package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpClimitId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpClimitId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String proposalNo;
	private String limitGrade;
	private Integer limitNo;
	private String limitType;
	private String currency;

	public PrpClimitId() {
	}

	@Column(name = "proposalno", nullable = false)
	public String getProposalNo() {
		return this.proposalNo;
	}

	public void setProposalNo(String proposalNo) {
		this.proposalNo = proposalNo;
	}

	@Column(name = "limitgrade", nullable = false)
	public String getLimitGrade() {
		return this.limitGrade;
	}

	public void setLimitGrade(String limitGrade) {
		this.limitGrade = limitGrade;
	}

	@Column(name = "limitno", nullable = false)
	public Integer getLimitNo() {
		return this.limitNo;
	}

	public void setLimitNo(Integer limitNo) {
		this.limitNo = limitNo;
	}

	@Column(name = "limittype", nullable = false)
	public String getLimitType() {
		return this.limitType;
	}

	public void setLimitType(String limitType) {
		this.limitType = limitType;
	}

	@Column(name = "currency", nullable = false)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpClimitId))
			return false;
		PrpClimitId castOther = (PrpClimitId) other;

		return ((this.getProposalNo() == castOther.getProposalNo()) || (this
				.getProposalNo() != null
				&& castOther.getProposalNo() != null && this.getProposalNo()
				.equals(castOther.getProposalNo())))
				&& ((this.getLimitGrade() == castOther.getLimitGrade()) || (this
						.getLimitGrade() != null
						&& castOther.getLimitGrade() != null && this
						.getLimitGrade().equals(castOther.getLimitGrade())))
				&& ((this.getLimitNo() == castOther.getLimitNo()) || (this
						.getLimitNo() != null
						&& castOther.getLimitNo() != null && this.getLimitNo()
						.equals(castOther.getLimitNo())))
				&& ((this.getLimitType() == castOther.getLimitType()) || (this
						.getLimitType() != null
						&& castOther.getLimitType() != null && this
						.getLimitType().equals(castOther.getLimitType())))
				&& ((this.getCurrency() == castOther.getCurrency()) || (this
						.getCurrency() != null
						&& castOther.getCurrency() != null && this
						.getCurrency().equals(castOther.getCurrency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProposalNo() == null ? 0 : this.getProposalNo()
						.hashCode());
		result = 37
				* result
				+ (getLimitGrade() == null ? 0 : this.getLimitGrade()
						.hashCode());
		result = 37 * result
				+ (getLimitNo() == null ? 0 : this.getLimitNo().hashCode());
		result = 37 * result
				+ (getLimitType() == null ? 0 : this.getLimitType().hashCode());
		result = 37 * result
				+ (getCurrency() == null ? 0 : this.getCurrency().hashCode());
		return result;
	}

}
