package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrpCopyFee generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcopyfee")
public class PrpCopyFee implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 币别 */
	private PrpCopyFeeId id;
	/** 批单申请号 */
	private PrpCopyMain prpCopyMain;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 总保额 */
	private BigDecimal amount;
	/** 应收保费 */
	private BigDecimal premium;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;
	/** 总税额 */
    private BigDecimal sumTaxFee;
    /** 总净保费 */
    private BigDecimal sumNetPremium;
    /** 总共方税额 */
	private BigDecimal sumTaxFee_gb;
	/** 总联方税额 */
	private BigDecimal sumTaxFee_lb;
	/** 总联方税额 */
	private BigDecimal sumTaxFee_ys;
	public PrpCopyFee() {
	}

	/**       
	 * 币别
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "currency", column = @Column(name = "currency", nullable = false)) })
	public PrpCopyFeeId getId() {
		return this.id;
	}

	public void setId(PrpCopyFeeId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpCopyMain getPrpCopyMain() {
		return this.prpCopyMain;
	}

	public void setPrpCopyMain(PrpCopyMain prpCopyMain) {
		this.prpCopyMain = prpCopyMain;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 总保额
	 */

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**       
	 * 应收保费
	 */

	@Column(name = "premium")
	public BigDecimal getPremium() {
		return this.premium;
	}

	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
    
	/**       
	 * 总税额
	 */
	public BigDecimal getSumTaxFee() {
		return sumTaxFee;
	}

	public void setSumTaxFee(BigDecimal sumTaxFee) {
		this.sumTaxFee = sumTaxFee;
	}
     
	/**       
	 * 总净收保费
	 */
	public BigDecimal getSumNetPremium() {
		return sumNetPremium;
	}

	public void setSumNetPremium(BigDecimal sumNetPremium) {
		this.sumNetPremium = sumNetPremium;
	}
    
	/**       
	 * 总共方税额
	 */
	@Column(name = "sumTaxFee_gb")
	public BigDecimal getSumTaxFee_gb() {
		return sumTaxFee_gb;
	}

	public void setSumTaxFee_gb(BigDecimal sumTaxFee_gb) {
		this.sumTaxFee_gb = sumTaxFee_gb;
	}
	/**       
	 * 总联方税额
	 */
	@Column(name = "sumtaxFee_lb")
	public BigDecimal getSumTaxFee_lb() {
		return sumTaxFee_lb;
	}

	public void setSumTaxFee_lb(BigDecimal sumTaxFee_lb) {
		this.sumTaxFee_lb = sumTaxFee_lb;
	}
	@Column(name = "sumTaxFee_ys")
	public BigDecimal getSumTaxFee_ys() {
		return sumTaxFee_ys;
	}

	public void setSumTaxFee_ys(BigDecimal sumTaxFee_ys) {
		this.sumTaxFee_ys = sumTaxFee_ys;
	}
	
}
