package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrpCopyDeduction generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcopydeduction")
public class PrpCopyDeduction implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 序号 */
	private PrpCopyDeductionId id;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 责任代码 */
	private String liabCode;
	/** 项目代码 */
	private String projectCode;
	/** 标的项目类别代码 */
	private String itemCode;
	/** 险别代码 */
	private String kindCode;
	/** 险别名称 */
	private String kindName;
	/** 币别 */
	private String currency;
	/** 冲减保额/赔款金额 */
	private BigDecimal endorAmount;
	/** 冲减天数 */
	private Long endorDays;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpCopyDeduction() {
	}

	/**       
	 * 序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "compensateNo", column = @Column(name = "compensateno", nullable = false)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "itemno", nullable = false)),
			@AttributeOverride(name = "itemKindNo", column = @Column(name = "itemkindno", nullable = false)) })
	public PrpCopyDeductionId getId() {
		return this.id;
	}

	public void setId(PrpCopyDeductionId id) {
		this.id = id;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno")
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 责任代码
	 */

	@Column(name = "liabcode", nullable = false)
	public String getLiabCode() {
		return this.liabCode;
	}

	public void setLiabCode(String liabCode) {
		this.liabCode = liabCode;
	}

	/**       
	 * 项目代码
	 */

	@Column(name = "projectcode", nullable = false)
	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	/**       
	 * 标的项目类别代码
	 */

	@Column(name = "itemcode", nullable = false)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	/**       
	 * 险别代码
	 */

	@Column(name = "kindcode", nullable = false)
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	/**       
	 * 险别名称
	 */

	@Column(name = "kindname")
	public String getKindName() {
		return this.kindName;
	}

	public void setKindName(String kindName) {
		this.kindName = kindName;
	}

	/**       
	 * 币别
	 */

	@Column(name = "currency")
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/**       
	 * 冲减保额/赔款金额
	 */

	@Column(name = "endoramount")
	public BigDecimal getEndorAmount() {
		return this.endorAmount;
	}

	public void setEndorAmount(BigDecimal endorAmount) {
		this.endorAmount = endorAmount;
	}

	/**       
	 * 冲减天数
	 */

	@Column(name = "endordays")
	public Long getEndorDays() {
		return this.endorDays;
	}

	public void setEndorDays(Long endorDays) {
		this.endorDays = endorDays;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

}
