package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrpCitem generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcitem")
public class PrpCitem implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 标的序号 */
	private PrpCitemId id;
	/** 投保单号码 */
	private PrpCmain prpCmain;
	/** 险种代码 */
	private String riskCode;
	/** 标的项目类别代码 */
	private String itemCode;
	/** 标的项目类别名称 */
	private String itemName;
	/** 加成比例 */
	private BigDecimal plusRate;
	/** 地址序号 */
	private Integer addressNo;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;
	private List<PrpCitemHouse> prpCitemHouses = new ArrayList<PrpCitemHouse>(0);
	private List<PrpCitemOil> prpCitemOils = new ArrayList<PrpCitemOil>(0);
	private List<PrpCitemCargo> prpCitemCargos = new ArrayList<PrpCitemCargo>(0);
	private List<PrpCitemShip> prpCitemShips = new ArrayList<PrpCitemShip>(0);
	private List<PrpCitemPlane> prpCitemPlanes = new ArrayList<PrpCitemPlane>(0);
	private List<PrpCitemAgri> prpCitemAgris = new ArrayList<PrpCitemAgri>(0);
	private List<PrpCitemProp> prpCitemProps = new ArrayList<PrpCitemProp>(0);
	private List<PrpCitemDevice> prpCitemDevices = new ArrayList<PrpCitemDevice>(
			0);
	private List<PrpCitemTravelAgency> prpCitemTravelAgencys = new ArrayList<PrpCitemTravelAgency>(
			0);
	private List<PrpCitemAnimal> prpCitemAnimals = new ArrayList<PrpCitemAnimal>(
			0);
	private List<PrpCitemAgriRelated> prpCitemAgriRelateds = new ArrayList<PrpCitemAgriRelated>(0);
	
	public PrpCitem() {
	}

	/**       
	 * 标的序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "proposalNo", column = @Column(name = "proposalno", nullable = false)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "itemno", nullable = false)) })
	public PrpCitemId getId() {
		return this.id;
	}

	public void setId(PrpCitemId id) {
		this.id = id;
	}

	/**       
	 * 投保单号码
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proposalno", nullable = false, insertable = false, updatable = false)
	public PrpCmain getPrpCmain() {
		return this.prpCmain;
	}

	public void setPrpCmain(PrpCmain prpCmain) {
		this.prpCmain = prpCmain;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 标的项目类别代码
	 */

	@Column(name = "itemcode")
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	/**       
	 * 标的项目类别名称
	 */

	@Column(name = "itemname")
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**       
	 * 加成比例
	 */

	@Column(name = "plusrate")
	public BigDecimal getPlusRate() {
		return this.plusRate;
	}

	public void setPlusRate(BigDecimal plusRate) {
		this.plusRate = plusRate;
	}

	/**       
	 * 地址序号
	 */

	@Column(name = "addressno")
	public Integer getAddressNo() {
		return this.addressNo;
	}

	public void setAddressNo(Integer addressNo) {
		this.addressNo = addressNo;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemHouse> getPrpCitemHouses() {
		return this.prpCitemHouses;
	}

	public void setPrpCitemHouses(List<PrpCitemHouse> prpCitemHouses) {
		this.prpCitemHouses = prpCitemHouses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemOil> getPrpCitemOils() {
		return this.prpCitemOils;
	}

	public void setPrpCitemOils(List<PrpCitemOil> prpCitemOils) {
		this.prpCitemOils = prpCitemOils;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemCargo> getPrpCitemCargos() {
		return this.prpCitemCargos;
	}

	public void setPrpCitemCargos(List<PrpCitemCargo> prpCitemCargos) {
		this.prpCitemCargos = prpCitemCargos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemShip> getPrpCitemShips() {
		return this.prpCitemShips;
	}

	public void setPrpCitemShips(List<PrpCitemShip> prpCitemShips) {
		this.prpCitemShips = prpCitemShips;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemPlane> getPrpCitemPlanes() {
		return this.prpCitemPlanes;
	}

	public void setPrpCitemPlanes(List<PrpCitemPlane> prpCitemPlanes) {
		this.prpCitemPlanes = prpCitemPlanes;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemAgri> getPrpCitemAgris() {
		return this.prpCitemAgris;
	}

	public void setPrpCitemAgris(List<PrpCitemAgri> prpCitemAgris) {
		this.prpCitemAgris = prpCitemAgris;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemProp> getPrpCitemProps() {
		return this.prpCitemProps;
	}

	public void setPrpCitemProps(List<PrpCitemProp> prpCitemProps) {
		this.prpCitemProps = prpCitemProps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemDevice> getPrpCitemDevices() {
		return this.prpCitemDevices;
	}

	public void setPrpCitemDevices(List<PrpCitemDevice> prpCitemDevices) {
		this.prpCitemDevices = prpCitemDevices;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemTravelAgency> getPrpCitemTravelAgencys() {
		return this.prpCitemTravelAgencys;
	}

	public void setPrpCitemTravelAgencys(List<PrpCitemTravelAgency> prpCitemTravelAgencys) {
		this.prpCitemTravelAgencys = prpCitemTravelAgencys;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemAnimal> getPrpCitemAnimals() {
		return prpCitemAnimals;
	}

	public void setPrpCitemAnimals(List<PrpCitemAnimal> prpCitemAnimals) {
		this.prpCitemAnimals = prpCitemAnimals;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpCitem")
	public List<PrpCitemAgriRelated> getPrpCitemAgriRelateds() {
		return prpCitemAgriRelateds;
	}

	public void setPrpCitemAgriRelateds(
			List<PrpCitemAgriRelated> prpCitemAgriRelateds) {
		this.prpCitemAgriRelateds = prpCitemAgriRelateds;
	}
	
	
}
