package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpCitemKindId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCitemKindEMId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String quoteNo;
	private Integer quoteId;

	public PrpCitemKindEMId() {
	}

	@Column(name = "quoteno", nullable = false)
	public String getQuoteNo() {
		return quoteNo;
	}

	public void setQuoteNo(String quoteNo) {
		this.quoteNo = quoteNo;
	}

	@Column(name = "quoteid", nullable = false)
		public Integer getQuoteId() {
		return quoteId;
	}

	public void setQuoteId(Integer quoteId) {
		this.quoteId = quoteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpCitemKindZId))
			return false;
		PrpCitemKindEMId castOther = (PrpCitemKindEMId) other;

		return ((this.getQuoteNo() == castOther.getQuoteNo()) || (this
				.getQuoteNo() != null
				&& castOther.getQuoteNo() != null && this.getQuoteNo()
				.equals(castOther.getQuoteNo())))
				&& ((this.getQuoteId() == castOther.getQuoteId()) || (this
						.getQuoteId() != null
						&& castOther.getQuoteId() != null && this
						.getQuoteId().equals(castOther.getQuoteId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getQuoteNo() == null ? 0 : this.getQuoteNo()
						.hashCode());
		result = 37
				* result
				+ (getQuoteId() == null ? 0 : this.getQuoteId()
						.hashCode());
		return result;
	}



}
