package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpCopyTrafficDetailId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCopyTrafficDetailId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer itemNo;
	private Integer serialNo;
	private String applyNo;

	public PrpCopyTrafficDetailId() {
	}

	@Column(name = "itemno", nullable = false)
	public Integer getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(Integer itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "serialno", nullable = false)
	public Integer getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Integer serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "applyno", nullable = false)
	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpCopyTrafficDetailId))
			return false;
		PrpCopyTrafficDetailId castOther = (PrpCopyTrafficDetailId) other;

		return ((this.getItemNo() == castOther.getItemNo()) || (this
				.getItemNo() != null
				&& castOther.getItemNo() != null && this.getItemNo().equals(
				castOther.getItemNo())))
				&& ((this.getSerialNo() == castOther.getSerialNo()) || (this
						.getSerialNo() != null
						&& castOther.getSerialNo() != null && this
						.getSerialNo().equals(castOther.getSerialNo())))
				&& ((this.getApplyNo() == castOther.getApplyNo()) || (this
						.getApplyNo() != null
						&& castOther.getApplyNo() != null && this.getApplyNo()
						.equals(castOther.getApplyNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getSerialNo() == null ? 0 : this.getSerialNo().hashCode());
		result = 37 * result
				+ (getApplyNo() == null ? 0 : this.getApplyNo().hashCode());
		return result;
	}

}
