package com.sinosoft.fccb.policy.common.model;
// Generated 2010-5-13 12:56:45 by Hibernate Tools 3.2.0.b9-sinosoft1.1


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
* PrpCopyMain generated by Tools.Don't edit.
 */
@Entity
@Table(name="prpcopymain"
)
public class PrpCopyMain  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    

    /** 批单申请号 */
    private String applyNo;
    /** 保单号 */
    private String policyNo;
    /** 险类代码 */
    private String classCode;
    /** 险种代码 */
    private String riskCode;
    /** 项目代码 */
    private String projectCode;
    /** 合同号 */
    private String contractNo;
    /** 保单种类 */
    private String policySort;
    /** 业务性质 */
    private String businessNature;
    /** 语种 */
    private String language;
    /** 保单类型 */
    private String policyType;
    /** 涉农标志 */
    private String agriFlag;
    /** OperateDate */
    private Date operateDate;
    /** 起运日期 */
    private Date startDate;
    /** 起保小时 */
    private Integer startHour;
    /** 生效终止日期 */
    private Date endDate;
    /** 终保小时 */
    private Integer endHour;
    /** 净费率 */
    private BigDecimal pureRate;
    /** 手续费率/浮动费率 */
    private BigDecimal disRate;
    /** 折扣率 */
    private BigDecimal discount;
    /** 币别 */
    private String currency;
    /** 货物价值 */
    private BigDecimal sumValue;
    /** 总保额 */
    private BigDecimal sumAmount;
    /** 总折扣金额 */
    private BigDecimal sumDiscount;
    /** 总保费 */
    private BigDecimal sumPremium;
    /** 总附加险保费 */
    private BigDecimal sumSubPrem;
    /** 被保险总数量/人数/户数 */
    private Integer sumQuantity;
    /** 投保人数 */
    private Integer insuredCount;
    /** 保单数量 */
    private Integer policyCount;
    /** 司法管辖 */
    private String judicalScope;
    /** 是否自动转帐续保标志 */
    private String autoTransRenewFlag;
    /** 争议解决方式 */
    private String argueSolution;
    /** 仲裁委员会名称 */
    private String arbitBoardName;
    /** 约定分期交费次数 */
    private Integer payTimes;
    /** 出单机构 */
    private String makeCom;
    /** 签单地点 */
    private String operateSite;
    /** 归属机构 */
    private String comCode;
    /** 经办人代码 */
    private String handlerCode;
    /** 归属人 */
    private String handler1Code;
    /** 复核人代码 */
    private String approverCode;
    /** 初审标志 */
    private String checkFlag;
    /** 初审员 */
    private String checkUpCode;
    /** 初审意见 */
    private String checkOpinion;
    /** 最终核保人代码 */
    private String underWriteCode;
    /** 最终核保人名称 */
    private String underWriteName;
    /** 操作员代码 */
    private String operatorCode;
    /** 报表数据生成日期 */
    private Date inputTime;
    /** 核保完成日期 */
    private Date underWriteEndDate;
    /** 保单统计年月 */
    private Date statisticsYM;
    /** 代理人代码 */
    private String agentCode;
    /** 联共保标志 */
    private String coinsFlag;
    /** 交叉销售标志 */
    private String crossFlag;
    /** 商业分保标志 */
    private String reinsFlag;
    /** 统保标志 */
    private String allinsFlag;
    /** 复核员 */
    private String checkCode;
    /** 核保标志 */
    private String underWriteFlag;
    /** 见费出单标志 */
    private String jfeeFlag;
    /** 保险费支付办法 */
    private String payMode;
    /** 其它标志字段 */
    private String othFlag;
    /** 政策性业务方案代码 */
    private String policyRelCode;
    /** 政策性业务方案名称 */
    private String policyRelName;
    /** 是否迁移数据 */
    private String dmFlag;
	/**是否倒补录*/
	private String inputFlag;
    /** 备注 */
    private String remark;
    /** 短信转存后是否删除标记 */
    private String flag;
    /** 批单号 */
    private String endorseNo;
    /** 生效日期 */
    private Date validDate;
    /** 生效小时 */
    private Integer validHour;
    /** 批改次序 */
    private Integer endorseTimes;
    /** 插入时间 */
    private Date insertTimeForHis;
    /** 更新时间 */
    private Date operateTimeForHis;
    
    //RYANGQH2013042201:总部出单功能，增加projectCodeZ
    private String projectCodeZ;
    /** 总税额 */
	private BigDecimal sumTaxFee;
	/** 总净保费 */
	private BigDecimal sumNetPremium;
    private List<PrpCopyItem> prpCopyItems = new ArrayList<PrpCopyItem>(0);
    private List<PrpCopyMainSub> prpCopyMainSubs = new ArrayList<PrpCopyMainSub>(0);
    private List<PrpCopyCommission> prpCopyCommissions = new ArrayList<PrpCopyCommission>(0);
    private List<PrpCopyCommissionDetail> prpCopyCommissionDetails = new ArrayList<PrpCopyCommissionDetail>(0);
    private List<PrpCopyEngage> prpCopyEngages = new ArrayList<PrpCopyEngage>(0);
    private List<PrpCopyMainAgri> prpCopyMainAgris = new ArrayList<PrpCopyMainAgri>(0);
    private List<PrpCopyBatch> prpCopyBatchs = new ArrayList<PrpCopyBatch>(0);
    private List<PrpCopyItemCar> prpCopyItemCars = new ArrayList<PrpCopyItemCar>(0);
    private List<PrpCopyCoeff> prpCopyCoeffs = new ArrayList<PrpCopyCoeff>(0);
    private List<PrpCopyHandler> prpCopyHandlers = new ArrayList<PrpCopyHandler>(0);
    private List<PrpCopyMainCargo> prpCopyMainCargos = new ArrayList<PrpCopyMainCargo>(0);
    private List<PrpCopyMainCredit> prpCopyMainCredits = new ArrayList<PrpCopyMainCredit>(0);
    private List<PrpCopyAddress> prpCopyAddresses = new ArrayList<PrpCopyAddress>(0);
    private List<PrpCopyMainConstruct> prpCopyMainConstructs = new ArrayList<PrpCopyMainConstruct>(0);
    private List<PrpCopyInsured> prpCopyInsureds = new ArrayList<PrpCopyInsured>(0);
    private List<PrpCopyMainInvest> prpCopyMainInvests = new ArrayList<PrpCopyMainInvest>(0);
    private List<PrpCopyName> prpCopyNames = new ArrayList<PrpCopyName>(0);
    private List<PrpCopyItemKind> prpCopyItemKinds = new ArrayList<PrpCopyItemKind>(0);
    private List<PrpCopyMainProp> prpCopyMainProps = new ArrayList<PrpCopyMainProp>(0);
    private List<PrpCopyGuaranty> prpCopyGuaranties = new ArrayList<PrpCopyGuaranty>(0);
    private List<PrpCopyCarShipTax> prpCopyCarShipTaxes = new ArrayList<PrpCopyCarShipTax>(0);
    private List<PrpCopyAgent> prpCopyAgents = new ArrayList<PrpCopyAgent>(0);
    private List<PrpCopyExtendInfo> prpCopyExtendInfos = new ArrayList<PrpCopyExtendInfo>(0);
    private List<PrpCopyMainAirLine> prpCopyMainAirLines = new ArrayList<PrpCopyMainAirLine>(0);
    private List<PrpCopyStampTax> prpCopyStampTaxes = new ArrayList<PrpCopyStampTax>(0);
    private List<PrpCopyRation> prpCopyRations = new ArrayList<PrpCopyRation>(0);
    private List<PrpCopyCoinsDetail> prpCopyCoinsDetails = new ArrayList<PrpCopyCoinsDetail>(0);
    private List<PrpCopyPlan> prpCopyPlans = new ArrayList<PrpCopyPlan>(0);
    private List<PrpCopyFee> prpCopyFees = new ArrayList<PrpCopyFee>(0);
    private List<PrpCopyMainChannel> prpCopyMainChannels = new ArrayList<PrpCopyMainChannel>(0);
    private List<PrpCopySpecialFac> prpCopySpecialFacs = new ArrayList<PrpCopySpecialFac>(0);
    private List<PrpCopyProfitFactor> prpCopyProfitFactors = new ArrayList<PrpCopyProfitFactor>(0);
    private List<PrpCopyAgentDetail> prpCopyAgentDetails = new ArrayList<PrpCopyAgentDetail>(0);
    private List<PrpCopyMainLoan> prpCopyMainLoans = new ArrayList<PrpCopyMainLoan>(0);
    private List<PrpCopyLimit> prpCopyLimits = new ArrayList<PrpCopyLimit>(0);
    private List<PrpCopyMainLiab> prpCopyMainLiabs = new ArrayList<PrpCopyMainLiab>(0);
    private List<PrpCopyCoins> prpCopyCoinses = new ArrayList<PrpCopyCoins>(0);
    private List<PrpCopycargoDetail> prpCopyCargoDetails = new ArrayList<PrpCopycargoDetail>(0);
    private List<PrpCopyShipDriver> prpCopyShipDrivers = new ArrayList<PrpCopyShipDriver>(0);
    private List<PrpCopyclauseConfine> prpCopyclauseConfines = new ArrayList<PrpCopyclauseConfine>(0);
    private List<PrpCopyClause> prpCopyClauses = new ArrayList<PrpCopyClause>(0);
    //BUG26027 添加保单贡献对应Copy表 add by liangjianze 20120327 start
    private List<PrpCopyContriution> prpCopyContriutions = new ArrayList<PrpCopyContriution>(0);
    //BUG26027 添加保单贡献对应Copy表 add by liangjianze 20120327 end
    // 20120413 add
    private List<PrpCopyItemCreditOth> prpCopyItemCreditOths = new ArrayList<PrpCopyItemCreditOth>(0);
    //RZHANGT2012081301 重要客户 add by liangjianze 20120906
    private List<PrpCopyMainCommon> prpCopyMainCommons = new ArrayList<PrpCopyMainCommon>(0);
    //RZHANGT2012121201  能翻母猪标的库后续调整 add by liusaisai 20130109 
    private List<PrpCopyAnimal> prpCopyAnimals = new ArrayList<PrpCopyAnimal>(0);
    //RLIUBIN2013091601 LXK浙江省农业保险共保体组合产品保费计算
    private List<PrpCopyClauseplan> PrpCopyClauseplans = new ArrayList<PrpCopyClauseplan>(0);
	public PrpCopyMain() {
    }
   
    /**       
     * 批单申请号
     */
     @Id 
    
    @Column(name="applyno", unique=true, nullable=false)
    public String getApplyNo() {
        return this.applyNo;
    }
    
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }
    /**       
     * 保单号
     */
    
    @Column(name="policyno", nullable=false)
    public String getPolicyNo() {
        return this.policyNo;
    }
    
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }
    /**       
     * 险类代码
     */
    
    @Column(name="classcode", nullable=false)
    public String getClassCode() {
        return this.classCode;
    }
    
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }
    /**       
     * 险种代码
     */
    
    @Column(name="riskcode", nullable=false)
    public String getRiskCode() {
        return this.riskCode;
    }
    
    public void setRiskCode(String riskCode) {
        this.riskCode = riskCode;
    }
    /**       
     * 项目代码
     */
    
    @Column(name="projectcode")
    public String getProjectCode() {
        return this.projectCode;
    }
    
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }
    /**       
     * 合同号
     */
    
    @Column(name="contractno")
    public String getContractNo() {
        return this.contractNo;
    }
    
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }
    /**       
     * 保单种类
     */
    
    @Column(name="policysort", nullable=false)
    public String getPolicySort() {
        return this.policySort;
    }
    
    public void setPolicySort(String policySort) {
        this.policySort = policySort;
    }
    /**       
     * 业务性质
     */
    
    @Column(name="businessnature")
    public String getBusinessNature() {
        return this.businessNature;
    }
    
    public void setBusinessNature(String businessNature) {
        this.businessNature = businessNature;
    }
    /**       
     * 语种
     */
    
    @Column(name="language")
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    /**       
     * 保单类型
     */
    
    @Column(name="policytype")
    public String getPolicyType() {
        return this.policyType;
    }
    
    public void setPolicyType(String policyType) {
        this.policyType = policyType;
    }
    /**       
     * 涉农标志
     */
    @Column(name="agriflag")
     public String getAgriFlag() {
		return agriFlag;
	}

	public void setAgriFlag(String agriFlag) {
		this.agriFlag = agriFlag;
	}
    /**       
     * OperateDate
     */
    
    @Column(name="operatedate")
    public Date getOperateDate() {
        return this.operateDate;
    }
    
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }
    /**       
     * 起运日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name="startdate")
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    /**       
     * 起保小时
     */
    
    @Column(name="starthour")
    public Integer getStartHour() {
        return this.startHour;
    }
    
    public void setStartHour(Integer startHour) {
        this.startHour = startHour;
    }
    /**       
     * 生效终止日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name="enddate")
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    /**       
     * 终保小时
     */
    
    @Column(name="endhour")
    public Integer getEndHour() {
        return this.endHour;
    }
    
    public void setEndHour(Integer endHour) {
        this.endHour = endHour;
    }
    /**       
     * 净费率
     */
    
    @Column(name="purerate")
    public BigDecimal getPureRate() {
        return this.pureRate;
    }
    
    public void setPureRate(BigDecimal pureRate) {
        this.pureRate = pureRate;
    }
    /**       
     * 手续费率/浮动费率
     */
    
    @Column(name="disrate")
    public BigDecimal getDisRate() {
        return this.disRate;
    }
    
    public void setDisRate(BigDecimal disRate) {
        this.disRate = disRate;
    }
    /**       
     * 折扣率
     */
    
    @Column(name="discount")
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }
    /**       
     * 币别
     */
    
    @Column(name="currency")
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    /**       
     * 货物价值
     */
    
    @Column(name="sumvalue")
    public BigDecimal getSumValue() {
        return this.sumValue;
    }
    
    public void setSumValue(BigDecimal sumValue) {
        this.sumValue = sumValue;
    }
    /**       
     * 总保额
     */
    
    @Column(name="sumamount")
    public BigDecimal getSumAmount() {
        return this.sumAmount;
    }
    
    public void setSumAmount(BigDecimal sumAmount) {
        this.sumAmount = sumAmount;
    }
    /**       
     * 总折扣金额
     */
    
    @Column(name="sumdiscount")
    public BigDecimal getSumDiscount() {
        return this.sumDiscount;
    }
    
    public void setSumDiscount(BigDecimal sumDiscount) {
        this.sumDiscount = sumDiscount;
    }
    /**       
     * 总保费
     */
    
    @Column(name="sumpremium")
    public BigDecimal getSumPremium() {
        return this.sumPremium;
    }
    
    public void setSumPremium(BigDecimal sumPremium) {
        this.sumPremium = sumPremium;
    }
    /**       
     * 总附加险保费
     */
    
    @Column(name="sumsubprem")
    public BigDecimal getSumSubPrem() {
        return this.sumSubPrem;
    }
    
    public void setSumSubPrem(BigDecimal sumSubPrem) {
        this.sumSubPrem = sumSubPrem;
    }
    /**       
     * 被保险总数量/人数/户数
     */
    
    @Column(name="sumquantity")
    public Integer getSumQuantity() {
        return this.sumQuantity;
    }
    
    public void setSumQuantity(Integer sumQuantity) {
        this.sumQuantity = sumQuantity;
    }
    /**       
     * 投保人数
     */
    
    @Column(name="insuredcount")
    public Integer getInsuredCount() {
        return this.insuredCount;
    }
    
    public void setInsuredCount(Integer insuredCount) {
        this.insuredCount = insuredCount;
    }
    /**       
     * 保单数量
     */
    
    @Column(name="policycount")
    public Integer getPolicyCount() {
        return this.policyCount;
    }
    
    public void setPolicyCount(Integer policyCount) {
        this.policyCount = policyCount;
    }
    /**       
     * 司法管辖
     */
    
    @Column(name="judicalscope")
    public String getJudicalScope() {
        return this.judicalScope;
    }
    
    public void setJudicalScope(String judicalScope) {
        this.judicalScope = judicalScope;
    }
    /**       
     * 是否自动转帐续保标志
     */
    
    @Column(name="autotransrenewflag")
    public String getAutoTransRenewFlag() {
        return this.autoTransRenewFlag;
    }
    
    public void setAutoTransRenewFlag(String autoTransRenewFlag) {
        this.autoTransRenewFlag = autoTransRenewFlag;
    }
    /**       
     * 争议解决方式
     */
    
    @Column(name="arguesolution")
    public String getArgueSolution() {
        return this.argueSolution;
    }
    
    public void setArgueSolution(String argueSolution) {
        this.argueSolution = argueSolution;
    }
    /**       
     * 仲裁委员会名称
     */
    
    @Column(name="arbitboardname")
    public String getArbitBoardName() {
        return this.arbitBoardName;
    }
    
    public void setArbitBoardName(String arbitBoardName) {
        this.arbitBoardName = arbitBoardName;
    }
    /**       
     * 约定分期交费次数
     */
    
    @Column(name="paytimes")
    public Integer getPayTimes() {
        return this.payTimes;
    }
    
    public void setPayTimes(Integer payTimes) {
        this.payTimes = payTimes;
    }
    /**       
     * 出单机构
     */
    
    @Column(name="makecom", nullable=false)
    public String getMakeCom() {
        return this.makeCom;
    }
    
    public void setMakeCom(String makeCom) {
        this.makeCom = makeCom;
    }
    /**       
     * 签单地点
     */
    
    @Column(name="operatesite")
    public String getOperateSite() {
        return this.operateSite;
    }
    
    public void setOperateSite(String operateSite) {
        this.operateSite = operateSite;
    }
    /**       
     * 归属机构
     */
    
    @Column(name="comcode", nullable=false)
    public String getComCode() {
        return this.comCode;
    }
    
    public void setComCode(String comCode) {
        this.comCode = comCode;
    }
    /**       
     * 经办人代码
     */
    
    @Column(name="handlercode")
    public String getHandlerCode() {
        return this.handlerCode;
    }
    
    public void setHandlerCode(String handlerCode) {
        this.handlerCode = handlerCode;
    }
    /**       
     * 归属人
     */
    
    @Column(name="handler1code")
    public String getHandler1Code() {
        return this.handler1Code;
    }
    
    public void setHandler1Code(String handler1Code) {
        this.handler1Code = handler1Code;
    }
    /**       
     * 复核人代码
     */
    
    @Column(name="approvercode")
    public String getApproverCode() {
        return this.approverCode;
    }
    
    public void setApproverCode(String approverCode) {
        this.approverCode = approverCode;
    }
    /**       
     * 初审标志
     */
    
    @Column(name="checkflag")
    public String getCheckFlag() {
        return this.checkFlag;
    }
    
    public void setCheckFlag(String checkFlag) {
        this.checkFlag = checkFlag;
    }
    /**       
     * 初审员
     */
    
    @Column(name="checkupcode")
    public String getCheckUpCode() {
        return this.checkUpCode;
    }
    
    public void setCheckUpCode(String checkUpCode) {
        this.checkUpCode = checkUpCode;
    }
    /**       
     * 初审意见
     */
    
    @Column(name="checkopinion")
    public String getCheckOpinion() {
        return this.checkOpinion;
    }
    
    public void setCheckOpinion(String checkOpinion) {
        this.checkOpinion = checkOpinion;
    }
    /**       
     * 最终核保人代码
     */
    
    @Column(name="underwritecode")
    public String getUnderWriteCode() {
        return this.underWriteCode;
    }
    
    public void setUnderWriteCode(String underWriteCode) {
        this.underWriteCode = underWriteCode;
    }
    /**       
     * 最终核保人名称
     */
    
    @Column(name="underwritename")
    public String getUnderWriteName() {
        return this.underWriteName;
    }
    
    public void setUnderWriteName(String underWriteName) {
        this.underWriteName = underWriteName;
    }
    /**       
     * 操作员代码
     */
    
    @Column(name="operatorcode")
    public String getOperatorCode() {
        return this.operatorCode;
    }
    
    public void setOperatorCode(String operatorCode) {
        this.operatorCode = operatorCode;
    }
    /**       
     * 报表数据生成日期
     */
    
    @Column(name="inputtime")
    public Date getInputTime() {
        return this.inputTime;
    }
    
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }
    /**       
     * 核保完成日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name="underwriteenddate")
    public Date getUnderWriteEndDate() {
        return this.underWriteEndDate;
    }
    
    public void setUnderWriteEndDate(Date underWriteEndDate) {
        this.underWriteEndDate = underWriteEndDate;
    }
    /**       
     * 保单统计年月
     */
    
    @Column(name="statisticsym")
    public Date getStatisticsYM() {
        return this.statisticsYM;
    }
    
    public void setStatisticsYM(Date statisticsYM) {
        this.statisticsYM = statisticsYM;
    }
    /**       
     * 代理人代码
     */
    
    @Column(name="agentcode")
    public String getAgentCode() {
        return this.agentCode;
    }
    
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }
    /**       
     * 联共保标志
     */
    
    @Column(name="coinsflag")
    public String getCoinsFlag() {
        return this.coinsFlag;
    }
    
    public void setCoinsFlag(String coinsFlag) {
        this.coinsFlag = coinsFlag;
    }
    /**       
     * 交叉销售标志
     */
    
    @Column(name="crossflag")
    public String getCrossFlag() {
        return this.crossFlag;
    }
    
    public void setCrossFlag(String crossFlag) {
        this.crossFlag = crossFlag;
    }
    /**       
     * 商业分保标志
     */
    
    @Column(name="reinsflag")
    public String getReinsFlag() {
        return this.reinsFlag;
    }
    
    public void setReinsFlag(String reinsFlag) {
        this.reinsFlag = reinsFlag;
    }
    /**       
     * 统保标志
     */
    
    @Column(name="allinsflag")
    public String getAllinsFlag() {
        return this.allinsFlag;
    }
    
    public void setAllinsFlag(String allinsFlag) {
        this.allinsFlag = allinsFlag;
    }
    
    /**       
     * 复核员
     */
    
    @Column(name="checkCode")
    public String getCheckCode() {
        return this.checkCode;
    }
    
    public void setCheckCode(String checkCode) {
        this.checkCode = checkCode;
    }
    
    /**       
     * 核保标志
     */
    
    @Column(name="underwriteflag")
    public String getUnderWriteFlag() {
        return this.underWriteFlag;
    }
    
    public void setUnderWriteFlag(String underWriteFlag) {
        this.underWriteFlag = underWriteFlag;
    }
    /**       
     * 见费出单标志
     */
    
    @Column(name="jfeeflag")
    public String getJfeeFlag() {
        return this.jfeeFlag;
    }
    
    public void setJfeeFlag(String jfeeFlag) {
        this.jfeeFlag = jfeeFlag;
    }
    /**       
     * 保险费支付办法
     */
    
    @Column(name="paymode")
    public String getPayMode() {
        return this.payMode;
    }
    
    public void setPayMode(String payMode) {
        this.payMode = payMode;
    }
    /**       
     * 其它标志字段
     */
    
    @Column(name="othflag")
    public String getOthFlag() {
        return this.othFlag;
    }
    
    public void setOthFlag(String othFlag) {
        this.othFlag = othFlag;
    }
    /**       
     * 政策性业务方案代码
     */
    
    @Column(name="policyrelcode")
    public String getPolicyRelCode() {
        return this.policyRelCode;
    }
    
    public void setPolicyRelCode(String policyRelCode) {
        this.policyRelCode = policyRelCode;
    }
    /**       
     * 政策性业务方案名称
     */
    
    @Column(name="policyrelname")
    public String getPolicyRelName() {
        return this.policyRelName;
    }
    
    public void setPolicyRelName(String policyRelName) {
        this.policyRelName = policyRelName;
    }
    /**       
     * 是否迁移数据
     */
    
    @Column(name="dmflag")
    public String getDmFlag() {
        return this.dmFlag;
    }
    
    public void setDmFlag(String dmFlag) {
        this.dmFlag = dmFlag;
    }
	/**       
	 * 输入标志
	 */
	@Column(name = "inputflag")
	public String getInputFlag() {
		return this.inputFlag;
	}

	public void setInputFlag(String inputFlag) {
		this.inputFlag = inputFlag;
	}
    /**       
     * 备注
     */
    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    /**       
     * 短信转存后是否删除标记
     */
    
    @Column(name="flag")
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }
    /**       
     * 批单号
     */
    
    @Column(name="endorseno")
    public String getEndorseNo() {
        return this.endorseNo;
    }
    
    public void setEndorseNo(String endorseNo) {
        this.endorseNo = endorseNo;
    }
    /**       
     * 生效日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name="validdate")
    public Date getValidDate() {
        return this.validDate;
    }
    
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }
    /**       
     * 生效小时
     */
    
    @Column(name="validhour")
    public Integer getValidHour() {
        return this.validHour;
    }
    
    public void setValidHour(Integer validHour) {
        this.validHour = validHour;
    }
    /**       
     * 批改次序
     */
    
    @Column(name="endorsetimes")
    public Integer getEndorseTimes() {
        return this.endorseTimes;
    }
    
    public void setEndorseTimes(Integer endorseTimes) {
        this.endorseTimes = endorseTimes;
    }
    /**       
     * 插入时间
     */
    
    @Column(name="inserttimeforhis", insertable=false, updatable=false)
    public Date getInsertTimeForHis() {
        return this.insertTimeForHis;
    }
    
    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }
    /**       
     * 更新时间
     */
    
    @Column(name="operatetimeforhis", insertable=false)
    public Date getOperateTimeForHis() {
        return this.operateTimeForHis;
    }
    
    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }
    
    /**       
	 * 总税额
	 */
	
	@Column(name = "sumTaxFee")
	public BigDecimal getSumTaxFee() {
		return sumTaxFee;
	}

	public void setSumTaxFee(BigDecimal sumTaxFee) {
		this.sumTaxFee = sumTaxFee;
	}
	
	/**       
	 * 总净保费
	 */
	
	@Column(name = "sumNetPremium")
	public BigDecimal getSumNetPremium() {
		return sumNetPremium;
	}

	public void setSumNetPremium(BigDecimal sumNetPremium) {
		this.sumNetPremium = sumNetPremium;
	}

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyItem> getPrpCopyItems() {
        return this.prpCopyItems;
    }
    
    public void setPrpCopyItems(List<PrpCopyItem> prpCopyItems) {
        this.prpCopyItems = prpCopyItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainSub> getPrpCopyMainSubs() {
        return this.prpCopyMainSubs;
    }
    
    public void setPrpCopyMainSubs(List<PrpCopyMainSub> prpCopyMainSubs) {
        this.prpCopyMainSubs = prpCopyMainSubs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyCommission> getPrpCopyCommissions() {
        return this.prpCopyCommissions;
    }
    
    public void setPrpCopyCommissions(List<PrpCopyCommission> prpCopyCommissions) {
        this.prpCopyCommissions = prpCopyCommissions;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyCommissionDetail> getPrpCopyCommissionDetails() {
		return prpCopyCommissionDetails;
	}

	public void setPrpCopyCommissionDetails(
			List<PrpCopyCommissionDetail> prpCopyCommissionDetails) {
		this.prpCopyCommissionDetails = prpCopyCommissionDetails;
	}

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyEngage> getPrpCopyEngages() {
        return this.prpCopyEngages;
    }
    
    public void setPrpCopyEngages(List<PrpCopyEngage> prpCopyEngages) {
        this.prpCopyEngages = prpCopyEngages;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainAgri> getPrpCopyMainAgris() {
        return this.prpCopyMainAgris;
    }
    
    public void setPrpCopyMainAgris(List<PrpCopyMainAgri> prpCopyMainAgris) {
        this.prpCopyMainAgris = prpCopyMainAgris;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyBatch> getPrpCopyBatchs() {
        return this.prpCopyBatchs;
    }
    
    public void setPrpCopyBatchs(List<PrpCopyBatch> prpCopyBatchs) {
        this.prpCopyBatchs = prpCopyBatchs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyItemCar> getPrpCopyItemCars() {
        return this.prpCopyItemCars;
    }
    
    public void setPrpCopyItemCars(List<PrpCopyItemCar> prpCopyItemCars) {
        this.prpCopyItemCars = prpCopyItemCars;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyCoeff> getPrpCopyCoeffs() {
        return this.prpCopyCoeffs;
    }
    
    public void setPrpCopyCoeffs(List<PrpCopyCoeff> prpCopyCoeffs) {
        this.prpCopyCoeffs = prpCopyCoeffs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyHandler> getPrpCopyHandlers() {
        return this.prpCopyHandlers;
    }
    
    public void setPrpCopyHandlers(List<PrpCopyHandler> prpCopyHandlers) {
        this.prpCopyHandlers = prpCopyHandlers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainCargo> getPrpCopyMainCargos() {
        return this.prpCopyMainCargos;
    }
    
    public void setPrpCopyMainCargos(List<PrpCopyMainCargo> prpCopyMainCargos) {
        this.prpCopyMainCargos = prpCopyMainCargos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainCredit> getPrpCopyMainCredits() {
        return this.prpCopyMainCredits;
    }
    
    public void setPrpCopyMainCredits(List<PrpCopyMainCredit> prpCopyMainCredits) {
        this.prpCopyMainCredits = prpCopyMainCredits;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyAddress> getPrpCopyAddresses() {
        return this.prpCopyAddresses;
    }
    
    public void setPrpCopyAddresses(List<PrpCopyAddress> prpCopyAddresses) {
        this.prpCopyAddresses = prpCopyAddresses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainConstruct> getPrpCopyMainConstructs() {
        return this.prpCopyMainConstructs;
    }
    
    public void setPrpCopyMainConstructs(List<PrpCopyMainConstruct> prpCopyMainConstructs) {
        this.prpCopyMainConstructs = prpCopyMainConstructs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyInsured> getPrpCopyInsureds() {
        return this.prpCopyInsureds;
    }
    
    public void setPrpCopyInsureds(List<PrpCopyInsured> prpCopyInsureds) {
        this.prpCopyInsureds = prpCopyInsureds;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainInvest> getPrpCopyMainInvests() {
        return this.prpCopyMainInvests;
    }
    
    public void setPrpCopyMainInvests(List<PrpCopyMainInvest> prpCopyMainInvests) {
        this.prpCopyMainInvests = prpCopyMainInvests;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyName> getPrpCopyNames() {
        return this.prpCopyNames;
    }
    
    public void setPrpCopyNames(List<PrpCopyName> prpCopyNames) {
        this.prpCopyNames = prpCopyNames;
    }


@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyItemKind> getPrpCopyItemKinds() {
        return this.prpCopyItemKinds;
    }
    
    public void setPrpCopyItemKinds(List<PrpCopyItemKind> prpCopyItemKinds) {
        this.prpCopyItemKinds = prpCopyItemKinds;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainProp> getPrpCopyMainProps() {
        return this.prpCopyMainProps;
    }
    
    public void setPrpCopyMainProps(List<PrpCopyMainProp> prpCopyMainProps) {
        this.prpCopyMainProps = prpCopyMainProps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyGuaranty> getPrpCopyGuaranties() {
        return this.prpCopyGuaranties;
    }
    
    public void setPrpCopyGuaranties(List<PrpCopyGuaranty> prpCopyGuaranties) {
        this.prpCopyGuaranties = prpCopyGuaranties;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyCarShipTax> getPrpCopyCarShipTaxes() {
        return this.prpCopyCarShipTaxes;
    }
    
    public void setPrpCopyCarShipTaxes(List<PrpCopyCarShipTax> prpCopyCarShipTaxes) {
        this.prpCopyCarShipTaxes = prpCopyCarShipTaxes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyAgent> getPrpCopyAgents() {
        return this.prpCopyAgents;
    }
    
    public void setPrpCopyAgents(List<PrpCopyAgent> prpCopyAgents) {
        this.prpCopyAgents = prpCopyAgents;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyExtendInfo> getPrpCopyExtendInfos() {
        return this.prpCopyExtendInfos;
    }
    
    public void setPrpCopyExtendInfos(List<PrpCopyExtendInfo> prpCopyExtendInfos) {
        this.prpCopyExtendInfos = prpCopyExtendInfos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainAirLine> getPrpCopyMainAirLines() {
        return this.prpCopyMainAirLines;
    }
    
    public void setPrpCopyMainAirLines(List<PrpCopyMainAirLine> prpCopyMainAirLines) {
        this.prpCopyMainAirLines = prpCopyMainAirLines;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyStampTax> getPrpCopyStampTaxes() {
        return this.prpCopyStampTaxes;
    }
    
    public void setPrpCopyStampTaxes(List<PrpCopyStampTax> prpCopyStampTaxes) {
        this.prpCopyStampTaxes = prpCopyStampTaxes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyRation> getPrpCopyRations() {
        return this.prpCopyRations;
    }
    
    public void setPrpCopyRations(List<PrpCopyRation> prpCopyRations) {
        this.prpCopyRations = prpCopyRations;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyCoinsDetail> getPrpCopyCoinsDetails() {
        return this.prpCopyCoinsDetails;
    }
    
    public void setPrpCopyCoinsDetails(List<PrpCopyCoinsDetail> prpCopyCoinsDetails) {
        this.prpCopyCoinsDetails = prpCopyCoinsDetails;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyPlan> getPrpCopyPlans() {
        return this.prpCopyPlans;
    }
    
    public void setPrpCopyPlans(List<PrpCopyPlan> prpCopyPlans) {
        this.prpCopyPlans = prpCopyPlans;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyFee> getPrpCopyFees() {
        return this.prpCopyFees;
    }
    
    public void setPrpCopyFees(List<PrpCopyFee> prpCopyFees) {
        this.prpCopyFees = prpCopyFees;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainChannel> getPrpCopyMainChannels() {
        return this.prpCopyMainChannels;
    }
    
    public void setPrpCopyMainChannels(List<PrpCopyMainChannel> prpCopyMainChannels) {
        this.prpCopyMainChannels = prpCopyMainChannels;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopySpecialFac> getPrpCopySpecialFacs() {
        return this.prpCopySpecialFacs;
    }
    
    public void setPrpCopySpecialFacs(List<PrpCopySpecialFac> prpCopySpecialFacs) {
        this.prpCopySpecialFacs = prpCopySpecialFacs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyProfitFactor> getPrpCopyProfitFactors() {
        return this.prpCopyProfitFactors;
    }
    
    public void setPrpCopyProfitFactors(List<PrpCopyProfitFactor> prpCopyProfitFactors) {
        this.prpCopyProfitFactors = prpCopyProfitFactors;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyAgentDetail> getPrpCopyAgentDetails() {
        return this.prpCopyAgentDetails;
    }
    
    public void setPrpCopyAgentDetails(List<PrpCopyAgentDetail> prpCopyAgentDetails) {
        this.prpCopyAgentDetails = prpCopyAgentDetails;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainLoan> getPrpCopyMainLoans() {
        return this.prpCopyMainLoans;
    }
    
    public void setPrpCopyMainLoans(List<PrpCopyMainLoan> prpCopyMainLoans) {
        this.prpCopyMainLoans = prpCopyMainLoans;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyLimit> getPrpCopyLimits() {
        return this.prpCopyLimits;
    }
    
    public void setPrpCopyLimits(List<PrpCopyLimit> prpCopyLimits) {
        this.prpCopyLimits = prpCopyLimits;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainLiab> getPrpCopyMainLiabs() {
        return this.prpCopyMainLiabs;
    }
    
    public void setPrpCopyMainLiabs(List<PrpCopyMainLiab> prpCopyMainLiabs) {
        this.prpCopyMainLiabs = prpCopyMainLiabs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyCoins> getPrpCopyCoinses() {
        return this.prpCopyCoinses;
    }
    
    public void setPrpCopyCoinses(List<PrpCopyCoins> prpCopyCoinses) {
        this.prpCopyCoinses = prpCopyCoinses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopycargoDetail> getPrpCopyCargoDetails() {
		return prpCopyCargoDetails;
	}

	public void setPrpCopyCargoDetails(List<PrpCopycargoDetail> prpCopyCargoDetails) {
		this.prpCopyCargoDetails = prpCopyCargoDetails;
	}
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopyShipDriver> getPrpCopyShipDrivers() {
		return prpCopyShipDrivers;
	}

	public void setPrpCopyShipDrivers(List<PrpCopyShipDriver> prpCopyShipDrivers) {
		this.prpCopyShipDrivers = prpCopyShipDrivers;
	}
	
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopyclauseConfine> getPrpCopyclauseConfines() {
		return prpCopyclauseConfines;
	}

	public void setPrpCopyclauseConfines(List<PrpCopyclauseConfine> prpCopyclauseConfines) {
		this.prpCopyclauseConfines = prpCopyclauseConfines;
	}
	
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopyClause> getPrpCopyClauses() {
		return prpCopyClauses;
	}

	public void setPrpCopyClauses(List<PrpCopyClause> prpCopyClauses) {
		this.prpCopyClauses = prpCopyClauses;
	}
	//BUG26027 添加保单贡献对应Copy表 add by liangjianze 20120327 start
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopyContriution> getPrpCopyContriutions() {
		return prpCopyContriutions;
	}

	public void setPrpCopyContriutions(List<PrpCopyContriution> prpCopyContriutions) {
		this.prpCopyContriutions = prpCopyContriutions;
	}
	//BUG26027 添加保单贡献对应Copy表 add by liangjianze 20120327 start
	
	// 20120413 add 车贷添加其他信息
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopyItemCreditOth> getPrpCopyItemCreditOths() {
		return prpCopyItemCreditOths;
	}

	public void setPrpCopyItemCreditOths(
			List<PrpCopyItemCreditOth> prpCopyItemCreditOths) {
		this.prpCopyItemCreditOths = prpCopyItemCreditOths;
	}
	
	//RZHANGT2012081301 重要客户 add by liangjianze 20120906 start
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
    public List<PrpCopyMainCommon> getPrpCopyMainCommons() {
		return prpCopyMainCommons;
	}

	public void setPrpCopyMainCommons(List<PrpCopyMainCommon> prpCopyMainCommons) {
		this.prpCopyMainCommons = prpCopyMainCommons;
	}
	//RZHANGT2012081301 重要客户 add by liangjianze 20120906 end
	
	//RZHANGT2012121201  能翻母猪标的库后续调整 add by liusaisai 20130109 
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopyAnimal> getPrpCopyAnimals() {
		return prpCopyAnimals;
	}

	public void setPrpCopyAnimals(List<PrpCopyAnimal> prpCopyAnimals) {
		this.prpCopyAnimals = prpCopyAnimals;
	}
	
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCopyMain")
	public List<PrpCopyClauseplan> getPrpCopyClauseplans() {
		return PrpCopyClauseplans;
	}

	public void setPrpCopyClauseplans(List<PrpCopyClauseplan> prpCopyClauseplans) {
		PrpCopyClauseplans = prpCopyClauseplans;
	}

	@Transient
	public String getProjectCodeZ() {
		return projectCodeZ;
	}

	public void setProjectCodeZ(String projectCodeZ) {
		this.projectCodeZ = projectCodeZ;
	}
}


