package com.sinosoft.fccb.policy.common.model;
// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
* PrpCrationId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCrationId  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private String proposalNo;
     private String modeCode;

    public PrpCrationId() {
    }

   

    @Column(name="proposalno")
    public String getProposalNo() {
        return this.proposalNo;
    }
    
    public void setProposalNo(String proposalNo) {
        this.proposalNo = proposalNo;
    }

    @Column(name="modecode")
    public String getModeCode() {
        return this.modeCode;
    }
    
    public void setModeCode(String modeCode) {
        this.modeCode = modeCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrpCrationId) ) return false;
		 PrpCrationId castOther = ( PrpCrationId ) other; 
         
		 return ( (this.getProposalNo()==castOther.getProposalNo()) || ( this.getProposalNo()!=null && castOther.getProposalNo()!=null && this.getProposalNo().equals(castOther.getProposalNo()) ) )
 && ( (this.getModeCode()==castOther.getModeCode()) || ( this.getModeCode()!=null && castOther.getModeCode()!=null && this.getModeCode().equals(castOther.getModeCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProposalNo() == null ? 0 : this.getProposalNo().hashCode() );
         result = 37 * result + ( getModeCode() == null ? 0 : this.getModeCode().hashCode() );
         return result;
   }   


}


