package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpCitemCar generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcitem_car")
public class PrpCitemCar implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 标的序号 */
	private PrpCitemCarId id;
	/** 投保单号码 */
	private PrpCmain prpCmain;
	/** 险种代码 */
	private String riskCode;
	/** 保户类别代码 */
	private String insuredTypeCode;
	/** 被保险人与车辆关系 */
	private String carInsuredRelation;
	/** 条款类别（选择代码） */
	private String clauseType;
	/** 是否外地车 */
	private String nonlocalFlag;
	/** 是否已上牌照 */
	private String licenseFlag;
	/** 车牌号码 */
	private String licenseNo;
	/** 车牌种类 */
	private String licenseType;
	/** 车牌底色代码 */
	private String licenseColorCode;
	/** 车辆种类代码 */
	private String carKindCode;
	/** 是否港澳车标志 */
	private String hkFlag;
	/** 港澳车牌号码 */
	private String hkLicenseNo;
	/** EngineNo */
	private String engineNo;
	/** VIN号 */
	private String vinNo;
	/** 车架号 */
	private String frameNo;
	/** 行驶区域代码 */
	private String runAreaCode;
	/** 行驶区域名称 */
	private String runAreaName;
	/** 行驶里程(公里) */
	private BigDecimal runMiles;
	/** 初登日期 */
	private Date enrollDate;
	/** 使用年限 */
	private BigDecimal useYears;
	/** 车型代码 */
	private String modelCode;
	/** 品牌名称 */
	private String brandName;
	/** 车型别名 */
	private String aliasName;
	/** 国别性质 */
	private String countryNature;
	/** 国家代码 */
	private String countryCode;
	/** 使用性质代码 */
	private String useNatureCode;
	/** 营业性质分类代码 */
	private String businessClassCode;
	/** 座位数 */
	private Integer seatCount;
	/** 吨位数 */
	private BigDecimal tonCount;
	/** 排量 */
	private BigDecimal exhaustScale;
	/** 整备质量 */
	private BigDecimal carLotEquQuality;
	/** 车身颜色代码 */
	private String colorCode;
	/** 安全配置 */
	private String safeDevice;
	/** 车损车型系数 */
	private BigDecimal coefficient1;
	/** 盗抢车型系数 */
	private BigDecimal coefficient2;
	/** 其他车型系数 */
	private BigDecimal coefficient3;
	/** 其他性质 */
	private String otherNature;
	/** 费率号次 */
	private String rateCode;
	/** 生产日期 */
	private Date makeDate;
	/** 购车用途 */
	private String carUsage;
	/** 币别 */
	private String currency;
	/** 新件购置价 */
	private BigDecimal purchasePrice;
	/** 实际价值 */
	private BigDecimal actualValue;
	/** 发票号 */
	private String invoiceNo;
	/** 是否在我公司投保信用或保证 */
	private String carLoanFlag;
	/** 经销商代码 */
	private String carDealerCode;
	/** 经销商名称 */
	private String carDealerName;
	/** 折扣方式类型 */
	private String discountType;
	/** 驾驶员类型 */
	private String driverType;
	/** 目的地 */
	private String endSiteName;
	/** 起运地 */
	private String startSiteName;
	/** 版本序号 */
	private String versionNo;
	/** 唯一识别码 */
	private String carId;
	/** 备注 */
	private String remark;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 车牌号一段 */
	private String licenseNo1;
	/** 车牌号二段 */
	private String licenseNo2;
	/** 车牌号三段 */
	private String licenseno3;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpCitemCar() {
	}

	/**       
	 * 标的序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "proposalNo", column = @Column(name = "proposalno", nullable = false)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "itemno", nullable = false)) })
	public PrpCitemCarId getId() {
		return this.id;
	}

	public void setId(PrpCitemCarId id) {
		this.id = id;
	}

	/**       
	 * 投保单号码
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proposalno", nullable = false, insertable = false, updatable = false)
	public PrpCmain getPrpCmain() {
		return this.prpCmain;
	}

	public void setPrpCmain(PrpCmain prpCmain) {
		this.prpCmain = prpCmain;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 保户类别代码
	 */

	@Column(name = "insuredtypecode")
	public String getInsuredTypeCode() {
		return this.insuredTypeCode;
	}

	public void setInsuredTypeCode(String insuredTypeCode) {
		this.insuredTypeCode = insuredTypeCode;
	}

	/**       
	 * 被保险人与车辆关系
	 */

	@Column(name = "carinsuredrelation")
	public String getCarInsuredRelation() {
		return this.carInsuredRelation;
	}

	public void setCarInsuredRelation(String carInsuredRelation) {
		this.carInsuredRelation = carInsuredRelation;
	}

	/**       
	 * 条款类别（选择代码）
	 */

	@Column(name = "clausetype")
	public String getClauseType() {
		return this.clauseType;
	}

	public void setClauseType(String clauseType) {
		this.clauseType = clauseType;
	}

	/**       
	 * 是否外地车
	 */

	@Column(name = "nonlocalflag")
	public String getNonlocalFlag() {
		return this.nonlocalFlag;
	}

	public void setNonlocalFlag(String nonlocalFlag) {
		this.nonlocalFlag = nonlocalFlag;
	}

	/**       
	 * 是否已上牌照
	 */

	@Column(name = "licenseflag")
	public String getLicenseFlag() {
		return this.licenseFlag;
	}

	public void setLicenseFlag(String licenseFlag) {
		this.licenseFlag = licenseFlag;
	}

	/**       
	 * 车牌号码
	 */

	@Column(name = "licenseno")
	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	/**       
	 * 车牌种类
	 */

	@Column(name = "licensetype")
	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	/**       
	 * 车牌底色代码
	 */

	@Column(name = "licensecolorcode")
	public String getLicenseColorCode() {
		return this.licenseColorCode;
	}

	public void setLicenseColorCode(String licenseColorCode) {
		this.licenseColorCode = licenseColorCode;
	}

	/**       
	 * 车辆种类代码
	 */

	@Column(name = "carkindcode")
	public String getCarKindCode() {
		return this.carKindCode;
	}

	public void setCarKindCode(String carKindCode) {
		this.carKindCode = carKindCode;
	}

	/**       
	 * 是否港澳车标志
	 */

	@Column(name = "hkflag")
	public String getHkFlag() {
		return this.hkFlag;
	}

	public void setHkFlag(String hkFlag) {
		this.hkFlag = hkFlag;
	}

	/**       
	 * 港澳车牌号码
	 */

	@Column(name = "hklicenseno")
	public String getHkLicenseNo() {
		return this.hkLicenseNo;
	}

	public void setHkLicenseNo(String hkLicenseNo) {
		this.hkLicenseNo = hkLicenseNo;
	}

	/**       
	 * EngineNo
	 */

	@Column(name = "engineno", nullable = false)
	public String getEngineNo() {
		return this.engineNo;
	}

	public void setEngineNo(String engineNo) {
		this.engineNo = engineNo;
	}

	/**       
	 * VIN号
	 */

	@Column(name = "vinno")
	public String getVinNo() {
		return this.vinNo;
	}

	public void setVinNo(String vinNo) {
		this.vinNo = vinNo;
	}

	/**       
	 * 车架号
	 */

	@Column(name = "frameno")
	public String getFrameNo() {
		return this.frameNo;
	}

	public void setFrameNo(String frameNo) {
		this.frameNo = frameNo;
	}

	/**       
	 * 行驶区域代码
	 */

	@Column(name = "runareacode")
	public String getRunAreaCode() {
		return this.runAreaCode;
	}

	public void setRunAreaCode(String runAreaCode) {
		this.runAreaCode = runAreaCode;
	}

	/**       
	 * 行驶区域名称
	 */

	@Column(name = "runareaname")
	public String getRunAreaName() {
		return this.runAreaName;
	}

	public void setRunAreaName(String runAreaName) {
		this.runAreaName = runAreaName;
	}

	/**       
	 * 行驶里程(公里)
	 */

	@Column(name = "runmiles")
	public BigDecimal getRunMiles() {
		return this.runMiles;
	}

	public void setRunMiles(BigDecimal runMiles) {
		this.runMiles = runMiles;
	}

	/**       
	 * 初登日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "enrolldate")
	public Date getEnrollDate() {
		return this.enrollDate;
	}

	public void setEnrollDate(Date enrollDate) {
		this.enrollDate = enrollDate;
	}

	/**       
	 * 使用年限
	 */

	@Column(name = "useyears")
	public BigDecimal getUseYears() {
		return this.useYears;
	}

	public void setUseYears(BigDecimal useYears) {
		this.useYears = useYears;
	}

	/**       
	 * 车型代码
	 */

	@Column(name = "modelcode")
	public String getModelCode() {
		return this.modelCode;
	}

	public void setModelCode(String modelCode) {
		this.modelCode = modelCode;
	}

	/**       
	 * 品牌名称
	 */

	@Column(name = "brandname", nullable = false)
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**       
	 * 车型别名
	 */

	@Column(name = "aliasname")
	public String getAliasName() {
		return this.aliasName;
	}

	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	/**       
	 * 国别性质
	 */

	@Column(name = "countrynature")
	public String getCountryNature() {
		return this.countryNature;
	}

	public void setCountryNature(String countryNature) {
		this.countryNature = countryNature;
	}

	/**       
	 * 国家代码
	 */

	@Column(name = "countrycode")
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	/**       
	 * 使用性质代码
	 */

	@Column(name = "usenaturecode")
	public String getUseNatureCode() {
		return this.useNatureCode;
	}

	public void setUseNatureCode(String useNatureCode) {
		this.useNatureCode = useNatureCode;
	}

	/**       
	 * 营业性质分类代码
	 */

	@Column(name = "businessclasscode")
	public String getBusinessClassCode() {
		return this.businessClassCode;
	}

	public void setBusinessClassCode(String businessClassCode) {
		this.businessClassCode = businessClassCode;
	}

	/**       
	 * 座位数
	 */

	@Column(name = "seatcount")
	public Integer getSeatCount() {
		return this.seatCount;
	}

	public void setSeatCount(Integer seatCount) {
		this.seatCount = seatCount;
	}

	/**       
	 * 吨位数
	 */

	@Column(name = "toncount")
	public BigDecimal getTonCount() {
		return this.tonCount;
	}

	public void setTonCount(BigDecimal tonCount) {
		this.tonCount = tonCount;
	}

	/**       
	 * 排量
	 */

	@Column(name = "exhaustscale")
	public BigDecimal getExhaustScale() {
		return this.exhaustScale;
	}

	public void setExhaustScale(BigDecimal exhaustScale) {
		this.exhaustScale = exhaustScale;
	}

	/**       
	 * 整备质量
	 */

	@Column(name = "carloteququality")
	public BigDecimal getCarLotEquQuality() {
		return this.carLotEquQuality;
	}

	public void setCarLotEquQuality(BigDecimal carLotEquQuality) {
		this.carLotEquQuality = carLotEquQuality;
	}

	/**       
	 * 车身颜色代码
	 */

	@Column(name = "colorcode")
	public String getColorCode() {
		return this.colorCode;
	}

	public void setColorCode(String colorCode) {
		this.colorCode = colorCode;
	}

	/**       
	 * 安全配置
	 */

	@Column(name = "safedevice")
	public String getSafeDevice() {
		return this.safeDevice;
	}

	public void setSafeDevice(String safeDevice) {
		this.safeDevice = safeDevice;
	}

	/**       
	 * 车损车型系数
	 */

	@Column(name = "coefficient1")
	public BigDecimal getCoefficient1() {
		return this.coefficient1;
	}

	public void setCoefficient1(BigDecimal coefficient1) {
		this.coefficient1 = coefficient1;
	}

	/**       
	 * 盗抢车型系数
	 */

	@Column(name = "coefficient2")
	public BigDecimal getCoefficient2() {
		return this.coefficient2;
	}

	public void setCoefficient2(BigDecimal coefficient2) {
		this.coefficient2 = coefficient2;
	}

	/**       
	 * 其他车型系数
	 */

	@Column(name = "coefficient3")
	public BigDecimal getCoefficient3() {
		return this.coefficient3;
	}

	public void setCoefficient3(BigDecimal coefficient3) {
		this.coefficient3 = coefficient3;
	}

	/**       
	 * 其他性质
	 */

	@Column(name = "othernature")
	public String getOtherNature() {
		return this.otherNature;
	}

	public void setOtherNature(String otherNature) {
		this.otherNature = otherNature;
	}

	/**       
	 * 费率号次
	 */

	@Column(name = "ratecode")
	public String getRateCode() {
		return this.rateCode;
	}

	public void setRateCode(String rateCode) {
		this.rateCode = rateCode;
	}

	/**       
	 * 生产日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "makedate")
	public Date getMakeDate() {
		return this.makeDate;
	}

	public void setMakeDate(Date makeDate) {
		this.makeDate = makeDate;
	}

	/**       
	 * 购车用途
	 */

	@Column(name = "carusage")
	public String getCarUsage() {
		return this.carUsage;
	}

	public void setCarUsage(String carUsage) {
		this.carUsage = carUsage;
	}

	/**       
	 * 币别
	 */

	@Column(name = "currency")
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/**       
	 * 新件购置价
	 */

	@Column(name = "purchaseprice")
	public BigDecimal getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(BigDecimal purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	/**       
	 * 实际价值
	 */

	@Column(name = "actualvalue")
	public BigDecimal getActualValue() {
		return this.actualValue;
	}

	public void setActualValue(BigDecimal actualValue) {
		this.actualValue = actualValue;
	}

	/**       
	 * 发票号
	 */

	@Column(name = "invoiceno")
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	/**       
	 * 是否在我公司投保信用或保证
	 */

	@Column(name = "carloanflag")
	public String getCarLoanFlag() {
		return this.carLoanFlag;
	}

	public void setCarLoanFlag(String carLoanFlag) {
		this.carLoanFlag = carLoanFlag;
	}

	/**       
	 * 经销商代码
	 */

	@Column(name = "cardealercode")
	public String getCarDealerCode() {
		return this.carDealerCode;
	}

	public void setCarDealerCode(String carDealerCode) {
		this.carDealerCode = carDealerCode;
	}

	/**       
	 * 经销商名称
	 */

	@Column(name = "cardealername")
	public String getCarDealerName() {
		return this.carDealerName;
	}

	public void setCarDealerName(String carDealerName) {
		this.carDealerName = carDealerName;
	}

	/**       
	 * 折扣方式类型
	 */

	@Column(name = "discounttype")
	public String getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(String discountType) {
		this.discountType = discountType;
	}

	/**       
	 * 驾驶员类型
	 */

	@Column(name = "drivertype")
	public String getDriverType() {
		return this.driverType;
	}

	public void setDriverType(String driverType) {
		this.driverType = driverType;
	}

	/**       
	 * 目的地
	 */

	@Column(name = "endsitename")
	public String getEndSiteName() {
		return this.endSiteName;
	}

	public void setEndSiteName(String endSiteName) {
		this.endSiteName = endSiteName;
	}

	/**       
	 * 起运地
	 */

	@Column(name = "startsitename")
	public String getStartSiteName() {
		return this.startSiteName;
	}

	public void setStartSiteName(String startSiteName) {
		this.startSiteName = startSiteName;
	}

	/**       
	 * 版本序号
	 */

	@Column(name = "versionno")
	public String getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(String versionNo) {
		this.versionNo = versionNo;
	}

	/**       
	 * 唯一识别码
	 */

	@Column(name = "carid")
	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 车牌号一段
	 */

	@Column(name = "licenseno1")
	public String getLicenseNo1() {
		return this.licenseNo1;
	}

	public void setLicenseNo1(String licenseNo1) {
		this.licenseNo1 = licenseNo1;
	}

	/**       
	 * 车牌号二段
	 */

	@Column(name = "licenseno2")
	public String getLicenseNo2() {
		return this.licenseNo2;
	}

	public void setLicenseNo2(String licenseNo2) {
		this.licenseNo2 = licenseNo2;
	}

	/**       
	 * 车牌号三段
	 */

	@Column(name = "licenseno3")
	public String getLicenseno3() {
		return this.licenseno3;
	}

	public void setLicenseno3(String licenseno3) {
		this.licenseno3 = licenseno3;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

}
