package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpCmainSubId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCmainSubId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String proposalNo;
	private String mainPolicyNo;

	public PrpCmainSubId() {
	}

	@Column(name = "proposalno", nullable = false)
	public String getProposalNo() {
		return this.proposalNo;
	}

	public void setProposalNo(String proposalNo) {
		this.proposalNo = proposalNo;
	}

	@Column(name = "mainpolicyno", nullable = false)
	public String getMainPolicyNo() {
		return this.mainPolicyNo;
	}

	public void setMainPolicyNo(String mainPolicyNo) {
		this.mainPolicyNo = mainPolicyNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpCmainSubId))
			return false;
		PrpCmainSubId castOther = (PrpCmainSubId) other;

		return ((this.getProposalNo() == castOther.getProposalNo()) || (this
				.getProposalNo() != null
				&& castOther.getProposalNo() != null && this.getProposalNo()
				.equals(castOther.getProposalNo())))
				&& ((this.getMainPolicyNo() == castOther.getMainPolicyNo()) || (this
						.getMainPolicyNo() != null
						&& castOther.getMainPolicyNo() != null && this
						.getMainPolicyNo().equals(castOther.getMainPolicyNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProposalNo() == null ? 0 : this.getProposalNo()
						.hashCode());
		result = 37
				* result
				+ (getMainPolicyNo() == null ? 0 : this.getMainPolicyNo()
						.hashCode());
		return result;
	}

}
