package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpCspecialFacId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCspecialFacId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String proposalNo;
	private Integer reinsNo;

	public PrpCspecialFacId() {
	}

	@Column(name = "proposalno", nullable = false)
	public String getProposalNo() {
		return this.proposalNo;
	}

	public void setProposalNo(String proposalNo) {
		this.proposalNo = proposalNo;
	}

	@Column(name = "reinsno", nullable = false)
	public Integer getReinsNo() {
		return this.reinsNo;
	}

	public void setReinsNo(Integer reinsNo) {
		this.reinsNo = reinsNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpCspecialFacId))
			return false;
		PrpCspecialFacId castOther = (PrpCspecialFacId) other;

		return ((this.getProposalNo() == castOther.getProposalNo()) || (this
				.getProposalNo() != null
				&& castOther.getProposalNo() != null && this.getProposalNo()
				.equals(castOther.getProposalNo())))
				&& ((this.getReinsNo() == castOther.getReinsNo()) || (this
						.getReinsNo() != null
						&& castOther.getReinsNo() != null && this.getReinsNo()
						.equals(castOther.getReinsNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProposalNo() == null ? 0 : this.getProposalNo()
						.hashCode());
		result = 37 * result
				+ (getReinsNo() == null ? 0 : this.getReinsNo().hashCode());
		return result;
	}

}
