package com.sinosoft.fccb.policy.common.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrpCcoins generated by Tools.Don't edit.
 */
@Entity
@Table(name = "PRPCCOINS")
public class PrpCcoins implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 主键 */
	private PrpCcoinsId id;

	/** 主表 */
	private PrpCmain prpCmain;

	/** 主保单号 */
	private String mainPolicyNo;
	
	/**共保身份 */
	private String coIdentity;

	/** 共保人机构代码 */
	private String coinsCode;

	/** 共保人名称 */
	private String coinsName;

	/** 共保类型 */
	private String coinsType;

	/** 共保份额 */
	private BigDecimal coinsRate;

	/** 分额保额 */
	private BigDecimal coinsAmount;

	/** 分额保费 */
	private BigDecimal coinsPremium;
	
	/** 插入时间 */
	private Date insertTimeForHis;

	/** 修改时间 */
	private Date operateTimeForHis;
	
	/**	共保方案代码 */
	private String coinsSchemeCode;
	
	/**	共保方案名称 */
	private String coinsSchemeName;

	/** 标志字段 */
	private String flag;
	
	//RZHANGT2013032801_01 联保方案改造，新增字段 add by zhoujin 20130809 begin
	/**主投保单号码*/
	private String mainProposalNo;
   
	/**从联方投保单号码*/
	private String subProposalNo;
	
	/**支付手续费方式  [1]是否代从联方支手续费 [2]是否代共保方收支保费 [3]是否代共保方支手续费 [4]是否代开他方发票*/
	private String payType;
	
	/**归属业务员*/
	private String handler1Code;	
	
	/**归属业务员统一工号*/
	private String handler1Code_uni;
	
	/**经办人*/
	private String handlerCode;
	
	/**经办人统一工号*/
	private String handlerCode_uni;
	
	/**操作员代码*/
	private String operatorCode;
	
	/**业务性质*/
	private String businessNature;
	
	/**渠道码*/
	private String agentCode;
	
	/**银行代码*/
	private String basicBankCode;
	
	/**银行名称*/
	private String basicBankName;
	
	/**银行区域代码*/
	private String recBankAreaCode;
	
	/**银行区域名称*/
	private String recBankAreaName;
	
	/**开户行代码*/
	private String bankCode;
	
	/**开户行名称*/
	private String bankName;
   
	/**银行帐号*/
	private String accountNo;
	
	/**银行帐号名称*/
	private String accountName;
	
	/**联行号*/
	private String cnaps;	
	
	/**证件类型*/
	private String identifyType;
	
	/**证件号码*/
	private String identifyNo;
	
	/**电话*/
	private String telephone;
	
	/**公私标志*/
	private String isPrivate;
	
	/**用途*/
	private String purpose;
	
	/**卡折标志*/
	private String cardType;
	
	/**是否发送短信*/
	private String sendSms;
	
	/**是否发送邮件*/
	private String sendMail;	
	
	/**支付ID*/
	private String payeeInfoid;
	
	/**邮箱地址*/
	private String mailAddr;
	
	/**支付方式*/
	private String paymodeflag;
	
	/**联保方类型*/
	private String comType;
	//RZHANGT2013032801_01 联保方案改造，新增字段 add by zhoujin 20130809 end
	
	//ZIS从联自动流程 add by zhangpengfei
	/**资源分配码*/
	private String resourceCode;
	
	/**联共保特殊标志*/
	private String coinsExtraFlag;
	
	
	
	public PrpCcoins() {
	}

	/**       
	 * 主键
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "proposalNo", column = @Column(name = "PROPOSALNO")),
			@AttributeOverride(name = "serialNo", column = @Column(name = "SERIALNO")),
			@AttributeOverride(name = "currency", column = @Column(name = "CURRENCY")) })
	public PrpCcoinsId getId() {
		return this.id;
	}

	public void setId(PrpCcoinsId id) {
		this.id = id;
	}

	/**       
	 * 主表
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROPOSALNO", nullable = false, insertable = false, updatable = false)
	public PrpCmain getPrpCmain() {
		return this.prpCmain;
	}

	public void setPrpCmain(PrpCmain prpCmain) {
		this.prpCmain = prpCmain;
	}

	/**       
	 * 主保单号
	 */

	@Column(name = "MAINPOLICYNO")
	public String getMainPolicyNo() {
		return this.mainPolicyNo;
	}

	public void setMainPolicyNo(String mainPolicyNo) {
		this.mainPolicyNo = mainPolicyNo;
	}

	/**       
	 * 共保身份
	 */

	@Column(name = "COIDENTITY")
	public String getCoIdentity() {
		return coIdentity;
	}

	public void setCoIdentity(String coIdentity) {
		this.coIdentity = coIdentity;
	}

	
	/**       
	 * 共保人机构代码
	 */

	@Column(name = "COINSCODE")
	public String getCoinsCode() {
		return this.coinsCode;
	}

	public void setCoinsCode(String coinsCode) {
		this.coinsCode = coinsCode;
	}

	/**       
	 * 共保人名称
	 */

	@Column(name = "COINSNAME")
	public String getCoinsName() {
		return this.coinsName;
	}

	public void setCoinsName(String coinsName) {
		this.coinsName = coinsName;
	}

	/**       
	 * 共保类型
	 */

	@Column(name = "COINSTYPE")
	public String getCoinsType() {
		return this.coinsType;
	}

	public void setCoinsType(String coinsType) {
		this.coinsType = coinsType;
	}

	/**       
	 * 共保份额
	 */

	@Column(name = "COINSRATE")
	public BigDecimal getCoinsRate() {
		return this.coinsRate;
	}

	public void setCoinsRate(BigDecimal coinsRate) {
		this.coinsRate = coinsRate;
	}

	/**       
	 * 分额保额
	 */

	@Column(name = "COINSAMOUNT")
	public BigDecimal getCoinsAmount() {
		return this.coinsAmount;
	}

	public void setCoinsAmount(BigDecimal coinsAmount) {
		this.coinsAmount = coinsAmount;
	}

	/**       
	 * 分额保费
	 */

	@Column(name = "COINSPREMIUM")
	public BigDecimal getCoinsPremium() {
		return this.coinsPremium;
	}

	public void setCoinsPremium(BigDecimal coinsPremium) {
		this.coinsPremium = coinsPremium;
	}
	/**       
	 * 插入时间
	 */
    @Column(name = "insertTimeForHis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
	    return insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
	    this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 修改时间
	 */
    @Column(name = "operateTimeForHis", insertable = false)
	public Date getOperateTimeForHis() {
	    return operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
	    this.operateTimeForHis = operateTimeForHis;
	}
	
	/**       
	 * 共保方案代码
	 */
	@Column(name = "COINSSCHEMECODE")
	public String getCoinsSchemeCode() {
		return coinsSchemeCode;
	}

	public void setCoinsSchemeCode(String coinsSchemeCode) {
		this.coinsSchemeCode = coinsSchemeCode;
	}
	
	/**       
	 * 共保方案名称
	 */
	@Column(name = "COINSSCHEMENAME")
	public String getCoinsSchemeName() {
		return coinsSchemeName;
	}

	public void setCoinsSchemeName(String coinsSchemeName) {
		this.coinsSchemeName = coinsSchemeName;
	}
	
	/**       
	 * 标志字段
	 */

	@Column(name = "FLAG")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getMainProposalNo() {
		return mainProposalNo;
	}

	public void setMainProposalNo(String mainProposalNo) {
		this.mainProposalNo = mainProposalNo;
	}

	public String getSubProposalNo() {
		return subProposalNo;
	}

	public void setSubProposalNo(String subProposalNo) {
		this.subProposalNo = subProposalNo;
	}

	public String getPayType() {
		return payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public String getHandler1Code() {
		return handler1Code;
	}

	public void setHandler1Code(String handler1Code) {
		this.handler1Code = handler1Code;
	}

	public String getHandlerCode() {
		return handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	public String getOperatorCode() {
		return operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	public String getBusinessNature() {
		return businessNature;
	}

	public void setBusinessNature(String businessNature) {
		this.businessNature = businessNature;
	}

	public String getAgentCode() {
		return agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public String getBasicBankCode() {
		return basicBankCode;
	}

	public void setBasicBankCode(String basicBankCode) {
		this.basicBankCode = basicBankCode;
	}

	public String getBasicBankName() {
		return basicBankName;
	}

	public void setBasicBankName(String basicBankName) {
		this.basicBankName = basicBankName;
	}

	public String getRecBankAreaCode() {
		return recBankAreaCode;
	}

	public void setRecBankAreaCode(String recBankAreaCode) {
		this.recBankAreaCode = recBankAreaCode;
	}

	public String getRecBankAreaName() {
		return recBankAreaName;
	}

	public void setRecBankAreaName(String recBankAreaName) {
		this.recBankAreaName = recBankAreaName;
	}

	public String getBankCode() {
		return bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getAccountNo() {
		return accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public String getCnaps() {
		return cnaps;
	}

	public void setCnaps(String cnaps) {
		this.cnaps = cnaps;
	}

	public String getIdentifyType() {
		return identifyType;
	}

	public void setIdentifyType(String identifyType) {
		this.identifyType = identifyType;
	}

	public String getIdentifyNo() {
		return identifyNo;
	}

	public void setIdentifyNo(String identifyNo) {
		this.identifyNo = identifyNo;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getIsPrivate() {
		return isPrivate;
	}

	public void setIsPrivate(String isPrivate) {
		this.isPrivate = isPrivate;
	}

	public String getPurpose() {
		return purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getCardType() {
		return cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getSendSms() {
		return sendSms;
	}

	public void setSendSms(String sendSms) {
		this.sendSms = sendSms;
	}

	public String getSendMail() {
		return sendMail;
	}

	public void setSendMail(String sendMail) {
		this.sendMail = sendMail;
	}

	public String getPayeeInfoid() {
		return payeeInfoid;
	}

	public void setPayeeInfoid(String payeeInfoid) {
		this.payeeInfoid = payeeInfoid;
	}

	public String getMailAddr() {
		return mailAddr;
	}

	public void setMailAddr(String mailAddr) {
		this.mailAddr = mailAddr;
	}

	public String getPaymodeflag() {
		return paymodeflag;
	}

	public void setPaymodeflag(String paymodeflag) {
		this.paymodeflag = paymodeflag;
	}

	public String getComType() {
		return comType;
	}

	public void setComType(String comType) {
		this.comType = comType;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getCoinsExtraFlag() {
		return coinsExtraFlag;
	}

	public void setCoinsExtraFlag(String coinsExtraFlag) {
		this.coinsExtraFlag = coinsExtraFlag;
	}

	public String getResourceCode() {
		return resourceCode;
	}

	public void setResourceCode(String resourceCode) {
		this.resourceCode = resourceCode;
	}

	
	@Column(name = "handler1code_uni")
	public String getHandler1Code_uni() {
		return handler1Code_uni;
	}

	public void setHandler1Code_uni(String handler1CodeUni) {
		handler1Code_uni = handler1CodeUni;
	}

	@Column(name = "handlercode_uni")
	public String getHandlerCode_uni() {
		return handlerCode_uni;
	}

	public void setHandlerCode_uni(String handlerCodeUni) {
		handlerCode_uni = handlerCodeUni;
	}
	/**
	 * @function 
	 * @author 黄娜
	 * @日期：2015-10-28
	 * @param source
	 * @param index
	 * @return void
	 */
	//201504091-002 从联录单允许加入多个从联方 add by huangna 201511-16 begin
	public void ssetCoinsExtraFlagByIndex(char source,int index) {
		if(null==coinsExtraFlag){
			StringBuffer sb=new StringBuffer();
			for(int i=0;i<index;i++){
				sb.append(' ');
			}
			sb.append(source);
			this.coinsExtraFlag = sb.toString();
		}else{
			StringBuffer sb=new StringBuffer(coinsExtraFlag);
			int length=coinsExtraFlag.length();
			if((length-1)>=index){
				StringBuilder sbb=new StringBuilder(String.valueOf(source));
				sb.replace(index, index+1, sbb.toString());
			}else{
				for(int i=0;i<index-length;i++){
					sb.append(' ');
				}
				sb.append(source);
			}
			this.coinsExtraFlag = sb.toString();
		}
	}
	/**
	 * @function 
	 * @author 黄娜
	 * @日期：2015-10-28
	 * @param index
	 * @return String
	 */
	public String ggetCoinsExtraFlagByIndex(int index) {
		if((coinsExtraFlag.length()-1)>=index){
			return coinsExtraFlag.substring(index, index+1);
		}else{
			return null;
		}
	}

}
//201504091-002 从联录单允许加入多个从联方 add by huangna 201511-16 end
