package com.sinosoft.fccb.policy.common.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpCclauseConfineId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCclauseConfineId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String proposalNo;
	private Integer clauseno;

	public PrpCclauseConfineId() {
	}

	@Column(name = "proposalno")
	public String getProposalNo() {
		return this.proposalNo;
	}

	public void setProposalNo(String proposalNo) {
		this.proposalNo = proposalNo;
	}

	@Column(name = "clauseno")
	public Integer getClauseno() {
		return this.clauseno;
	}

	public void setClauseno(Integer clauseno) {
		this.clauseno = clauseno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpCclauseConfineId))
			return false;
		PrpCclauseConfineId castOther = (PrpCclauseConfineId) other;

		return ((this.getProposalNo() == castOther.getProposalNo()) || (this
				.getProposalNo() != null
				&& castOther.getProposalNo() != null && this.getProposalNo()
				.equals(castOther.getProposalNo())))
				&& ((this.getClauseno() == castOther.getClauseno()) || (this
						.getClauseno() != null
						&& castOther.getClauseno() != null && this
						.getClauseno().equals(castOther.getClauseno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProposalNo() == null ? 0 : this.getProposalNo()
						.hashCode());
		result = 37 * result
				+ (getClauseno() == null ? 0 : this.getClauseno().hashCode());
		return result;
	}

}
