package com.sinosoft.fccb.policy.common.model;

//Generated 2010-4-21 18:20:11 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * PrpCitemKindDetail generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcitemkinddetail")
public class PrpCitemKindDetail implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	/** 序号 */
	private PrpCitemKindDetailId id;
	/** 保险责任序号 */
	private PrpCitemKind prpCitemKind;
	/** 产品代码 */
	private String riskCode;
	/** 对应类型 */
	private Integer itemKindNo;
	/** 层赔偿限额 */
	private BigDecimal layerAmount;
	/** 层起赔点 */
	private BigDecimal layerStartAmount;
	/** 层费率 */
	private BigDecimal layerRate;
	/** 层保费 */
	private BigDecimal layerpremium;
	/** 参与份额 */
	private BigDecimal layerCoinsRate;
	/** 份额内保费*/
	private BigDecimal premium;
	/** 标志字段 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;
	
	public PrpCitemKindDetail() {
		
	}
	
	/**       
	 * 序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "proposalNo", column = @Column(name = "proposalno", nullable = false)),
			@AttributeOverride(name = "serialNo", column = @Column(name = "serialno", nullable = false)) })
	public PrpCitemKindDetailId getId() {
		return this.id;
	}

	public void setId(PrpCitemKindDetailId id) {
		this.id = id;
	}

	/**       
	 * 保险责任序号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "proposalno", referencedColumnName="proposalno", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "itemkindno", referencedColumnName="itemkindno", nullable = false, insertable = false, updatable = false) })
	public PrpCitemKind getPrpCitemKind() {
		return prpCitemKind;
	}

	public void setPrpCitemKind(PrpCitemKind prpCitemKind) {
		this.prpCitemKind = prpCitemKind;
	}

	
	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}
	
	/**       
	 * 对应类型
	 */

	@Column(name = "itemkindno")
	public Integer getItemKindNo() {
		return itemKindNo;
	}

	public void setItemKindNo(Integer itemKindNo) {
		this.itemKindNo = itemKindNo;
	}
	
	/**       
	 * 层赔偿限额
	 */

	@Column(name = "layeramount")
	public BigDecimal getLayerAmount() {
		return layerAmount;
	}

	public void setLayerAmount(BigDecimal layerAmount) {
		this.layerAmount = layerAmount;
	}
    
	/**       
	 * 层起赔点
	 */

	@Column(name = "layerstartamount")
	public BigDecimal getLayerStartAmount() {
		return layerStartAmount;
	}

	public void setLayerStartAmount(BigDecimal layerStartAmount) {
		this.layerStartAmount = layerStartAmount;
	}
	
	/**       
	 * 层费率
	 */

	@Column(name = "layerrate")
	public BigDecimal getLayerRate() {
		return layerRate;
	}

	public void setLayerRate(BigDecimal layerRate) {
		this.layerRate = layerRate;
	}
	
	/**       
	 * 层保费
	 */

	@Column(name = "layerpremium")
	public BigDecimal getLayerpremium() {
		return layerpremium;
	}

	public void setLayerpremium(BigDecimal layerpremium) {
		this.layerpremium = layerpremium;
	}
    
	/**       
	 * 参与份额
	 */

	@Column(name = "layercoinsrate")
	public BigDecimal getLayerCoinsRate() {
		return layerCoinsRate;
	}

	public void setLayerCoinsRate(BigDecimal layerCoinsRate) {
		this.layerCoinsRate = layerCoinsRate;
	}
    
	/**       
	 * 份额内保费
	 */

	@Column(name = "premium")
	public BigDecimal getPremium() {
		return premium;
	}

	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}
    
	/**       
	 * 标志字段
	 */

	@Column(name = "flag")
	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
    
	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis")
	public Date getInsertTimeForHis() {
		return insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}
    
	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis")
	public Date getOperateTimeForHis() {
		return operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
}
