package com.sinosoft.fccb.policy.common.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpCopyShipDriver generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcopyshipdriver")
public class PrpCopyShipDriver implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** SerialNo */
	private PrpCopyShipDriverId id;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 标的序号 */
	private Integer itemNo;
	/** 驾驶员姓名 */
	private String driverName;
	/** 驾驶员性别 */
	private String driverSex;
	/** 驾驶员类型 */
	private String driverTypeCode;
	/** 出生日期 */
	private Date birthday;
	/** 驾驶员等级 */
	private String driverGrade;
	/** 驾驶员航线 */
	private String driverSeaRoute;
	/** 驾驶证号码 */
	private String drivingLicenseNo;
	/** 领证时间 */
	private Date receiveLicenseDate;
	/** 准驾船型 */
	private String drivingShipType;
	/** 驾驶年限 */
	private Integer drivingYear;
	/** 是否固定驾驶员标志 */
	private String changelessFlag;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;
	/** 批单申请号 */
	private PrpCopyMain prpCopyMain;

	public PrpCopyShipDriver() {
	}

	/**       
	 * SerialNo
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno")),
			@AttributeOverride(name = "serialNo", column = @Column(name = "serialno")) })
	public PrpCopyShipDriverId getId() {
		return this.id;
	}

	public void setId(PrpCopyShipDriverId id) {
		this.id = id;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno")
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode")
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 标的序号
	 */

	@Column(name = "itemno")
	public Integer getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(Integer itemNo) {
		this.itemNo = itemNo;
	}

	/**       
	 * 驾驶员姓名
	 */

	@Column(name = "drivername")
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	/**       
	 * 驾驶员性别
	 */

	@Column(name = "driversex")
	public String getDriverSex() {
		return this.driverSex;
	}

	public void setDriverSex(String driverSex) {
		this.driverSex = driverSex;
	}

	/**       
	 * 驾驶员类型
	 */

	@Column(name = "drivertypecode")
	public String getDriverTypeCode() {
		return this.driverTypeCode;
	}

	public void setDriverTypeCode(String driverTypeCode) {
		this.driverTypeCode = driverTypeCode;
	}

	/**       
	 * 出生日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "birthday")
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**       
	 * 驾驶员等级
	 */

	@Column(name = "drivergrade")
	public String getDriverGrade() {
		return this.driverGrade;
	}

	public void setDriverGrade(String driverGrade) {
		this.driverGrade = driverGrade;
	}

	/**       
	 * 驾驶员航线
	 */

	@Column(name = "driversearoute")
	public String getDriverSeaRoute() {
		return this.driverSeaRoute;
	}

	public void setDriverSeaRoute(String driverSeaRoute) {
		this.driverSeaRoute = driverSeaRoute;
	}

	/**       
	 * 驾驶证号码
	 */

	@Column(name = "drivinglicenseno")
	public String getDrivingLicenseNo() {
		return this.drivingLicenseNo;
	}

	public void setDrivingLicenseNo(String drivingLicenseNo) {
		this.drivingLicenseNo = drivingLicenseNo;
	}

	/**       
	 * 领证时间
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "receivelicensedate")
	public Date getReceiveLicenseDate() {
		return this.receiveLicenseDate;
	}

	public void setReceiveLicenseDate(Date receiveLicenseDate) {
		this.receiveLicenseDate = receiveLicenseDate;
	}

	/**       
	 * 准驾船型
	 */

	@Column(name = "drivingshiptype")
	public String getDrivingShipType() {
		return this.drivingShipType;
	}

	public void setDrivingShipType(String drivingShipType) {
		this.drivingShipType = drivingShipType;
	}

	/**       
	 * 驾驶年限
	 */

	@Column(name = "drivingyear")
	public Integer getDrivingYear() {
		return this.drivingYear;
	}

	public void setDrivingYear(Integer drivingYear) {
		this.drivingYear = drivingYear;
	}

	/**       
	 * 是否固定驾驶员标志
	 */

	@Column(name = "changelessflag")
	public String getChangelessFlag() {
		return this.changelessFlag;
	}

	public void setChangelessFlag(String changelessFlag) {
		this.changelessFlag = changelessFlag;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", unique = true, nullable = false, insertable = false, updatable = false)
	public PrpCopyMain getPrpCopyMain() {
		return this.prpCopyMain;
	}

	public void setPrpCopyMain(PrpCopyMain prpCopyMain) {
		this.prpCopyMain = prpCopyMain;
	}
}
