package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpCitemKindEACId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCitemKindEACId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String quoteNo;
	private Integer orderNum;

	public PrpCitemKindEACId() {
	}

	@Column(name = "quoteno", nullable = false)
	public String getQuoteNo() {
		return quoteNo;
	}

	public void setQuoteNo(String quoteNo) {
		this.quoteNo = quoteNo;
	}

	@Column(name = "ordernum", nullable = false)
	public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpCitemKindEACId))
			return false;
		PrpCitemKindEACId castOther = (PrpCitemKindEACId) other;

		return ((this.getQuoteNo() == castOther.getQuoteNo()) || (this
				.getQuoteNo() != null
				&& castOther.getQuoteNo() != null && this.getQuoteNo()
				.equals(castOther.getQuoteNo())))
				&& ((this.getOrderNum() == castOther.getOrderNum()) || (this
						.getOrderNum() != null
						&& castOther.getOrderNum() != null && this
						.getOrderNum().equals(castOther.getOrderNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getQuoteNo() == null ? 0 : this.getQuoteNo()
						.hashCode());
		result = 37
				* result
				+ (getOrderNum() == null ? 0 : this.getOrderNum()
						.hashCode());
		return result;
	}



}
