package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrpCopyMainSub generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcopymainsub")
public class PrpCopyMainSub implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 主保单号码 */
	private PrpCopyMainSubId id;
	/** 批单申请号 */
	private PrpCopyMain prpCopyMain;
	/** 主投保单号码 */
	private String mainProposalNo;
	/** 保单号 */
	private String policyNo;
	/** 批单号 */
	private String endorseNo;
	/** 发货登记序号 */
	private String cargoSerialNo;
	/** 第几次协议结算（YAE） */
	private Integer balanceTimes;
	/** 参与协议结算标志 */
	private String balanceFlag;
	/** 单独收费标志 */
	private String payFlag;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpCopyMainSub() {
	}

	/**       
	 * 主保单号码
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "mainPolicyNo", column = @Column(name = "mainpolicyno", nullable = false)) })
	public PrpCopyMainSubId getId() {
		return this.id;
	}

	public void setId(PrpCopyMainSubId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpCopyMain getPrpCopyMain() {
		return this.prpCopyMain;
	}

	public void setPrpCopyMain(PrpCopyMain prpCopyMain) {
		this.prpCopyMain = prpCopyMain;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 第几次协议结算（YAE）
	 */

	@Column(name = "balancetimes")
	public Integer getBalanceTimes() {
		return this.balanceTimes;
	}

	public void setBalanceTimes(Integer balanceTimes) {
		this.balanceTimes = balanceTimes;
	}

	/**       
	 * 参与协议结算标志
	 */

	@Column(name = "balanceflag")
	public String getBalanceFlag() {
		return this.balanceFlag;
	}

	public void setBalanceFlag(String balanceFlag) {
		this.balanceFlag = balanceFlag;
	}

	/**       
	 * 单独收费标志
	 */

	@Column(name = "payflag")
	public String getPayFlag() {
		return this.payFlag;
	}

	public void setPayFlag(String payFlag) {
		this.payFlag = payFlag;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	/**       
	 * 主投保单号码
	 */

	@Column(name = "mainproposalno")
	public String getMainProposalNo() {
		return mainProposalNo;
	}

	public void setMainProposalNo(String mainProposalNo) {
		this.mainProposalNo = mainProposalNo;
	}

	/**       
	 * 发货登记序号
	 */

	@Column(name = "cargoserialno")
	public String getCargoSerialNo() {
		return cargoSerialNo;
	}

	public void setCargoSerialNo(String cargoSerialNo) {
		this.cargoSerialNo = cargoSerialNo;
	}

}
