package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpCopyEngageId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpCopyClauseContentId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String applyNo;
	private String clauseCode;

	public PrpCopyClauseContentId() {
	}

	@Column(name = "applyno", nullable = false)
	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	@Column(name = "clauseCode", nullable = false)
	public String getClauseCode() {
		return this.clauseCode;
	}

	public void setClauseCode(String clauseCode) {
		this.clauseCode = clauseCode;
	}

}
