package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpPitemPropId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpPitemPropId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String endorseNo;
	private Integer itemNo;

	public PrpPitemPropId() {
	}

	@Column(name = "endorseno", nullable = false)
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	@Column(name = "itemno", nullable = false)
	public Integer getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(Integer itemNo) {
		this.itemNo = itemNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpPitemPropId))
			return false;
		PrpPitemPropId castOther = (PrpPitemPropId) other;

		return ((this.getEndorseNo() == castOther.getEndorseNo()) || (this
				.getEndorseNo() != null
				&& castOther.getEndorseNo() != null && this.getEndorseNo()
				.equals(castOther.getEndorseNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null
						&& castOther.getItemNo() != null && this.getItemNo()
						.equals(castOther.getItemNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEndorseNo() == null ? 0 : this.getEndorseNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		return result;
	}

}
