package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrpPlimit generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpplimit")
public class PrpPlimit implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 币别 */
	private PrpPlimitId id;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 赔偿限额/免赔额 */
	private BigDecimal limitFee;
	/** 是否计算保额标志 */
	private String calculateFlag;
	/** 免赔标志 */
	private String limitFlag;
	/** 是否是必录项标识 */
	private String isRecorded;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpPlimit() {
	}

	/**       
	 * 币别
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "limitGrade", column = @Column(name = "limitgrade", nullable = false)),
			@AttributeOverride(name = "limitNo", column = @Column(name = "limitno", nullable = false)),
			@AttributeOverride(name = "limitType", column = @Column(name = "limittype", nullable = false)),
			@AttributeOverride(name = "currency", column = @Column(name = "currency", nullable = false)) })
	public PrpPlimitId getId() {
		return this.id;
	}

	public void setId(PrpPlimitId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 赔偿限额/免赔额
	 */

	@Column(name = "limitfee")
	public BigDecimal getLimitFee() {
		return this.limitFee;
	}

	public void setLimitFee(BigDecimal limitFee) {
		this.limitFee = limitFee;
	}

	/**       
	 * 是否计算保额标志
	 */

	@Column(name = "calculateflag")
	public String getCalculateFlag() {
		return this.calculateFlag;
	}

	public void setCalculateFlag(String calculateFlag) {
		this.calculateFlag = calculateFlag;
	}

	/**       
	 * 免赔标志
	 */

	@Column(name = "limitflag")
	public String getLimitFlag() {
		return this.limitFlag;
	}

	public void setLimitFlag(String limitFlag) {
		this.limitFlag = limitFlag;
	}

	/**       
	 * 承保是否必输
	 */

	@Column(name = "isrecorded")
	public String getIsRecorded() {
		return this.isRecorded;
	}

	public void setIsRecorded(String isRecorded) {
		this.isRecorded = isRecorded;
	}
	
	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

}
