package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpPprojectId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpPprojectId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String applyNo;
	private Integer projectNo;

	public PrpPprojectId() {
	}

	@Column(name = "applyno", nullable = false)
	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	@Column(name = "projectno", nullable = false)
	public Integer getProjectNo() {
		return this.projectNo;
	}

	public void setProjectNo(Integer projectNo) {
		this.projectNo = projectNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpPprojectId))
			return false;
		PrpPprojectId castOther = (PrpPprojectId) other;

		return ((this.getApplyNo() == castOther.getApplyNo()) || (this
				.getApplyNo() != null
				&& castOther.getApplyNo() != null && this.getApplyNo().equals(
				castOther.getApplyNo())))
				&& ((this.getProjectNo() == castOther.getProjectNo()) || (this
						.getProjectNo() != null
						&& castOther.getProjectNo() != null && this
						.getProjectNo().equals(castOther.getProjectNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getApplyNo() == null ? 0 : this.getApplyNo().hashCode());
		result = 37 * result
				+ (getProjectNo() == null ? 0 : this.getProjectNo().hashCode());
		return result;
	}

}
