package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpPmainAgri generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppmain_agri")
public class PrpPmainAgri implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 批单申请号 */
	private String applyNo;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 种植/养殖时间 */
	private Date raiseDate;
	/** 种植地点/养殖地点/坐落地点 */
	private String raiseSite;
	/** 地理信息 */
	private String raiseCoordinates;
	/** 村域种植规模(亩) */
	private String raiseArea;
	/** 东经起始 */
	private String longitudeStart;
	/** 东经终止 */
	private String longitudeEnd;
	/** 北纬起始 */
	private String latitudeStart;
	/** 北纬终止 */
	private String latitudeEnd;
	/** 总投保面积(种植险) */
	private BigDecimal insureArea;
	/** 养殖方式(养殖险) */
	private String farmingMethod;
	/** 业务类型 */
	private String businessType;
	/** 经营模式 */
	private String businessModel;
	/** 备注 */
	private String remark;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpPmainAgri() {
	}

	/**       
	 * 批单申请号
	 */
	@Id
	@Column(name = "applyno", unique = true, nullable = false)
	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", unique = true, nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 种植/养殖时间
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "raisedate")
	public Date getRaiseDate() {
		return this.raiseDate;
	}

	public void setRaiseDate(Date raiseDate) {
		this.raiseDate = raiseDate;
	}

	/**       
	 * 种植地点/养殖地点/坐落地点
	 */

	@Column(name = "raisesite")
	public String getRaiseSite() {
		return this.raiseSite;
	}

	public void setRaiseSite(String raiseSite) {
		this.raiseSite = raiseSite;
	}
	
	/**       
	 * 地理信息
	 */

	@Column(name = "raisecoordinates")
	public String getRaiseCoordinates() {
		return raiseCoordinates;
	}

	public void setRaiseCoordinates(String raiseCoordinates) {
		this.raiseCoordinates = raiseCoordinates;
	}

	/**       
	 * 村域种植规模(亩)
	 */

	@Column(name = "raisearea")
	public String getRaiseArea() {
		return raiseArea;
	}

	public void setRaiseArea(String raiseArea) {
		this.raiseArea = raiseArea;
	}

	@Column(name = "longitudestart")
	public String getLongitudeStart() {
		return longitudeStart;
	}

	public void setLongitudeStart(String longitudeStart) {
		this.longitudeStart = longitudeStart;
	}
	@Column(name = "longitudeend")
	public String getLongitudeEnd() {
		return longitudeEnd;
	}

	public void setLongitudeEnd(String longitudeEnd) {
		this.longitudeEnd = longitudeEnd;
	}
	@Column(name = "latitudestart")
	public String getLatitudeStart() {
		return latitudeStart;
	}

	public void setLatitudeStart(String latitudeStart) {
		this.latitudeStart = latitudeStart;
	}
	@Column(name = "latitudeend")
	public String getLatitudeEnd() {
		return latitudeEnd;
	}

	public void setLatitudeEnd(String latitudeEnd) {
		this.latitudeEnd = latitudeEnd;
	}

	/**       
	 * 总投保面积(种植险)
	 */

	@Column(name = "insurearea")
	public BigDecimal getInsureArea() {
		return this.insureArea;
	}

	public void setInsureArea(BigDecimal insureArea) {
		this.insureArea = insureArea;
	}

	/**       
	 * 养殖方式(养殖险)
	 */

	@Column(name = "farmingmethod")
	public String getFarmingMethod() {
		return this.farmingMethod;
	}

	public void setFarmingMethod(String farmingMethod) {
		this.farmingMethod = farmingMethod;
	}

	/**       
	 * 业务类型
	 */

	@Column(name = "businesstype")
	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	/**       
	 * 经营模式
	 */

	@Column(name = "businessmodel")
	public String getBusinessModel() {
		return this.businessModel;
	}

	public void setBusinessModel(String businessModel) {
		this.businessModel = businessModel;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

}
