package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpPinsuredNature generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppinsurednature")
public class PrpPinsuredNature implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** SerialNo */
	private PrpPinsuredNatureId id;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 关系人角色标志 */
	private String insuredFlag;
	/** 性别 */
	private String sex;
	/** 年龄 */
	private Integer age;
	/** 出生日期 */
	private Date birthday;
	/** 健康状况 */
	private String health;
	/** 职称 */
	private String jobTitle;
	/** 在本地工作年限 */
	private Integer localWorkYears;
	/** 学历 */
	private String education;
	/** 总工龄 */
	private Integer totalWorkYears;
	/** 担保物计量单位 */
	private String unit;
	/** 单位电话 */
	private String unitPhoneNumber;
	/** 单位地址 */
	private String unitAddress;
	/** 单位邮编 */
	private String unitPostCode;
	/** 单位性质 */
	private String unitType;
	/** 任职级别 */
	private String dutyLevel;
	/** 任职种类 */
	private String dutyType;
	/** 个人职业代码 */
	private String occupationCode;
	/** 房产状况 */
	private String houseProperty;
	/** 户口所在地派出所名称 */
	private String localPoliceStation;
	/** 经常住房地 */
	private String roomAddress;
	/** 邮政编码 */
	private String roomPostCode;
	/** 本人月收入 */
	private BigDecimal selfMonthIncome;
	/** 家庭月收入 */
	private BigDecimal familyMonthIncome;
	/** 收入来源 */
	private String incomeSource;
	/** 常住房电话 */
	private String roomPhone;
	/** 移动电话 */
	private String mobile;
	/** 家庭人口 */
	private Integer familySumQuantity;
	/** 婚姻状况 */
	private String marriage;
	/** 配偶姓名 */
	private String spouseName;
	/** 配偶出生年月 */
	private Date spouseBornDate;
	/** 配偶身份证号码 */
	private String spouseId;
	/** 配偶手机号码 */
	private String spouseMobile;
	/** 配偶单位 */
	private String spouseUnit;
	/** 配偶职务 */
	private String spouseJobTitle;
	/** 配偶单位电话 */
	private String spouseUnitPhone;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpPinsuredNature() {
	}

	/**       
	 * SerialNo
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "serialNo", column = @Column(name = "serialno", nullable = false)) })
	public PrpPinsuredNatureId getId() {
		return this.id;
	}

	public void setId(PrpPinsuredNatureId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 关系人角色标志
	 */

	@Column(name = "insuredflag")
	public String getInsuredFlag() {
		return this.insuredFlag;
	}

	public void setInsuredFlag(String insuredFlag) {
		this.insuredFlag = insuredFlag;
	}

	/**       
	 * 性别
	 */

	@Column(name = "sex")
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	/**       
	 * 年龄
	 */

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	/**       
	 * 出生日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "birthday")
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**       
	 * 健康状况
	 */

	@Column(name = "health")
	public String getHealth() {
		return this.health;
	}

	public void setHealth(String health) {
		this.health = health;
	}

	/**       
	 * 职称
	 */

	@Column(name = "jobtitle")
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	/**       
	 * 在本地工作年限
	 */

	@Column(name = "localworkyears")
	public Integer getLocalWorkYears() {
		return this.localWorkYears;
	}

	public void setLocalWorkYears(Integer localWorkYears) {
		this.localWorkYears = localWorkYears;
	}

	/**       
	 * 学历
	 */

	@Column(name = "education")
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	/**       
	 * 总工龄
	 */

	@Column(name = "totalworkyears")
	public Integer getTotalWorkYears() {
		return this.totalWorkYears;
	}

	public void setTotalWorkYears(Integer totalWorkYears) {
		this.totalWorkYears = totalWorkYears;
	}

	/**       
	 * 担保物计量单位
	 */

	@Column(name = "unit")
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**       
	 * 单位电话
	 */

	@Column(name = "unitphonenumber")
	public String getUnitPhoneNumber() {
		return this.unitPhoneNumber;
	}

	public void setUnitPhoneNumber(String unitPhoneNumber) {
		this.unitPhoneNumber = unitPhoneNumber;
	}

	/**       
	 * 单位地址
	 */

	@Column(name = "unitaddress")
	public String getUnitAddress() {
		return this.unitAddress;
	}

	public void setUnitAddress(String unitAddress) {
		this.unitAddress = unitAddress;
	}

	/**       
	 * 单位邮编
	 */

	@Column(name = "unitpostcode")
	public String getUnitPostCode() {
		return this.unitPostCode;
	}

	public void setUnitPostCode(String unitPostCode) {
		this.unitPostCode = unitPostCode;
	}

	/**       
	 * 单位性质
	 */

	@Column(name = "unittype")
	public String getUnitType() {
		return this.unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	/**       
	 * 任职级别
	 */

	@Column(name = "dutylevel")
	public String getDutyLevel() {
		return this.dutyLevel;
	}

	public void setDutyLevel(String dutyLevel) {
		this.dutyLevel = dutyLevel;
	}

	/**       
	 * 任职种类
	 */

	@Column(name = "dutytype")
	public String getDutyType() {
		return this.dutyType;
	}

	public void setDutyType(String dutyType) {
		this.dutyType = dutyType;
	}

	/**       
	 * 个人职业代码
	 */

	@Column(name = "occupationcode")
	public String getOccupationCode() {
		return this.occupationCode;
	}

	public void setOccupationCode(String occupationCode) {
		this.occupationCode = occupationCode;
	}

	/**       
	 * 房产状况
	 */

	@Column(name = "houseproperty")
	public String getHouseProperty() {
		return this.houseProperty;
	}

	public void setHouseProperty(String houseProperty) {
		this.houseProperty = houseProperty;
	}

	/**       
	 * 户口所在地派出所名称
	 */

	@Column(name = "localpolicestation")
	public String getLocalPoliceStation() {
		return this.localPoliceStation;
	}

	public void setLocalPoliceStation(String localPoliceStation) {
		this.localPoliceStation = localPoliceStation;
	}

	/**       
	 * 经常住房地
	 */

	@Column(name = "roomaddress")
	public String getRoomAddress() {
		return this.roomAddress;
	}

	public void setRoomAddress(String roomAddress) {
		this.roomAddress = roomAddress;
	}

	/**       
	 * 邮政编码
	 */

	@Column(name = "roompostcode")
	public String getRoomPostCode() {
		return this.roomPostCode;
	}

	public void setRoomPostCode(String roomPostCode) {
		this.roomPostCode = roomPostCode;
	}

	/**       
	 * 本人月收入
	 */

	@Column(name = "selfmonthincome")
	public BigDecimal getSelfMonthIncome() {
		return this.selfMonthIncome;
	}

	public void setSelfMonthIncome(BigDecimal selfMonthIncome) {
		this.selfMonthIncome = selfMonthIncome;
	}

	/**       
	 * 家庭月收入
	 */

	@Column(name = "familymonthincome")
	public BigDecimal getFamilyMonthIncome() {
		return this.familyMonthIncome;
	}

	public void setFamilyMonthIncome(BigDecimal familyMonthIncome) {
		this.familyMonthIncome = familyMonthIncome;
	}

	/**       
	 * 收入来源
	 */

	@Column(name = "incomesource")
	public String getIncomeSource() {
		return this.incomeSource;
	}

	public void setIncomeSource(String incomeSource) {
		this.incomeSource = incomeSource;
	}

	/**       
	 * 常住房电话
	 */

	@Column(name = "roomphone")
	public String getRoomPhone() {
		return this.roomPhone;
	}

	public void setRoomPhone(String roomPhone) {
		this.roomPhone = roomPhone;
	}

	/**       
	 * 移动电话
	 */

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**       
	 * 家庭人口
	 */

	@Column(name = "familysumquantity")
	public Integer getFamilySumQuantity() {
		return this.familySumQuantity;
	}

	public void setFamilySumQuantity(Integer familySumQuantity) {
		this.familySumQuantity = familySumQuantity;
	}

	/**       
	 * 婚姻状况
	 */

	@Column(name = "marriage")
	public String getMarriage() {
		return this.marriage;
	}

	public void setMarriage(String marriage) {
		this.marriage = marriage;
	}

	/**       
	 * 配偶姓名
	 */

	@Column(name = "spousename")
	public String getSpouseName() {
		return this.spouseName;
	}

	public void setSpouseName(String spouseName) {
		this.spouseName = spouseName;
	}

	/**       
	 * 配偶出生年月
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "spouseborndate")
	public Date getSpouseBornDate() {
		return this.spouseBornDate;
	}

	public void setSpouseBornDate(Date spouseBornDate) {
		this.spouseBornDate = spouseBornDate;
	}

	/**       
	 * 配偶身份证号码
	 */

	@Column(name = "spouseid")
	public String getSpouseId() {
		return this.spouseId;
	}

	public void setSpouseId(String spouseId) {
		this.spouseId = spouseId;
	}

	/**       
	 * 配偶手机号码
	 */

	@Column(name = "spousemobile")
	public String getSpouseMobile() {
		return this.spouseMobile;
	}

	public void setSpouseMobile(String spouseMobile) {
		this.spouseMobile = spouseMobile;
	}

	/**       
	 * 配偶单位
	 */

	@Column(name = "spouseunit")
	public String getSpouseUnit() {
		return this.spouseUnit;
	}

	public void setSpouseUnit(String spouseUnit) {
		this.spouseUnit = spouseUnit;
	}

	/**       
	 * 配偶职务
	 */

	@Column(name = "spousejobtitle")
	public String getSpouseJobTitle() {
		return this.spouseJobTitle;
	}

	public void setSpouseJobTitle(String spouseJobTitle) {
		this.spouseJobTitle = spouseJobTitle;
	}

	/**       
	 * 配偶单位电话
	 */

	@Column(name = "spouseunitphone")
	public String getSpouseUnitPhone() {
		return this.spouseUnitPhone;
	}

	public void setSpouseUnitPhone(String spouseUnitPhone) {
		this.spouseUnitPhone = spouseUnitPhone;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

}
