package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpPitemShip generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppitem_ship")
public class PrpPitemShip implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 标的序号 */
	private PrpPitemShipId id;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 船队编号 */
	private String fleetNo;
	/** 标的库序号 */
	private Integer ditemno;
	/** 船舶代码 */
	private String shipCode;
	/** 船名(中文) */
	private String shipCName;
	/** 船名(英文) */
	private String shipEName;
	/** 曾用名 */
	private String oldShipName;
	/** 船东 */
	private String shipOwner;
	/** 原船东 */
	private String oldShipOwner;
	/** 经营者 */
	private String conveyManager;
	/** 保赔协会 */
	private String associate;
	/** 建造年月 */
	private Date makeYearMonth;
	/** 国家代码 */
	private String countryCode;
	/** 制造厂商 */
	private String makeFactory;
	/** 建造船坞名称及地址 */
	private String makeDock;
	/** 船台类型 */
	private String shipWayType;
	/** 适用规范 */
	private String applyCriterion;
	/** 建造合同号 */
	private String makeContractNo;
	/** 建造起始日期 */
	private Date makeStartDate;
	/** 建造终止日期 */
	private Date makeEndDate;
	/** 预建周期 */
	private String preBuildCyc;
	/** 船级 */
	private String stepHull;
	/** 原船级 */
	private String oldStepHull;
	/** 船旗 */
	private String shipFlag;
	/** 船舶种类代码 */
	private String shipTypeCode;
	/** 使用性质代码 */
	private String useNatureCode;
	/** 船舶用途 */
	private String shipUsage;
	/** 船质结构代码 */
	private String shipStruct;
	/** 注册地点 */
	private String registrySite;
	/** 吨位数 */
	private BigDecimal tonCount;
	/** 净吨位 */
	private BigDecimal netTonCount;
	/** 功率 */
	private BigDecimal horsePower;
	/** 功率单位 */
	private String powerUnit;
	/** 座位数 */
	private Integer seatCount;
	/** 载重吨 */
	private BigDecimal loadTon;
	/** 总长 */
	private BigDecimal shipLength;
	/** 型宽 */
	private BigDecimal shipWidth;
	/** 型深 */
	private BigDecimal shipDepth;
	/** 试航期限 */
	private String trySailPeriod;
	/** 试航区域 */
	private String trySailArea;
	/** 船籍港 */
	private String shipPort;
	/** 出航日期 */
	private Date launchDate;
	/** 航行区域代码 */
	private String sailAreaCode;
	/** 航行区域名称 */
	private String sailAreaName;
	/** 航行范围 */
	private String sailScope;
	/** 航行方式 */
	private String sailModeCode;
	/** 航行距离 */
	private String voyage;
	/** 船舶价值 */
	private BigDecimal shipValue;
	/** 币别 */
	private String currency;
	/** 停航开始日期 */
	private Date suspendStartDate;
	/** 停航结束日期 */
	private Date suspendEndDate;
	/** 抵押权人 */
	private String mortgageName;
	/** 被保险人与船舶关系 */
	private String insurerShipRelation;
	/** 船舶呼号 */
	private String shipCallSign;
	/** IMO号 */
	private String imo;
	/** 船舶经营/管理人地址 */
	private String shipManagerAddress;
	/** 改造年份 */
	private Date reconstructionYear;
	/** 船队现属保赔协会 */
	private String shipAssociation;
	/** 船队规模（总数）*/
	private Integer fleetTotalScale;
	/** 船队规模（PICC承保数）*/
	private Integer fleetPICCScale;
	/** 船舶建造地址 */
	private String shipConstractionAdrdress;
	/** 下水方式 */
	private String launchType;
	/** 船舶国籍证书—发证机关 */
	private String govAgencyForShip;
	/** 船舶国籍证书—发证日期 */
	private Date licStartDateForShip;
	/** 船舶国籍证书—证书终止日期 */
	private Date licEndDateForShip;
	/** 船体入级证书—发证机关 */
	private String govAgencyForHull;
	/** 船体入级证书—发证日期 */
	private Date licStartDateForHull;
	/** 船体入级证书—证书终止日期 */
	private Date licEndDateForHull;
	/** 临时船体入级证书—发证机关 */
	private String govAgencyForTempHull;
	/** 临时船体入级证书—发证日期 */
	private Date licStartDateForTempHull;
	/** 临时船体入级证书—证书终止日期 */
	private Date licenceEndDateForTempHull;
	/** 轮机入级证书—发证机关 */
	private String govAgencyForMachinery;
	/** 轮机入级证书—发证日期 */
	private Date licStartDateForMachinery;
	/** 轮机入级证书—证书终止日期 */
	private Date licEndDateForMachinery;
	/** 临时轮机入级证书—发证机关 */
	private String govAgencyForTempMachinery;
	/** 临时轮机入级证书—发证日期 */
	private Date licStartDateForTempMachinery;
	/** 临时轮机入级证书—证书终止日期 */
	private Date licEndDateForTempMachinery;
	/** 是否有国际吨位证书 */
	private String isLicForIntTon;
	/** 国际吨位证书—发证日期 */
	private Date licStartDateForIntTon;
	/** 国际吨位证书—证书终止日期 */
	private Date licEndDateForIntTon;
	/** 是否有国际船舶载重线证书 */
	private String isLicForIntLoad;
	/** 国际船舶载重线证书—发证日期 */
	private Date licStartDateForIntLoad;
	/** 国际船舶载重线证书—证书终止日期 */
	private Date licEndDateForIntLoad;
	/** 是否有货船构造安全证书 */
	private String isLicForConstruction;
	/** 货船构造安全证书—发证日期 */
	private Date licStartDateForConstruction;
	/** 货船构造安全证书—证书终止日期 */
	private Date licEndDateForConstruction;
	/** 是否有货船设备安全证书 */
	private String isLicForEquipment;
	/** 货船设备安全证书—发证日期 */
	private Date licStartDateForEquipment;
	/** 货船设备安全证书—证书终止日期 */
	private Date licEndDateForEquipment;
	/** 是否有货船无线电报安全证书 */
	private String isLicForWireLess;
	/** 货船无线电安全证书—发证日期 */
	private Date licStartDateForWireLess;
	/** 货船无线电安全证书—证书终止日期 */
	private Date licEndDateForWireLess;
	/** 是否有起重设备证书 */
	private String isLicForLift;
	/** 起重设备证书—发证日期 */
	private Date licStartDateForLift;
	/** 起重设备证书—证书终止日期 */
	private Date licEndDateForLift;
	/** 是否有适装证书 */
	private String isLicForFitness;
	/** 适装证书—发证日期 */
	private Date licStartDateForFitness;
	/** 适装证书—证书终止日期 */
	private Date licEndDateForFitness;
	/** 是否有国际防止油污证书 */
	private String isLicForIOPP;
	/** 国际防止污染证书—发证日期 */
	private Date licStartDateForIOPP; 
	/** 国际防止污染证书—证书终止日期 */
	private Date licEndDateForIOPP;
	/** 是否有船舶航行安全证书 */
	private String isLicForNavigation;
	/** 船舶航行安全证书—发证日期 */
	private Date licStartDateForNavigation; 
	/** 船舶航行安全证书—证书终止日期 */
	private Date licEndDateForNavigation; 
	/** 是否有船舶安全管理证书 */
	private String isLicForSMC;
	/** 船舶安全管理证书—发证日期 */
	private Date licStartDateForSMC;
	/** 船舶安全管理证书—证书终止日期 */
	private Date licEndDateForSMC;
	/** 是否有船舶符合证明 */
	private String isLicForConform;
	/** 船舶符合证明—发证日期 */
	private Date licStartDateForConform;
	/** 船舶符合证明—证书终止日期 */
	private Date licEndDateForConform;
	/** 是否有船舶最低安全配员证书 */
	private String isLicForMSM;
	/** 船舶最低安全配员证书—发证日期 */
	private Date licStartDateForMSM;
	/** 船舶最低安全配员证书—证书终止日期 */
	private Date licEndDateForMSM;
	/** 建造船坞地址 */
	private String makeDockAddress;
	/** 建造人的船厂、船坞范围内建造的船壳和机器—保险项目 */
	private String projectForBuilder;
	/** 建造人的船厂、船坞范围内建造的船壳和机器—合同或船坞编号 */
	private String constractNoForBuilder;
	/** 建造人的船厂、船坞范围内建造的船壳和机器—保险金额 */
	private String amountForBuilder;
	/** 建造人的船厂、船坞范围内建造的船壳和机器—建造地点 */
	private String addressForBuilder;
	/** 由分承包人建造的被保险船壳和机器—保险项目名称 */
	private String projectForSub;
	/** 由分承包人建造的被保险船壳和机器—合同或船坞编号 */
	private String constractNoForSub;
	/** 由分承包人建造的被保险船壳和机器—建造地点 */
	private String addressForSub;
	/** 建造人的建造能力及历史记录 */
	private String historyForBuilder;
	/** 建成价格/合同最后价格 */
	private String lastPrice;
	/** 交船地点 */
	private String deliveryPlace;
	/**动工日期*/
	private Date beginDate;
	/** 上船台日期 */
	private Date stageDate;
	/** 下水日期 */
	private Date waterDate;
	/** 试航日期 */
	private Date sailDate;
	/** 交船日期 */
	private Date deliveryDate;
	/** 建造合同中被保险人的身份 */
	private String insuredStatus;
	/** 实际船东 */
	private String actualShipOwner;
	/** 装载类型 */
	private String loadType;
	/** 装载方式 */
	private String loadStyle;
	/** 船舶登记所有人 */
	private String shipRegisterOwner;
	/** 船舶所有人主要营业地 */
	private String shipRegisterPlace;
	/** 新船合同价 */
	private String newContractPrice;
	/** 备注 */
	private String remark;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpPitemShip() {
	}

	/**       
	 * 标的序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "itemno", nullable = false)) })
	public PrpPitemShipId getId() {
		return this.id;
	}

	public void setId(PrpPitemShipId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 船队编号
	 */

	@Column(name = "fleetno")
	public String getFleetNo() {
		return this.fleetNo;
	}

	public void setFleetNo(String fleetNo) {
		this.fleetNo = fleetNo;
	}

	/**       
	 * 船舶代码
	 */

	@Column(name = "shipcode", nullable = false)
	public String getShipCode() {
		return this.shipCode;
	}

	public void setShipCode(String shipCode) {
		this.shipCode = shipCode;
	}

	/**       
	 * 船名(中文)
	 */

	@Column(name = "shipcname")
	public String getShipCName() {
		return this.shipCName;
	}

	public void setShipCName(String shipCName) {
		this.shipCName = shipCName;
	}

	/**       
	 * 船名(英文)
	 */

	@Column(name = "shipename")
	public String getShipEName() {
		return this.shipEName;
	}

	public void setShipEName(String shipEName) {
		this.shipEName = shipEName;
	}

	/**       
	 * 曾用名
	 */

	@Column(name = "oldshipname")
	public String getOldShipName() {
		return this.oldShipName;
	}

	public void setOldShipName(String oldShipName) {
		this.oldShipName = oldShipName;
	}

	/**       
	 * 船东
	 */

	@Column(name = "shipowner")
	public String getShipOwner() {
		return this.shipOwner;
	}

	public void setShipOwner(String shipOwner) {
		this.shipOwner = shipOwner;
	}

	/**       
	 * 原船东
	 */

	@Column(name = "oldshipowner")
	public String getOldShipOwner() {
		return this.oldShipOwner;
	}

	public void setOldShipOwner(String oldShipOwner) {
		this.oldShipOwner = oldShipOwner;
	}

	/**       
	 * 经营者
	 */

	@Column(name = "conveymanager")
	public String getConveyManager() {
		return this.conveyManager;
	}

	public void setConveyManager(String conveyManager) {
		this.conveyManager = conveyManager;
	}

	/**       
	 * 保赔协会
	 */

	@Column(name = "associate")
	public String getAssociate() {
		return this.associate;
	}

	public void setAssociate(String associate) {
		this.associate = associate;
	}

	/**       
	 * 建造年月
	 */

	@Column(name = "makeyearmonth")
	public Date getMakeYearMonth() {
		return this.makeYearMonth;
	}

	public void setMakeYearMonth(Date makeYearMonth) {
		this.makeYearMonth = makeYearMonth;
	}

	/**       
	 * 国家代码
	 */

	@Column(name = "countrycode")
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	/**       
	 * 制造厂商
	 */

	@Column(name = "makefactory")
	public String getMakeFactory() {
		return this.makeFactory;
	}

	public void setMakeFactory(String makeFactory) {
		this.makeFactory = makeFactory;
	}

	/**       
	 * 建造船坞名称及地址
	 */

	@Column(name = "makedock")
	public String getMakeDock() {
		return this.makeDock;
	}

	public void setMakeDock(String makeDock) {
		this.makeDock = makeDock;
	}

	/**       
	 * 船台类型
	 */

	@Column(name = "shipwaytype")
	public String getShipWayType() {
		return this.shipWayType;
	}

	public void setShipWayType(String shipWayType) {
		this.shipWayType = shipWayType;
	}

	/**       
	 * 适用规范
	 */

	@Column(name = "applycriterion")
	public String getApplyCriterion() {
		return this.applyCriterion;
	}

	public void setApplyCriterion(String applyCriterion) {
		this.applyCriterion = applyCriterion;
	}

	/**       
	 * 建造合同号
	 */

	@Column(name = "makecontractno")
	public String getMakeContractNo() {
		return this.makeContractNo;
	}

	public void setMakeContractNo(String makeContractNo) {
		this.makeContractNo = makeContractNo;
	}

	/**       
	 * 建造起始日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "makestartdate")
	public Date getMakeStartDate() {
		return this.makeStartDate;
	}

	public void setMakeStartDate(Date makeStartDate) {
		this.makeStartDate = makeStartDate;
	}

	/**       
	 * 建造终止日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "makeenddate")
	public Date getMakeEndDate() {
		return this.makeEndDate;
	}

	public void setMakeEndDate(Date makeEndDate) {
		this.makeEndDate = makeEndDate;
	}

	/**       
	 * 预建周期
	 */

	@Column(name = "prebuildcyc")
	public String getPreBuildCyc() {
		return this.preBuildCyc;
	}

	public void setPreBuildCyc(String preBuildCyc) {
		this.preBuildCyc = preBuildCyc;
	}

	/**       
	 * 船级
	 */

	@Column(name = "stephull")
	public String getStepHull() {
		return this.stepHull;
	}

	public void setStepHull(String stepHull) {
		this.stepHull = stepHull;
	}

	/**       
	 * 原船级
	 */

	@Column(name = "oldstephull")
	public String getOldStepHull() {
		return this.oldStepHull;
	}

	public void setOldStepHull(String oldStepHull) {
		this.oldStepHull = oldStepHull;
	}

	/**       
	 * 船旗
	 */

	@Column(name = "shipflag")
	public String getShipFlag() {
		return this.shipFlag;
	}

	public void setShipFlag(String shipFlag) {
		this.shipFlag = shipFlag;
	}

	/**       
	 * 船舶种类代码
	 */

	@Column(name = "shiptypecode")
	public String getShipTypeCode() {
		return this.shipTypeCode;
	}

	public void setShipTypeCode(String shipTypeCode) {
		this.shipTypeCode = shipTypeCode;
	}

	/**       
	 * 使用性质代码
	 */

	@Column(name = "usenaturecode")
	public String getUseNatureCode() {
		return this.useNatureCode;
	}

	public void setUseNatureCode(String useNatureCode) {
		this.useNatureCode = useNatureCode;
	}

	/**       
	 * 船舶用途
	 */

	@Column(name = "shipusage")
	public String getShipUsage() {
		return this.shipUsage;
	}

	public void setShipUsage(String shipUsage) {
		this.shipUsage = shipUsage;
	}

	/**       
	 * 船质结构代码
	 */

	@Column(name = "shipstruct")
	public String getShipStruct() {
		return this.shipStruct;
	}

	public void setShipStruct(String shipStruct) {
		this.shipStruct = shipStruct;
	}

	/**       
	 * 注册地点
	 */

	@Column(name = "registrysite")
	public String getRegistrySite() {
		return this.registrySite;
	}

	public void setRegistrySite(String registrySite) {
		this.registrySite = registrySite;
	}

	/**       
	 * 吨位数
	 */

	@Column(name = "toncount")
	public BigDecimal getTonCount() {
		return this.tonCount;
	}

	public void setTonCount(BigDecimal tonCount) {
		this.tonCount = tonCount;
	}

	/**       
	 * 净吨位
	 */

	@Column(name = "nettoncount")
	public BigDecimal getNetTonCount() {
		return this.netTonCount;
	}

	public void setNetTonCount(BigDecimal netTonCount) {
		this.netTonCount = netTonCount;
	}

	/**       
	 * 功率
	 */

	@Column(name = "horsepower")
	public BigDecimal getHorsePower() {
		return this.horsePower;
	}

	public void setHorsePower(BigDecimal horsePower) {
		this.horsePower = horsePower;
	}

	/**       
	 * 功率单位
	 */

	@Column(name = "powerunit")
	public String getPowerUnit() {
		return this.powerUnit;
	}

	public void setPowerUnit(String powerUnit) {
		this.powerUnit = powerUnit;
	}

	/**       
	 * 座位数
	 */

	@Column(name = "seatcount")
	public Integer getSeatCount() {
		return this.seatCount;
	}

	public void setSeatCount(Integer seatCount) {
		this.seatCount = seatCount;
	}

	/**       
	 * 载重吨
	 */

	@Column(name = "loadton")
	public BigDecimal getLoadTon() {
		return this.loadTon;
	}

	public void setLoadTon(BigDecimal loadTon) {
		this.loadTon = loadTon;
	}

	/**       
	 * 总长
	 */

	@Column(name = "shiplength")
	public BigDecimal getShipLength() {
		return this.shipLength;
	}

	public void setShipLength(BigDecimal shipLength) {
		this.shipLength = shipLength;
	}

	/**       
	 * 型宽
	 */

	@Column(name = "shipwidth")
	public BigDecimal getShipWidth() {
		return this.shipWidth;
	}

	public void setShipWidth(BigDecimal shipWidth) {
		this.shipWidth = shipWidth;
	}

	/**       
	 * 型深
	 */

	@Column(name = "shipdepth")
	public BigDecimal getShipDepth() {
		return this.shipDepth;
	}

	public void setShipDepth(BigDecimal shipDepth) {
		this.shipDepth = shipDepth;
	}

	/**       
	 * 试航期限
	 */

	@Column(name = "trysailperiod")
	public String getTrySailPeriod() {
		return this.trySailPeriod;
	}

	public void setTrySailPeriod(String trySailPeriod) {
		this.trySailPeriod = trySailPeriod;
	}

	/**       
	 * 试航区域
	 */

	@Column(name = "trysailarea")
	public String getTrySailArea() {
		return this.trySailArea;
	}

	public void setTrySailArea(String trySailArea) {
		this.trySailArea = trySailArea;
	}

	/**       
	 * 船籍港
	 */

	@Column(name = "shipport")
	public String getShipPort() {
		return this.shipPort;
	}

	public void setShipPort(String shipPort) {
		this.shipPort = shipPort;
	}

	/**       
	 * 出航日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "launchdate")
	public Date getLaunchDate() {
		return this.launchDate;
	}

	public void setLaunchDate(Date launchDate) {
		this.launchDate = launchDate;
	}

	/**       
	 * 航行区域代码
	 */

	@Column(name = "sailareacode")
	public String getSailAreaCode() {
		return this.sailAreaCode;
	}

	public void setSailAreaCode(String sailAreaCode) {
		this.sailAreaCode = sailAreaCode;
	}

	/**       
	 * 航行区域名称
	 */

	@Column(name = "sailareaname")
	public String getSailAreaName() {
		return this.sailAreaName;
	}

	public void setSailAreaName(String sailAreaName) {
		this.sailAreaName = sailAreaName;
	}

	/**       
	 * 航行范围
	 */

	@Column(name = "sailscope")
	public String getSailScope() {
		return this.sailScope;
	}

	public void setSailScope(String sailScope) {
		this.sailScope = sailScope;
	}

	/**       
	 * 航行方式
	 */

	@Column(name = "sailmodecode")
	public String getSailModeCode() {
		return this.sailModeCode;
	}

	public void setSailModeCode(String sailModeCode) {
		this.sailModeCode = sailModeCode;
	}

	/**       
	 * 航行距离
	 */

	@Column(name = "voyage")
	public String getVoyage() {
		return this.voyage;
	}

	public void setVoyage(String voyage) {
		this.voyage = voyage;
	}

	/**       
	 * 船舶价值
	 */

	@Column(name = "shipvalue")
	public BigDecimal getShipValue() {
		return this.shipValue;
	}

	public void setShipValue(BigDecimal shipValue) {
		this.shipValue = shipValue;
	}

	/**       
	 * 币别
	 */

	@Column(name = "currency")
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/**       
	 * 停航开始日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "suspendstartdate")
	public Date getSuspendStartDate() {
		return this.suspendStartDate;
	}

	public void setSuspendStartDate(Date suspendStartDate) {
		this.suspendStartDate = suspendStartDate;
	}

	/**       
	 * 停航结束日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "suspendenddate")
	public Date getSuspendEndDate() {
		return this.suspendEndDate;
	}

	public void setSuspendEndDate(Date suspendEndDate) {
		this.suspendEndDate = suspendEndDate;
	}

	/**       
	 * 抵押权人
	 */

	@Column(name = "mortgagename")
	public String getMortgageName() {
		return this.mortgageName;
	}

	public void setMortgageName(String mortgageName) {
		this.mortgageName = mortgageName;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
	/**
	 * 标的库序号
	 * @return
	 */
	@Column(name = "ditemno")
	public Integer getDitemno() {
		return this.ditemno;
	}

	public void setDitemno(Integer ditemno) {
		this.ditemno = ditemno;
	}
	/**
	 * 被保险人与船舶关系
	 * @return
	 */
	@Column(name = "insurershiprelation")
	public String getInsurerShipRelation() {
		return insurerShipRelation;
	}

	public void setInsurerShipRelation(String insurerShipRelation) {
		this.insurerShipRelation = insurerShipRelation;
	}
	/**
	 * 船舶呼号
	 * @return
	 */
	@Column(name = "shipcallsign")
	public String getShipCallSign() {
		return shipCallSign;
	}

	public void setShipCallSign(String shipCallSign) {
		this.shipCallSign = shipCallSign;
	}
	/**
	 * IMO号
	 * @return
	 */
	@Column(name = "imo")
	public String getImo() {
		return imo;
	}

	public void setImo(String imo) {
		this.imo = imo;
	}
	
	/**
	 * 船舶经营/管理人地址
	 * @return
	 */
	@Column(name = "shipManagerAddress")
	public String getShipManagerAddress() {
		return shipManagerAddress;
	}

	public void setShipManagerAddress(String shipManagerAddress) {
		this.shipManagerAddress = shipManagerAddress;
	}
	
	/**
	 * 改造年份
	 * @return
	 */
	@Column(name = "reconstructionYear")
	public Date getReconstructionYear() {
		return reconstructionYear;
	}

	public void setReconstructionYear(Date reconstructionYear) {
		this.reconstructionYear = reconstructionYear;
	}
	
	/**
	 * 船队现属保赔协会
	 * @return
	 */
	@Column(name = "shipAssociation")
	public String getShipAssociation() {
		return shipAssociation;
	}
	
	public void setShipAssociation(String shipAssociation) {
		this.shipAssociation = shipAssociation;
	}
	/**
	 * 船队规模（总数）
	 * @return
	 */
	@Column(name = "fleetTotalScale")
	public Integer getFleetTotalScale() {
		return fleetTotalScale;
	}

	public void setFleetTotalScale(Integer fleetTotalScale) {
		this.fleetTotalScale = fleetTotalScale;
	}

	/**
	 * 船队规模（PICC承保数）
	 * @return
	 */
	@Column(name = "fleetPICCScale")
	public Integer getFleetPICCScale() {
		return fleetPICCScale;
	}

	public void setFleetPICCScale(Integer fleetPICCScale) {
		this.fleetPICCScale = fleetPICCScale;
	}

	/**
	 * 船舶建造地址
	 * @return
	 */
	@Column(name = "shipConstractionAdrdress")
	public String getShipConstractionAdrdress() {
		return shipConstractionAdrdress;
	}

	public void setShipConstractionAdrdress(String shipConstractionAdrdress) {
		this.shipConstractionAdrdress = shipConstractionAdrdress;
	}

	/**
	 * 下水方式
	 * @return
	 */
	@Column(name = "launchType")
	public String getLaunchType() {
		return launchType;
	}

	public void setLaunchType(String launchType) {
		this.launchType = launchType;
	}

	/**
	 * 船舶国籍证书—发证机关
	 * @return
	 */
	@Column(name = "govagencyforship")
	public String getGovAgencyForShip() {
		return govAgencyForShip;
	}

	public void setGovAgencyForShip(String govAgencyForShip) {
		this.govAgencyForShip = govAgencyForShip;
	}
	/**
	 * 船舶国籍证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforship")
	public Date getLicStartDateForShip() {
		return licStartDateForShip;
	}
	
	public void setLicStartDateForShip(Date licStartDateForShip) {
		this.licStartDateForShip = licStartDateForShip;
	}
	/**
	 * 船舶国籍证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforship")
	public Date getLicEndDateForShip() {
		return licEndDateForShip;
	}

	public void setLicEndDateForShip(Date licEndDateForShip) {
		this.licEndDateForShip = licEndDateForShip;
	}
	/**
	 * 船体入级证书—发证机关
	 * @return
	 */
	@Column(name = "govagencyforhull")
	public String getGovAgencyForHull() {
		return govAgencyForHull;
	}

	public void setGovAgencyForHull(String govAgencyForHull) {
		this.govAgencyForHull = govAgencyForHull;
	}
	/**
	 * 船体入级证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforhull")
	public Date getLicStartDateForHull() {
		return licStartDateForHull;
	}

	public void setLicStartDateForHull(Date licStartDateForHull) {
		this.licStartDateForHull = licStartDateForHull;
	}
	/**
	 * 船体入级证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforhull")
	public Date getLicEndDateForHull() {
		return licEndDateForHull;
	}

	public void setLicEndDateForHull(Date licEndDateForHull) {
		this.licEndDateForHull = licEndDateForHull;
	}
	/**
	 * 临时船体入级证书—发证机关
	 * @return
	 */
	@Column(name = "govagencyfortemphull")
	public String getGovAgencyForTempHull() {
		return govAgencyForTempHull;
	}

	public void setGovAgencyForTempHull(String govAgencyForTempHull) {
		this.govAgencyForTempHull = govAgencyForTempHull;
	}
	/**
	 * 临时船体入级证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdatefortemphull")
	public Date getLicStartDateForTempHull() {
		return licStartDateForTempHull;
	}

	public void setLicStartDateForTempHull(Date licStartDateForTempHull) {
		this.licStartDateForTempHull = licStartDateForTempHull;
	}
	/**
	 * 临时船体入级证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenceenddatefortemphull")
	public Date getLicenceEndDateForTempHull() {
		return licenceEndDateForTempHull;
	}

	public void setLicenceEndDateForTempHull(Date licenceEndDateForTempHull) {
		this.licenceEndDateForTempHull = licenceEndDateForTempHull;
	}
	/**
	 * 轮机入级证书—发证机关
	 * @return
	 */
	@Column(name = "govagencyformachinery")
	public String getGovAgencyForMachinery() {
		return govAgencyForMachinery;
	}

	public void setGovAgencyForMachinery(String govAgencyForMachinery) {
		this.govAgencyForMachinery = govAgencyForMachinery;
	}
	/**
	 * 轮机入级证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateformachinery")
	public Date getLicStartDateForMachinery() {
		return licStartDateForMachinery;
	}

	public void setLicStartDateForMachinery(Date licStartDateForMachinery) {
		this.licStartDateForMachinery = licStartDateForMachinery;
	}
	/**
	 * 轮机入级证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateformachinery")
	public Date getLicEndDateForMachinery() {
		return licEndDateForMachinery;
	}

	public void setLicEndDateForMachinery(Date licEndDateForMachinery) {
		this.licEndDateForMachinery = licEndDateForMachinery;
	}
	/**
	 * 临时轮机入级证书—发证机关
	 * @return
	 */
	@Column(name = "govagencyfortempmachinery")
	public String getGovAgencyForTempMachinery() {
		return govAgencyForTempMachinery;
	}

	public void setGovAgencyForTempMachinery(String govAgencyForTempMachinery) {
		this.govAgencyForTempMachinery = govAgencyForTempMachinery;
	}
	/**
	 * 临时轮机入级证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdatefortempmachinery")
	public Date getLicStartDateForTempMachinery() {
		return licStartDateForTempMachinery;
	}

	public void setLicStartDateForTempMachinery(Date licStartDateForTempMachinery) {
		this.licStartDateForTempMachinery = licStartDateForTempMachinery;
	}
	/**
	 * 临时轮机入级证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddatefortempmachinery")
	public Date getLicEndDateForTempMachinery() {
		return licEndDateForTempMachinery;
	}

	public void setLicEndDateForTempMachinery(Date licEndDateForTempMachinery) {
		this.licEndDateForTempMachinery = licEndDateForTempMachinery;
	}
	/**
	 * 是否有国际吨位证书
	 * @return
	 */
	@Column(name = "islicforintton")
	public String getIsLicForIntTon() {
		return isLicForIntTon;
	}

	public void setIsLicForIntTon(String isLicForIntTon) {
		this.isLicForIntTon = isLicForIntTon;
	}
	/**
	 * 国际吨位证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforintton")
	public Date getLicStartDateForIntTon() {
		return licStartDateForIntTon;
	}

	public void setLicStartDateForIntTon(Date licStartDateForIntTon) {
		this.licStartDateForIntTon = licStartDateForIntTon;
	}
	/**
	 * 国际吨位证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforintton")
	public Date getLicEndDateForIntTon() {
		return licEndDateForIntTon;
	}

	public void setLicEndDateForIntTon(Date licEndDateForIntTon) {
		this.licEndDateForIntTon = licEndDateForIntTon;
	}
	/**
	 * 是否有国际船舶载重线证书
	 * @return
	 */
	@Column(name = "islicforintload")
	public String getIsLicForIntLoad() {
		return isLicForIntLoad;
	}

	public void setIsLicForIntLoad(String isLicForIntLoad) {
		this.isLicForIntLoad = isLicForIntLoad;
	}
	/**
	 * 国际船舶载重线证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforintload")
	public Date getLicStartDateForIntLoad() {
		return licStartDateForIntLoad;
	}

	public void setLicStartDateForIntLoad(Date licStartDateForIntLoad) {
		this.licStartDateForIntLoad = licStartDateForIntLoad;
	}
	/**
	 * 国际船舶载重线证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforintload")
	public Date getLicEndDateForIntLoad() {
		return licEndDateForIntLoad;
	}

	public void setLicEndDateForIntLoad(Date licEndDateForIntLoad) {
		this.licEndDateForIntLoad = licEndDateForIntLoad;
	}
	/**
	 * 是否有货船构造安全证书
	 * @return
	 */
	@Column(name = "islicforconstruction")
	public String getIsLicForConstruction() {
		return isLicForConstruction;
	}

	public void setIsLicForConstruction(String isLicForConstruction) {
		this.isLicForConstruction = isLicForConstruction;
	}
	/**
	 * 货船构造安全证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforconstruction")
	public Date getLicStartDateForConstruction() {
		return licStartDateForConstruction;
	}

	public void setLicStartDateForConstruction(Date licStartDateForConstruction) {
		this.licStartDateForConstruction = licStartDateForConstruction;
	}
	/**
	 * 货船构造安全证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforconstruction")
	public Date getLicEndDateForConstruction() {
		return licEndDateForConstruction;
	}

	public void setLicEndDateForConstruction(Date licEndDateForConstruction) {
		this.licEndDateForConstruction = licEndDateForConstruction;
	}
	/**
	 * 是否有货船设备安全证书
	 * @return
	 */
	@Column(name = "islicforequipment")
	public String getIsLicForEquipment() {
		return isLicForEquipment;
	}

	public void setIsLicForEquipment(String isLicForEquipment) {
		this.isLicForEquipment = isLicForEquipment;
	}
	/**
	 * 货船设备安全证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforequipment")
	public Date getLicStartDateForEquipment() {
		return licStartDateForEquipment;
	}

	public void setLicStartDateForEquipment(Date licStartDateForEquipment) {
		this.licStartDateForEquipment = licStartDateForEquipment;
	}
	/**
	 * 货船设备安全证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforequipment")
	public Date getLicEndDateForEquipment() {
		return licEndDateForEquipment;
	}

	public void setLicEndDateForEquipment(Date licEndDateForEquipment) {
		this.licEndDateForEquipment = licEndDateForEquipment;
	}
	/**
	 * 是否有货船无线电报安全证书
	 * @return
	 */
	@Column(name = "islicforwireless")
	public String getIsLicForWireLess() {
		return isLicForWireLess;
	}

	public void setIsLicForWireLess(String isLicForWireLess) {
		this.isLicForWireLess = isLicForWireLess;
	}
	/**
	 * 货船无线电安全证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforwireless")
	public Date getLicStartDateForWireLess() {
		return licStartDateForWireLess;
	}

	public void setLicStartDateForWireLess(Date licStartDateForWireLess) {
		this.licStartDateForWireLess = licStartDateForWireLess;
	}
	/**
	 * 货船无线电安全证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforwireless")
	public Date getLicEndDateForWireLess() {
		return licEndDateForWireLess;
	}

	public void setLicEndDateForWireLess(Date licEndDateForWireLess) {
		this.licEndDateForWireLess = licEndDateForWireLess;
	}
	/**
	 * 是否有起重设备证书
	 * @return
	 */
	@Column(name = "islicforlift")
	public String getIsLicForLift() {
		return isLicForLift;
	}

	public void setIsLicForLift(String isLicForLift) {
		this.isLicForLift = isLicForLift;
	}
	/**
	 * 起重设备证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforlift")
	public Date getLicStartDateForLift() {
		return licStartDateForLift;
	}

	public void setLicStartDateForLift(Date licStartDateForLift) {
		this.licStartDateForLift = licStartDateForLift;
	}
	/**
	 * 起重设备证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforlift")
	public Date getLicEndDateForLift() {
		return licEndDateForLift;
	}

	public void setLicEndDateForLift(Date licEndDateForLift) {
		this.licEndDateForLift = licEndDateForLift;
	}
	/**
	 * 是否有适装证书
	 * @return
	 */
	@Column(name = "islicforfitness")
	public String getIsLicForFitness() {
		return isLicForFitness;
	}

	public void setIsLicForFitness(String isLicForFitness) {
		this.isLicForFitness = isLicForFitness;
	}
	/**
	 * 适装证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforfitness")
	public Date getLicStartDateForFitness() {
		return licStartDateForFitness;
	}

	public void setLicStartDateForFitness(Date licStartDateForFitness) {
		this.licStartDateForFitness = licStartDateForFitness;
	}
	/**
	 * 适装证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforfitness")
	public Date getLicEndDateForFitness() {
		return licEndDateForFitness;
	}

	public void setLicEndDateForFitness(Date licEndDateForFitness) {
		this.licEndDateForFitness = licEndDateForFitness;
	}
	/**
	 * 是否有国际防止油污证书
	 * @return
	 */
	@Column(name = "islicforiopp")
	public String getIsLicForIOPP() {
		return isLicForIOPP;
	}

	public void setIsLicForIOPP(String isLicForIOPP) {
		this.isLicForIOPP = isLicForIOPP;
	}
	/**
	 * 国际防止污染证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforiopp")
	public Date getLicStartDateForIOPP() {
		return licStartDateForIOPP;
	}

	public void setLicStartDateForIOPP(Date licStartDateForIOPP) {
		this.licStartDateForIOPP = licStartDateForIOPP;
	}
	/**
	 * 国际防止污染证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforiopp")
	public Date getLicEndDateForIOPP() {
		return licEndDateForIOPP;
	}

	public void setLicEndDateForIOPP(Date licEndDateForIOPP) {
		this.licEndDateForIOPP = licEndDateForIOPP;
	}
	/**
	 * 是否有船舶航行安全证书
	 * @return
	 */
	@Column(name = "islicfornavigation")
	public String getIsLicForNavigation() {
		return isLicForNavigation;
	}

	public void setIsLicForNavigation(String isLicForNavigation) {
		this.isLicForNavigation = isLicForNavigation;
	}
	/**
	 * 船舶航行安全证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdatefornavigation")
	public Date getLicStartDateForNavigation() {
		return licStartDateForNavigation;
	}

	public void setLicStartDateForNavigation(Date licStartDateForNavigation) {
		this.licStartDateForNavigation = licStartDateForNavigation;
	}
	/**
	 * 船舶航行安全证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddatefornavigation")
	public Date getLicEndDateForNavigation() {
		return licEndDateForNavigation;
	}

	public void setLicEndDateForNavigation(Date licEndDateForNavigation) {
		this.licEndDateForNavigation = licEndDateForNavigation;
	}
	/**
	 * 是否有船舶安全管理证书
	 * @return
	 */
	@Column(name = "islicforsmc")
	public String getIsLicForSMC() {
		return isLicForSMC;
	}

	public void setIsLicForSMC(String isLicForSMC) {
		this.isLicForSMC = isLicForSMC;
	}
	/**
	 * 船舶安全管理证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforsmc")
	public Date getLicStartDateForSMC() {
		return licStartDateForSMC;
	}

	public void setLicStartDateForSMC(Date licStartDateForSMC) {
		this.licStartDateForSMC = licStartDateForSMC;
	}
	/**
	 * 船舶安全管理证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforsmc")
	public Date getLicEndDateForSMC() {
		return licEndDateForSMC;
	}

	public void setLicEndDateForSMC(Date licEndDateForSMC) {
		this.licEndDateForSMC = licEndDateForSMC;
	}
	/**
	 * 是否有船舶符合证明
	 * @return
	 */
	@Column(name = "islicforconform")
	public String getIsLicForConform() {
		return isLicForConform;
	}

	public void setIsLicForConform(String isLicForConform) {
		this.isLicForConform = isLicForConform;
	}
	/**
	 * 船舶符合证明—发证日期
	 * @return
	 */
	@Column(name = "licstartdateforconform")
	public Date getLicStartDateForConform() {
		return licStartDateForConform;
	}

	public void setLicStartDateForConform(Date licStartDateForConform) {
		this.licStartDateForConform = licStartDateForConform;
	}
	/**
	 * 船舶符合证明—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateforconform")
	public Date getLicEndDateForConform() {
		return licEndDateForConform;
	}

	public void setLicEndDateForConform(Date licEndDateForConform) {
		this.licEndDateForConform = licEndDateForConform;
	}
	/**
	 * 是否有船舶最低安全配员证书
	 * @return
	 */
	@Column(name = "islicformsm")
	public String getIsLicForMSM() {
		return isLicForMSM;
	}

	public void setIsLicForMSM(String isLicForMSM) {
		this.isLicForMSM = isLicForMSM;
	}
	/**
	 * 船舶最低安全配员证书—发证日期
	 * @return
	 */
	@Column(name = "licstartdateformsm")
	public Date getLicStartDateForMSM() {
		return licStartDateForMSM;
	}

	public void setLicStartDateForMSM(Date licStartDateForMSM) {
		this.licStartDateForMSM = licStartDateForMSM;
	}
	/**
	 * 船舶最低安全配员证书—证书终止日期
	 * @return
	 */
	@Column(name = "licenddateformsm")
	public Date getLicEndDateForMSM() {
		return licEndDateForMSM;
	}

	public void setLicEndDateForMSM(Date licEndDateForMSM) {
		this.licEndDateForMSM = licEndDateForMSM;
	}
	/**
	 * 建造船坞地址
	 * @return
	 */
	@Column(name = "makedockaddress")
	public String getMakeDockAddress() {
		return makeDockAddress;
	}

	public void setMakeDockAddress(String makeDockAddress) {
		this.makeDockAddress = makeDockAddress;
	}
	/**
	 * 建造人的船厂、船坞范围内建造的船壳和机器—保险项目
	 * @return
	 */
	@Column(name = "projectforbuilder")
	public String getProjectForBuilder() {
		return projectForBuilder;
	}

	public void setProjectForBuilder(String projectForBuilder) {
		this.projectForBuilder = projectForBuilder;
	}
	/**
	 * 建造人的船厂、船坞范围内建造的船壳和机器—合同或船坞编号
	 * @return
	 */
	@Column(name = "constractnoforbuilder")
	public String getConstractNoForBuilder() {
		return constractNoForBuilder;
	}

	public void setConstractNoForBuilder(String constractNoForBuilder) {
		this.constractNoForBuilder = constractNoForBuilder;
	}
	/**
	 * 建造人的船厂、船坞范围内建造的船壳和机器—保险金额
	 * @return
	 */
	@Column(name = "amountforbuilder")
	public String getAmountForBuilder() {
		return amountForBuilder;
	}

	public void setAmountForBuilder(String amountForBuilder) {
		this.amountForBuilder = amountForBuilder;
	}
	/**
	 * 建造人的船厂、船坞范围内建造的船壳和机器—建造地点
	 * @return
	 */
	@Column(name = "addressforbuilder")
	public String getAddressForBuilder() {
		return addressForBuilder;
	}

	public void setAddressForBuilder(String addressForBuilder) {
		this.addressForBuilder = addressForBuilder;
	}
	/**
	 * 由分承包人建造的被保险船壳和机器—保险项目名称
	 * @return
	 */
	@Column(name = "projectforsub")
	public String getProjectForSub() {
		return projectForSub;
	}

	public void setProjectForSub(String projectForSub) {
		this.projectForSub = projectForSub;
	}
	/**
	 * 由分承包人建造的被保险船壳和机器—合同或船坞编号
	 * @return
	 */
	@Column(name = "constractnoforsub")
	public String getConstractNoForSub() {
		return constractNoForSub;
	}

	public void setConstractNoForSub(String constractNoForSub) {
		this.constractNoForSub = constractNoForSub;
	}
	/**
	 * 由分承包人建造的被保险船壳和机器—建造地点
	 * @return
	 */
	@Column(name = "addressforsub")
	public String getAddressForSub() {
		return addressForSub;
	}

	public void setAddressForSub(String addressForSub) {
		this.addressForSub = addressForSub;
	}
	/**
	 * 建造人的建造能力及历史记录
	 * @return
	 */
	@Column(name = "historyforbuilder")
	public String getHistoryForBuilder() {
		return historyForBuilder;
	}

	public void setHistoryForBuilder(String historyForBuilder) {
		this.historyForBuilder = historyForBuilder;
	}
	/**
	 * 建成价格/合同最后价格
	 * @return
	 */
	@Column(name = "lastprice")
	public String getLastPrice() {
		return lastPrice;
	}

	public void setLastPrice(String lastPrice) {
		this.lastPrice = lastPrice;
	}
	/**
	 * 交船地点
	 * @return
	 */
	@Column(name = "deliveryplace")
	public String getDeliveryPlace() {
		return deliveryPlace;
	}

	public void setDeliveryPlace(String deliveryPlace) {
		this.deliveryPlace = deliveryPlace;
	}
	/**
	 * 上船台日期
	 * @return
	 */
	@Column(name = "stagedate")
	public Date getStageDate() {
		return stageDate;
	}

	public void setStageDate(Date stageDate) {
		this.stageDate = stageDate;
	}
	/**
	 * 下水日期
	 * @return
	 */
	@Column(name = "waterdate")
	public Date getWaterDate() {
		return waterDate;
	}

	public void setWaterDate(Date waterDate) {
		this.waterDate = waterDate;
	}
	/**
	 * 试航日期
	 * @return
	 */
	@Column(name = "saildate")
	public Date getSailDate() {
		return sailDate;
	}

	public void setSailDate(Date sailDate) {
		this.sailDate = sailDate;
	}
	/**
	 * 交船日期
	 * @return
	 */
	@Column(name = "deliverydate")
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}
	/**
	 * 建造合同中被保险人的身份
	 * @return
	 */
	@Column(name = "insuredstatus")
	public String getInsuredStatus() {
		return insuredStatus;
	}

	public void setInsuredStatus(String insuredStatus) {
		this.insuredStatus = insuredStatus;
	}
	/**
	 * 实际船东
	 * @return
	 */
	@Column(name = "actualshipowner")
	public String getActualShipOwner() {
		return actualShipOwner;
	}

	public void setActualShipOwner(String actualShipOwner) {
		this.actualShipOwner = actualShipOwner;
	}
	/**
	 * 装载类型
	 * @return
	 */
	@Column(name = "loadtype")
	public String getLoadType() {
		return loadType;
	}

	public void setLoadType(String loadType) {
		this.loadType = loadType;
	}
	/**
	 * 装载方式
	 * @return
	 */
	@Column(name = "loadstyle")
	public String getLoadStyle() {
		return loadStyle;
	}

	public void setLoadStyle(String loadStyle) {
		this.loadStyle = loadStyle;
	}
	/**
	 * 动工日期
	 * @return
	 */
	@Column(name = "begindate")
	public Date getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}
	/**
	 * 船舶登记所有人
	 * @return
	 */
	@Column(name = "shipregisterowner")
	public String getShipRegisterOwner() {
		return shipRegisterOwner;
	}

	public void setShipRegisterOwner(String shipRegisterOwner) {
		this.shipRegisterOwner = shipRegisterOwner;
	}
	/**
	 * 船舶所有人主要营业地
	 * @return
	 */
	@Column(name = "shipregisterplace")
	public String getShipRegisterPlace() {
		return shipRegisterPlace;
	}

	public void setShipRegisterPlace(String shipRegisterPlace) {
		this.shipRegisterPlace = shipRegisterPlace;
	}
	/**
	 * 新船合同价
	 * @return
	 */
	@Column(name = "newcontractprice")
	public String getNewContractPrice() {
		return newContractPrice;
	}

	public void setNewContractPrice(String newContractPrice) {
		this.newContractPrice = newContractPrice;
	}
		
}
