package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrpPfee generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppfee")
public class PrpPfee implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 币别 */
	private PrpPfeeId id;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 保额变化量 */
	private BigDecimal chgAmount;
	/** 保费变化量 */
	private BigDecimal chgPremium;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;
	/** 总税额 */
   	private BigDecimal sumTaxFee;
   	/** 总净保费 */
   	private BigDecimal sumNetPremium;
	/** 总税额变化量 */
   	private BigDecimal chgTaxFee;
   	/** 总净保费变化量 */
   	private BigDecimal chgNetPremium;
   	/** 总税额变化量 */
   	private BigDecimal chgTaxFee_gb;
   	/** 总联方税额变化量 */
   	private BigDecimal chgTaxFee_lb;
   	/** 预收保费税额变化量*/
   	private BigDecimal chgTaxFee_ys;
	public PrpPfee() {
	}

	/**       
	 * 币别
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "currency", column = @Column(name = "currency", nullable = false)) })
	public PrpPfeeId getId() {
		return this.id;
	}

	public void setId(PrpPfeeId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 保额变化量
	 */

	@Column(name = "chgamount")
	public BigDecimal getChgAmount() {
		return this.chgAmount;
	}

	public void setChgAmount(BigDecimal chgAmount) {
		this.chgAmount = chgAmount;
	}

	/**       
	 * 保费变化量
	 */

	@Column(name = "chgpremium")
	public BigDecimal getChgPremium() {
		return this.chgPremium;
	}

	public void setChgPremium(BigDecimal chgPremium) {
		this.chgPremium = chgPremium;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
	
	/**     
	 * 总税额
	 */
	
	public BigDecimal getSumTaxFee() {
		return sumTaxFee;
	}

	public void setSumTaxFee(BigDecimal sumTaxFee) {
		this.sumTaxFee = sumTaxFee;
	}
	
	/**       
	 * 总净保费
	 */
	
	public BigDecimal getSumNetPremium() {
		return sumNetPremium;
	}

	public void setSumNetPremium(BigDecimal sumNetPremium) {
		this.sumNetPremium = sumNetPremium;
	}

	/**       
	 * 总税额变化量
	 */
	
	public BigDecimal getChgTaxFee() {
		return chgTaxFee;
	}

	public void setChgTaxFee(BigDecimal chgTaxFee) {
		this.chgTaxFee = chgTaxFee;
	}
    
	/**       
	 * 总净保费变化量
	 */
	
	public BigDecimal getChgNetPremium() {
		return chgNetPremium;
	}

	public void setChgNetPremium(BigDecimal chgNetPremium) {
		this.chgNetPremium = chgNetPremium;
	}


   	
	/**       
	 * 总共方税额变化量
	 */
	
	@Column(name = "chgTaxFee_gb")
	public BigDecimal getChgTaxFee_gb() {
		return chgTaxFee_gb;
	}

	public void setChgTaxFee_gb(BigDecimal chgTaxFee_gb) {
		this.chgTaxFee_gb = chgTaxFee_gb;
	}
	/**       
	 * 总联方税额变化量
	 */
	
	@Column(name = "chgTaxFee_lb")
	public BigDecimal getChgTaxFee_lb() {
		return chgTaxFee_lb;
	}

	public void setChgTaxFee_lb(BigDecimal chgTaxFee_lb) {
		this.chgTaxFee_lb = chgTaxFee_lb;
	}
	
	@Column(name = "chgTaxFee_ys")
	public BigDecimal getChgTaxFee_ys() {
		return chgTaxFee_ys;
	}

	public void setChgTaxFee_ys(BigDecimal chgTaxFee_ys) {
		this.chgTaxFee_ys = chgTaxFee_ys;
	}
	
	
}
