package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpPitemTravelAgency generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppitem_travelagency")
public class PrpPitemTravelAgency implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 标的序号 */
	private PrpPitemTravelAgencyId id;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 许可证号 */
	private String licenceNo;
	/** 标的库序号 */
	private Integer ditemno;
	/** 业务年度 */
	private String uwYear;
	/** 旅行社中文名称 */
	private String agencyCName;
	/** 旅行社英文名称 */
	private String agencyEName;
	/** 旅行社种类▲ */
	private String agencyType;
	/** 地址 */
	private String addressName;
	/** 邮编 */
	private String postCode;
	/** 有无出境游经营资格 */
	private String businessDetail;
	/** 旅游接待人天数 */
	private Integer quantity;
	/** 上年度营业收入 */
	private String preTurnOver;
	/** (UwYear – 1)年度保费 */
	private BigDecimal prePremium1;
	/** (UwYear – 1)年度赔款金额 */
	private BigDecimal preSumPaid1;
	/** (UwYear – 2)年度保费 */
	private BigDecimal prePremium2;
	/** (UwYear – 2)年度赔款金额 */
	private BigDecimal preSumPaid2;
	/** (UwYear – 3)年度赔款金额 */
	private BigDecimal prePremium3;
	/** (UwYear – 3)年度赔款金额 */
	private BigDecimal preSumPaid3;
	/** 生效标志 */
	private String validStatus;
	/** 备注 */
	private String remark;
	/** 标志字段 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpPitemTravelAgency() {
	}

	/**       
	 * 标的序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "itemno", nullable = false)) })
	public PrpPitemTravelAgencyId getId() {
		return this.id;
	}

	public void setId(PrpPitemTravelAgencyId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 许可证号
	 */

	@Column(name = "licenceno", nullable = false)
	public String getLicenceNo() {
		return this.licenceNo;
	}

	public void setLicenceNo(String licenceNo) {
		this.licenceNo = licenceNo;
	}

	/**       
	 * 业务年度
	 */

	@Column(name = "uwYear", nullable = false)
	public String getUwYear() {
		return this.uwYear;
	}

	public void setUwYear(String uwYear) {
		this.uwYear = uwYear;
	}

	/**       
	 * 旅行社中文名称
	 */

	@Column(name = "agencycname")
	public String getAgencyCName() {
		return this.agencyCName;
	}

	public void setAgencyCName(String agencyCName) {
		this.agencyCName = agencyCName;
	}

	/**       
	 * 旅行社英文名称
	 */

	@Column(name = "agencyename")
	public String getAgencyEName() {
		return this.agencyEName;
	}

	public void setAgencyEName(String agencyEName) {
		this.agencyEName = agencyEName;
	}

	/**       
	 * 旅行社种类▲
	 */

	@Column(name = "agencytype")
	public String getAgencyType() {
		return this.agencyType;
	}

	public void setAgencyType(String agencyType) {
		this.agencyType = agencyType;
	}

	/**       
	 * 地址
	 */

	@Column(name = "addressname")
	public String getAddressName() {
		return this.addressName;
	}

	public void setAddressName(String addressName) {
		this.addressName = addressName;
	}

	/**       
	 * 邮编
	 */

	@Column(name = "postcode")
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**       
	 * 有无出境游经营资格
	 */

	@Column(name = "businessdetail")
	public String getBusinessDetail() {
		return this.businessDetail;
	}

	public void setBusinessDetail(String businessDetail) {
		this.businessDetail = businessDetail;
	}

	/**       
	 * 旅游接待人天数
	 */

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**       
	 * 上年度营业收入
	 */

	@Column(name = "preturnover")
	public String getPreTurnOver() {
		return this.preTurnOver;
	}

	public void setPreTurnOver(String preTurnOver) {
		this.preTurnOver = preTurnOver;
	}

	/**       
	 * (UwYear – 1)年度保费 
	 */

	@Column(name = "prepremium1")
	public BigDecimal getPrePremium1() {
		return this.prePremium1;
	}

	public void setPrePremium1(BigDecimal prePremium1) {
		this.prePremium1 = prePremium1;
	}

	/**       
	 * (UwYear – 1)年度赔款金额
	 */

	@Column(name = "presumpaid1")
	public BigDecimal getPreSumPaid1() {
		return this.preSumPaid1;
	}

	public void setPreSumPaid1(BigDecimal preSumPaid1) {
		this.preSumPaid1 = preSumPaid1;
	}

	/**       
	 * (UwYear – 2)年度保费 
	 */

	@Column(name = "prepremium2")
	public BigDecimal getPrepremium2() {
		return this.prePremium2;
	}

	public void setPrepremium2(BigDecimal prePremium2) {
		this.prePremium2 = prePremium2;
	}

	/**       
	 *(UwYear – 2)年度赔款金额
	 */

	@Column(name = "presumpaid2")
	public BigDecimal getPreSumPaid2() {
		return this.preSumPaid2;
	}

	public void setPreSumPaid2(BigDecimal preSumPaid2) {
		this.preSumPaid2 = preSumPaid2;
	}

	/**       
	 * (UwYear – 3)年度保费 
	 */

	@Column(name = "prepremium3")
	public BigDecimal getPrepremium3() {
		return this.prePremium3;
	}

	public void setPrepremium3(BigDecimal prePremium3) {
		this.prePremium3 = prePremium3;
	}

	/**       
	 * (UwYear – 3)年度赔款金额
	 */
	
	@Column(name = "presumpaid3")
	public BigDecimal getPreSumPaid3() {
		return this.preSumPaid3;
	}

	public void setPreSumPaid3(BigDecimal preSumPaid3) {
		this.preSumPaid3 = preSumPaid3;
	}

	/**       
	 * 有效性
	 */

	@Column(name = "validstatus")
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 标志字段
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}


	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
	/**
	 * 标的库序号
	 * @return
	 */
	@Column(name = "ditemno")
	public Integer getDitemno() {
		return this.ditemno;
	}

	public void setDitemno(Integer ditemno) {
		this.ditemno = ditemno;
	}

}
