package com.sinosoft.fccb.policy.common.model;

// Generated 2010-5-24 11:46:52 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpPhead generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpphead")
public class PrpPhead implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 批单申请号 */
	private String applyNo;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险类代码 */
	private String classCode;
	/** 险种代码 */
	private String riskCode;
	/** 批改次序 */
	private Integer endorseTimes;
	/** 出单机构 */
	private String makeCom;
	/** 赔款计算书号 */
	private String compensateNo;
	/** 关系人代码 */
	private String insuredCode;
	/** InsuredName */
	private String insuredName;
	/** 语种 */
	private String language;
	/** 保单类型 */
	private String policyType;
	/** 批改原因代码  */
	private String reasonCode;
	/** 批改原因备注  */
	private String reasonText;
	/** 批改类型 */
	private String endorType;
	/** 批改日期 */
	private Date endorDate;
	/** 生效日期 */
	private Date validDate;
	/** 生效小时 */
	private Integer validHour;
	/** 经办人代码 */
	private String handlerCode;
	/** 归属人 */
	private String handler1Code;
	/** 复核人代码 */
	private String approverCode;
	/** 初审标志 */
	private String checkFlag;
	/** 初审员 */
	private String checkUpCode;
	/** 初审意见 */
	private String checkOpinion;
	/** 最终核保人代码 */
	private String underWriteCode;
	/** 最终核保人名称 */
	private String underWriteName;
	/** 操作员代码 */
	private String operatorCode;
	/** 报表数据生成日期 */
	private Date inputTime;
	/** 归属机构 */
	private String comCode;
	/** 代理人代码 */
	private String agentCode;
	/** 保单统计年月 */
	private Date statisticsYM;
	/** 核保完成日期 */
	private Date underWriteEndDate;
	/** 核保标志 */
	private String underWriteFlag;
	/** 见费出单标志 */
	private String jfeeFlag;
	/** 是否迁移数据 */
	private String dmFlag;
	/**是否倒批标志*/
	private String inputFlag;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;
	private List<PrpPstampTax> prpPstampTaxes = new ArrayList<PrpPstampTax>(0);
	private List<PrpPmainCargo> prpPmainCargos = new ArrayList<PrpPmainCargo>(0);
	private List<PrpPitemDevice> prpPitemDevices = new ArrayList<PrpPitemDevice>(
			0);
	private List<PrpPitem> prpPitems = new ArrayList<PrpPitem>(0);
	private List<PrpPspecialFac> prpPspecialFacs = new ArrayList<PrpPspecialFac>(
			0);
	private List<PrpPcoinsDetail> prpPcoinsDetails = new ArrayList<PrpPcoinsDetail>(
			0);
	private List<PrpPinsuredIdvList> prpPinsuredIdvLists = new ArrayList<PrpPinsuredIdvList>(
			0);
	private List<PrpPinsuredIdvListNature> prpPinsuredIdvListNatures = new ArrayList<PrpPinsuredIdvListNature>(0);
	private List<PrpPcarDevice> prpPcarDevices = new ArrayList<PrpPcarDevice>(0);
	private List<PrpPitemCargo> prpPitemCargos = new ArrayList<PrpPitemCargo>(0);
	private List<PrpPagentDetail> prpPagentDetails = new ArrayList<PrpPagentDetail>(
			0);
	private List<PrpPshipDriver> prpPshipDrivers = new ArrayList<PrpPshipDriver>(
			0);
	private List<PrpPbatch> prpPbatchs = new ArrayList<PrpPbatch>(0);
	private List<PrpPdeduction> prpPdeductions = new ArrayList<PrpPdeduction>(0);
	private List<PrpPitemShip> prpPitemShips = new ArrayList<PrpPitemShip>(0);
	private List<PrpPcoins> prpPcoinses = new ArrayList<PrpPcoins>(0);
	private List<PrpPguaranty> prpPguaranties = new ArrayList<PrpPguaranty>(0);
	private List<PrpPitemPlane> prpPitemPlanes = new ArrayList<PrpPitemPlane>(0);
	private List<PrpPmainAirLine> prpPmainAirLines = new ArrayList<PrpPmainAirLine>(
			0);
	private List<PrpPmainLiab> prpPmainLiabs = new ArrayList<PrpPmainLiab>(0);
	private List<PrpPpayeeAccount> prpPpayeeAccounts = new ArrayList<PrpPpayeeAccount>(
			0);
	private List<PrpPfee> prpPfees = new ArrayList<PrpPfee>(0);
	private List<PrpPcarShipTax> prpPcarShipTaxes = new ArrayList<PrpPcarShipTax>(
			0);
	private List<PrpPcommission> prpPcommissions = new ArrayList<PrpPcommission>(
			0);
	private List<PrpPproject> prpPprojects = new ArrayList<PrpPproject>(0);
	private List<PrpPmainCar> prpPmainCars = new ArrayList<PrpPmainCar>(0);
	private List<PrpPitemHouse> prpPitemHouses = new ArrayList<PrpPitemHouse>(0);
	private List<PrpPitemAgri> prpPitemAgris = new ArrayList<PrpPitemAgri>(0);
	private List<PrpPitemTravelAgency> prpPitemTravelAgencys = new ArrayList<PrpPitemTravelAgency>(0);
	private List<PrpPitemAnimal> prpPitemAnimals = new ArrayList<PrpPitemAnimal>(0);
	private List<PrpPprofitFactor> prpPprofitFactors = new ArrayList<PrpPprofitFactor>(
			0);
	private List<PrpPplan> prpPplans = new ArrayList<PrpPplan>(0);
	private List<PrpPmainCredit> prpPmainCredits = new ArrayList<PrpPmainCredit>(
			0);
	private List<PrpPhandler> prpPhandlers = new ArrayList<PrpPhandler>(0);
	private List<PrpPmainInvest> prpPmainInvests = new ArrayList<PrpPmainInvest>(
			0);
	private List<PrpPitemOil> prpPitemOils = new ArrayList<PrpPitemOil>(0);
	private List<PrpPration> prpPrations = new ArrayList<PrpPration>(0);
	private List<PrpPmainAgri> prpPmainAgris = new ArrayList<PrpPmainAgri>(0);
	private List<PrpPname> prpPnames = new ArrayList<PrpPname>(0);
	private List<PrpPagent> prpPagents = new ArrayList<PrpPagent>(0);
	private List<PrpPitemCar> prpPitemCars = new ArrayList<PrpPitemCar>(0);
	private List<PrpPinsured> prpPinsureds = new ArrayList<PrpPinsured>(0);
	private List<PrpPitemProp> prpPitemProps = new ArrayList<PrpPitemProp>(0);
	private List<PrpPinsuredNature> prpPinsuredNatures = new ArrayList<PrpPinsuredNature>(
			0);
	private List<PrpPitemKind> prpPitemKinds = new ArrayList<PrpPitemKind>(0);
	private List<PrpPitemKindDetail> prpPitemKindDetails = new ArrayList<PrpPitemKindDetail>(0);
	
	private List<PrpPmain> prpPmains = new ArrayList<PrpPmain>(0);
	private List<PrpPcoeff> prpPcoeffs = new ArrayList<PrpPcoeff>(0);
	private List<PrpPengage> prpPengages = new ArrayList<PrpPengage>(0);
	private List<PrpPitemCarExt> prpPitemCarExts = new ArrayList<PrpPitemCarExt>(
			0);
	private List<PrpPmainConstruct> prpPmainConstructs = new ArrayList<PrpPmainConstruct>(
			0);
	private List<PrpPmainLoan> prpPmainLoans = new ArrayList<PrpPmainLoan>(0);
	private List<PrpPinsuredArtif> prpPinsuredArtifs = new ArrayList<PrpPinsuredArtif>(
			0);
	private List<PrpPlimit> prpPlimits = new ArrayList<PrpPlimit>(0);
	private List<PrpPaddress> prpPaddresses = new ArrayList<PrpPaddress>(0);
	private List<PrpPmainProp> prpPmainProps = new ArrayList<PrpPmainProp>(0);
	private List<PrpPextendInfo> prpPextendInfos = new ArrayList<PrpPextendInfo>(
			0);
	private List<PrpPcontractPause> prpPcontractPauses = new ArrayList<PrpPcontractPause>(
			0);
	private List<PrpPtext> prpPtexts = new ArrayList<PrpPtext>(0);
	private List<PrpPcargoDetail> prpPcargoDetails = new ArrayList<PrpPcargoDetail>(0);

	private List<PrpPcommissionDetail> prpPcommissionDetails = new ArrayList<PrpPcommissionDetail>(0);

	private List<PrpPitemAgriRelated> prpPitemAgriRelateds = new ArrayList<PrpPitemAgriRelated>(0);

	private List<PrpPclause> prpPclauses = new ArrayList<PrpPclause>(0);
	//BUG26027 添加保单贡献对应P表 add by liangjianze 20120327 start
	private List<PrpPcontriution> prpPcontriutions =new ArrayList<PrpPcontriution>(0);
	//BUG26027 添加保单贡献对应P表 add by liangjianze 20120327 end
	//车贷其他信息P表添加
	private List<PrpPitemCreditOth> prpPitemCreditOths = new ArrayList<PrpPitemCreditOth>(0);
	private List<PrpPinsuredCreditInvest> prpPinsuredCreditInvests = new ArrayList<PrpPinsuredCreditInvest>(0);
	//RZHANGT2012081301 重要客户 add by liangjianze 20120906
	private List<PrpPmainCommon> prpPmainCommons = new ArrayList<PrpPmainCommon>(0);
	//RZHANGT2012121201  能翻母猪标的库后续调整 add by liusaisai 20130109 
	private List<PrpPanimal> prpPanimals = new ArrayList<PrpPanimal>(0);
	//RLIUBIN2013091601 LXK浙江省农业保险共保体组合产品保费计算
	private List<PrpPclauseplan> prpPclauseplans = new ArrayList<PrpPclauseplan>(0);
	//itemkind附表
	private List<PrpPitemKindTaxFee> prpPitemKindTaxFees = new ArrayList<PrpPitemKindTaxFee>(0);
	
	
	public PrpPhead() {
	}

	/**       
	 * 批单申请号
	 */
	@Id
	@Column(name = "applyno", unique = true, nullable = false)
	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险类代码
	 */

	@Column(name = "classcode")
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode")
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 批改次序
	 */

	@Column(name = "endorsetimes")
	public Integer getEndorseTimes() {
		return this.endorseTimes;
	}

	public void setEndorseTimes(Integer endorseTimes) {
		this.endorseTimes = endorseTimes;
	}

	/**       
	 * 出单机构
	 */

	@Column(name = "makecom")
	public String getMakeCom() {
		return this.makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	/**       
	 * 赔款计算书号
	 */

	@Column(name = "compensateno")
	public String getCompensateNo() {
		return this.compensateNo;
	}

	public void setCompensateNo(String compensateNo) {
		this.compensateNo = compensateNo;
	}

	/**       
	 * 关系人代码
	 */

	@Column(name = "insuredcode")
	public String getInsuredCode() {
		return this.insuredCode;
	}

	public void setInsuredCode(String insuredCode) {
		this.insuredCode = insuredCode;
	}

	/**       
	 * InsuredName
	 */

	@Column(name = "insuredname")
	public String getInsuredName() {
		return this.insuredName;
	}

	public void setInsuredName(String insuredName) {
		this.insuredName = insuredName;
	}

	/**       
	 * 语种
	 */

	@Column(name = "language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	/**       
	 * 保单类型
	 */

	@Column(name = "policytype")
	public String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}
	
	/**       
	 * 批改原因代码
	 */

	@Column(name = "reasoncode")
	public String getReasonCode() {
		return reasonCode;
	}

	public void setReasonCode(String reasonCode) {
		this.reasonCode = reasonCode;
	}
	
	/**       
	 * 批改原因备注
	 */

	@Column(name = "reasontext")
	public String getReasonText() {
		return reasonText;
	}

	public void setReasonText(String reasonText) {
		this.reasonText = reasonText;
	}

	/**       
	 * 批改类型
	 */

	@Column(name = "endortype")
	public String getEndorType() {
		return this.endorType;
	}

	public void setEndorType(String endorType) {
		this.endorType = endorType;
	}

	/**       
	 * 批改日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "endordate")
	public Date getEndorDate() {
		return this.endorDate;
	}

	public void setEndorDate(Date endorDate) {
		this.endorDate = endorDate;
	}

	/**       
	 * 生效日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "validdate")
	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	/**       
	 * 生效小时
	 */

	@Column(name = "validhour")
	public Integer getValidHour() {
		return this.validHour;
	}

	public void setValidHour(Integer validHour) {
		this.validHour = validHour;
	}

	/**       
	 * 经办人代码
	 */

	@Column(name = "handlercode")
	public String getHandlerCode() {
		return this.handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	/**       
	 * 归属人
	 */

	@Column(name = "handler1code")
	public String getHandler1Code() {
		return this.handler1Code;
	}

	public void setHandler1Code(String handler1Code) {
		this.handler1Code = handler1Code;
	}

	/**       
	 * 复核人代码
	 */

	@Column(name = "approvercode")
	public String getApproverCode() {
		return this.approverCode;
	}

	public void setApproverCode(String approverCode) {
		this.approverCode = approverCode;
	}

	/**       
	 * 初审标志
	 */

	@Column(name = "checkflag")
	public String getCheckFlag() {
		return this.checkFlag;
	}

	public void setCheckFlag(String checkFlag) {
		this.checkFlag = checkFlag;
	}

	/**       
	 * 初审员
	 */

	@Column(name = "checkupcode")
	public String getCheckUpCode() {
		return this.checkUpCode;
	}

	public void setCheckUpCode(String checkUpCode) {
		this.checkUpCode = checkUpCode;
	}

	/**       
	 * 初审意见
	 */

	@Column(name = "checkopinion")
	public String getCheckOpinion() {
		return this.checkOpinion;
	}

	public void setCheckOpinion(String checkOpinion) {
		this.checkOpinion = checkOpinion;
	}

	/**       
	 * 最终核保人代码
	 */

	@Column(name = "underwritecode")
	public String getUnderWriteCode() {
		return this.underWriteCode;
	}

	public void setUnderWriteCode(String underWriteCode) {
		this.underWriteCode = underWriteCode;
	}

	/**       
	 * 最终核保人名称
	 */

	@Column(name = "underwritename")
	public String getUnderWriteName() {
		return this.underWriteName;
	}

	public void setUnderWriteName(String underWriteName) {
		this.underWriteName = underWriteName;
	}

	/**       
	 * 操作员代码
	 */

	@Column(name = "operatorcode")
	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	/**       
	 * 报表数据生成日期
	 */

	@Column(name = "inputtime")
	public Date getInputTime() {
		return this.inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	/**       
	 * 归属机构
	 */

	@Column(name = "comcode")
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	/**       
	 * 代理人代码
	 */

	@Column(name = "agentcode")
	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	/**       
	 * 保单统计年月
	 */

	@Column(name = "statisticsym")
	public Date getStatisticsYM() {
		return this.statisticsYM;
	}

	public void setStatisticsYM(Date statisticsYM) {
		this.statisticsYM = statisticsYM;
	}

	/**       
	 * 核保完成日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "underwriteenddate")
	public Date getUnderWriteEndDate() {
		return this.underWriteEndDate;
	}

	public void setUnderWriteEndDate(Date underWriteEndDate) {
		this.underWriteEndDate = underWriteEndDate;
	}

	/**       
	 * 核保标志
	 */

	@Column(name = "underwriteflag")
	public String getUnderWriteFlag() {
		return this.underWriteFlag;
	}

	public void setUnderWriteFlag(String underWriteFlag) {
		this.underWriteFlag = underWriteFlag;
	}

	/**       
	 * 见费出单标志
	 */

	@Column(name = "jfeeflag")
	public String getJfeeFlag() {
		return this.jfeeFlag;
	}

	public void setJfeeFlag(String jfeeFlag) {
		this.jfeeFlag = jfeeFlag;
	}

	/**       
	 * 是否迁移数据
	 */

	@Column(name = "dmflag")
	public String getDmFlag() {
		return this.dmFlag;
	}

	public void setDmFlag(String dmFlag) {
		this.dmFlag = dmFlag;
	}
	/**       
	 * 是否倒批标志
	 */
	@Column(name = "inputFlag")
	public String getInputFlag() {
		return this.inputFlag;
	}

	public void setInputFlag(String inputFlag) {
		this.inputFlag = inputFlag;
	}
	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPstampTax> getPrpPstampTaxes() {
		return this.prpPstampTaxes;
	}

	public void setPrpPstampTaxes(List<PrpPstampTax> prpPstampTaxes) {
		this.prpPstampTaxes = prpPstampTaxes;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainCargo> getPrpPmainCargos() {
		return this.prpPmainCargos;
	}

	public void setPrpPmainCargos(List<PrpPmainCargo> prpPmainCargos) {
		this.prpPmainCargos = prpPmainCargos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemDevice> getPrpPitemDevices() {
		return this.prpPitemDevices;
	}

	public void setPrpPitemDevices(List<PrpPitemDevice> prpPitemDevices) {
		this.prpPitemDevices = prpPitemDevices;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitem> getPrpPitems() {
		return this.prpPitems;
	}

	public void setPrpPitems(List<PrpPitem> prpPitems) {
		this.prpPitems = prpPitems;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPspecialFac> getPrpPspecialFacs() {
		return this.prpPspecialFacs;
	}

	public void setPrpPspecialFacs(List<PrpPspecialFac> prpPspecialFacs) {
		this.prpPspecialFacs = prpPspecialFacs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcoinsDetail> getPrpPcoinsDetails() {
		return this.prpPcoinsDetails;
	}

	public void setPrpPcoinsDetails(List<PrpPcoinsDetail> prpPcoinsDetails) {
		this.prpPcoinsDetails = prpPcoinsDetails;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPinsuredIdvList> getPrpPinsuredIdvLists() {
		return this.prpPinsuredIdvLists;
	}

	public void setPrpPinsuredIdvLists(
			List<PrpPinsuredIdvList> prpPinsuredIdvLists) {
		this.prpPinsuredIdvLists = prpPinsuredIdvLists;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcarDevice> getPrpPcarDevices() {
		return this.prpPcarDevices;
	}

	public void setPrpPcarDevices(List<PrpPcarDevice> prpPcarDevices) {
		this.prpPcarDevices = prpPcarDevices;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemCargo> getPrpPitemCargos() {
		return this.prpPitemCargos;
	}

	public void setPrpPitemCargos(List<PrpPitemCargo> prpPitemCargos) {
		this.prpPitemCargos = prpPitemCargos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPagentDetail> getPrpPagentDetails() {
		return this.prpPagentDetails;
	}

	public void setPrpPagentDetails(List<PrpPagentDetail> prpPagentDetails) {
		this.prpPagentDetails = prpPagentDetails;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPshipDriver> getPrpPshipDrivers() {
		return this.prpPshipDrivers;
	}

	public void setPrpPshipDrivers(List<PrpPshipDriver> prpPshipDrivers) {
		this.prpPshipDrivers = prpPshipDrivers;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPbatch> getPrpPbatchs() {
		return this.prpPbatchs;
	}

	public void setPrpPbatchs(List<PrpPbatch> prpPbatchs) {
		this.prpPbatchs = prpPbatchs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPdeduction> getPrpPdeductions() {
		return this.prpPdeductions;
	}

	public void setPrpPdeductions(List<PrpPdeduction> prpPdeductions) {
		this.prpPdeductions = prpPdeductions;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemShip> getPrpPitemShips() {
		return this.prpPitemShips;
	}

	public void setPrpPitemShips(List<PrpPitemShip> prpPitemShips) {
		this.prpPitemShips = prpPitemShips;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcoins> getPrpPcoinses() {
		return this.prpPcoinses;
	}

	public void setPrpPcoinses(List<PrpPcoins> prpPcoinses) {
		this.prpPcoinses = prpPcoinses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPguaranty> getPrpPguaranties() {
		return this.prpPguaranties;
	}

	public void setPrpPguaranties(List<PrpPguaranty> prpPguaranties) {
		this.prpPguaranties = prpPguaranties;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemPlane> getPrpPitemPlanes() {
		return this.prpPitemPlanes;
	}

	public void setPrpPitemPlanes(List<PrpPitemPlane> prpPitemPlanes) {
		this.prpPitemPlanes = prpPitemPlanes;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainAirLine> getPrpPmainAirLines() {
		return this.prpPmainAirLines;
	}

	public void setPrpPmainAirLines(List<PrpPmainAirLine> prpPmainAirLines) {
		this.prpPmainAirLines = prpPmainAirLines;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainLiab> getPrpPmainLiabs() {
		return this.prpPmainLiabs;
	}

	public void setPrpPmainLiabs(List<PrpPmainLiab> prpPmainLiabs) {
		this.prpPmainLiabs = prpPmainLiabs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPpayeeAccount> getPrpPpayeeAccounts() {
		return this.prpPpayeeAccounts;
	}

	public void setPrpPpayeeAccounts(List<PrpPpayeeAccount> prpPpayeeAccounts) {
		this.prpPpayeeAccounts = prpPpayeeAccounts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPfee> getPrpPfees() {
		return this.prpPfees;
	}

	public void setPrpPfees(List<PrpPfee> prpPfees) {
		this.prpPfees = prpPfees;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcarShipTax> getPrpPcarShipTaxes() {
		return this.prpPcarShipTaxes;
	}

	public void setPrpPcarShipTaxes(List<PrpPcarShipTax> prpPcarShipTaxes) {
		this.prpPcarShipTaxes = prpPcarShipTaxes;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcommission> getPrpPcommissions() {
		return this.prpPcommissions;
	}

	public void setPrpPcommissions(List<PrpPcommission> prpPcommissions) {
		this.prpPcommissions = prpPcommissions;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPproject> getPrpPprojects() {
		return this.prpPprojects;
	}

	public void setPrpPprojects(List<PrpPproject> prpPprojects) {
		this.prpPprojects = prpPprojects;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainCar> getPrpPmainCars() {
		return this.prpPmainCars;
	}

	public void setPrpPmainCars(List<PrpPmainCar> prpPmainCars) {
		this.prpPmainCars = prpPmainCars;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemHouse> getPrpPitemHouses() {
		return this.prpPitemHouses;
	}

	public void setPrpPitemHouses(List<PrpPitemHouse> prpPitemHouses) {
		this.prpPitemHouses = prpPitemHouses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemAgri> getPrpPitemAgris() {
		return this.prpPitemAgris;
	}

	public void setPrpPitemAgris(List<PrpPitemAgri> prpPitemAgris) {
		this.prpPitemAgris = prpPitemAgris;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemTravelAgency> getPrpPitemTravelAgencys() {
		return this.prpPitemTravelAgencys;
	}

	public void setPrpPitemTravelAgencys(List<PrpPitemTravelAgency> prpPitemTravelAgencys) {
		this.prpPitemTravelAgencys = prpPitemTravelAgencys;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemAnimal> getPrpPitemAnimals() {
		return prpPitemAnimals;
	}

	public void setPrpPitemAnimals(List<PrpPitemAnimal> prpPitemAnimals) {
		this.prpPitemAnimals = prpPitemAnimals;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPprofitFactor> getPrpPprofitFactors() {
		return this.prpPprofitFactors;
	}

	public void setPrpPprofitFactors(List<PrpPprofitFactor> prpPprofitFactors) {
		this.prpPprofitFactors = prpPprofitFactors;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPplan> getPrpPplans() {
		return this.prpPplans;
	}

	public void setPrpPplans(List<PrpPplan> prpPplans) {
		this.prpPplans = prpPplans;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainCredit> getPrpPmainCredits() {
		return this.prpPmainCredits;
	}

	public void setPrpPmainCredits(List<PrpPmainCredit> prpPmainCredits) {
		this.prpPmainCredits = prpPmainCredits;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPhandler> getPrpPhandlers() {
		return this.prpPhandlers;
	}

	public void setPrpPhandlers(List<PrpPhandler> prpPhandlers) {
		this.prpPhandlers = prpPhandlers;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainInvest> getPrpPmainInvests() {
		return this.prpPmainInvests;
	}

	public void setPrpPmainInvests(List<PrpPmainInvest> prpPmainInvests) {
		this.prpPmainInvests = prpPmainInvests;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemOil> getPrpPitemOils() {
		return this.prpPitemOils;
	}

	public void setPrpPitemOils(List<PrpPitemOil> prpPitemOils) {
		this.prpPitemOils = prpPitemOils;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPration> getPrpPrations() {
		return this.prpPrations;
	}

	public void setPrpPrations(List<PrpPration> prpPrations) {
		this.prpPrations = prpPrations;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainAgri> getPrpPmainAgris() {
		return this.prpPmainAgris;
	}

	public void setPrpPmainAgris(List<PrpPmainAgri> prpPmainAgris) {
		this.prpPmainAgris = prpPmainAgris;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPname> getPrpPnames() {
		return this.prpPnames;
	}

	public void setPrpPnames(List<PrpPname> prpPnames) {
		this.prpPnames = prpPnames;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPagent> getPrpPagents() {
		return this.prpPagents;
	}

	public void setPrpPagents(List<PrpPagent> prpPagents) {
		this.prpPagents = prpPagents;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemCar> getPrpPitemCars() {
		return this.prpPitemCars;
	}

	public void setPrpPitemCars(List<PrpPitemCar> prpPitemCars) {
		this.prpPitemCars = prpPitemCars;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPinsured> getPrpPinsureds() {
		return this.prpPinsureds;
	}

	public void setPrpPinsureds(List<PrpPinsured> prpPinsureds) {
		this.prpPinsureds = prpPinsureds;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemProp> getPrpPitemProps() {
		return this.prpPitemProps;
	}

	public void setPrpPitemProps(List<PrpPitemProp> prpPitemProps) {
		this.prpPitemProps = prpPitemProps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPinsuredNature> getPrpPinsuredNatures() {
		return this.prpPinsuredNatures;
	}

	public void setPrpPinsuredNatures(List<PrpPinsuredNature> prpPinsuredNatures) {
		this.prpPinsuredNatures = prpPinsuredNatures;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemKind> getPrpPitemKinds() {
		return this.prpPitemKinds;
	}

	public void setPrpPitemKinds(List<PrpPitemKind> prpPitemKinds) {
		this.prpPitemKinds = prpPitemKinds;
	}
    
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmain> getPrpPmains() {
		return this.prpPmains;
	}

	public void setPrpPmains(List<PrpPmain> prpPmains) {
		this.prpPmains = prpPmains;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcoeff> getPrpPcoeffs() {
		return this.prpPcoeffs;
	}

	public void setPrpPcoeffs(List<PrpPcoeff> prpPcoeffs) {
		this.prpPcoeffs = prpPcoeffs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPengage> getPrpPengages() {
		return this.prpPengages;
	}

	public void setPrpPengages(List<PrpPengage> prpPengages) {
		this.prpPengages = prpPengages;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemCarExt> getPrpPitemCarExts() {
		return this.prpPitemCarExts;
	}

	public void setPrpPitemCarExts(List<PrpPitemCarExt> prpPitemCarExts) {
		this.prpPitemCarExts = prpPitemCarExts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainConstruct> getPrpPmainConstructs() {
		return this.prpPmainConstructs;
	}

	public void setPrpPmainConstructs(List<PrpPmainConstruct> prpPmainConstructs) {
		this.prpPmainConstructs = prpPmainConstructs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainLoan> getPrpPmainLoans() {
		return this.prpPmainLoans;
	}

	public void setPrpPmainLoans(List<PrpPmainLoan> prpPmainLoans) {
		this.prpPmainLoans = prpPmainLoans;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPinsuredArtif> getPrpPinsuredArtifs() {
		return this.prpPinsuredArtifs;
	}

	public void setPrpPinsuredArtifs(List<PrpPinsuredArtif> prpPinsuredArtifs) {
		this.prpPinsuredArtifs = prpPinsuredArtifs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPlimit> getPrpPlimits() {
		return this.prpPlimits;
	}

	public void setPrpPlimits(List<PrpPlimit> prpPlimits) {
		this.prpPlimits = prpPlimits;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPaddress> getPrpPaddresses() {
		return this.prpPaddresses;
	}

	public void setPrpPaddresses(List<PrpPaddress> prpPaddresses) {
		this.prpPaddresses = prpPaddresses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainProp> getPrpPmainProps() {
		return this.prpPmainProps;
	}

	public void setPrpPmainProps(List<PrpPmainProp> prpPmainProps) {
		this.prpPmainProps = prpPmainProps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPextendInfo> getPrpPextendInfos() {
		return this.prpPextendInfos;
	}

	public void setPrpPextendInfos(List<PrpPextendInfo> prpPextendInfos) {
		this.prpPextendInfos = prpPextendInfos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcontractPause> getPrpPcontractPauses() {
		return this.prpPcontractPauses;
	}

	public void setPrpPcontractPauses(List<PrpPcontractPause> prpPcontractPauses) {
		this.prpPcontractPauses = prpPcontractPauses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPtext> getPrpPtexts() {
		return this.prpPtexts;
	}

	public void setPrpPtexts(List<PrpPtext> prpPtexts) {
		this.prpPtexts = prpPtexts;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcargoDetail> getPrpPcargoDetails() {
		return prpPcargoDetails;
	}

	public void setPrpPcargoDetails(List<PrpPcargoDetail> prpPcargoDetails) {
		this.prpPcargoDetails = prpPcargoDetails;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcommissionDetail> getPrpPcommissionDetails() {
		return prpPcommissionDetails;
	}

	public void setPrpPcommissionDetails(
			List<PrpPcommissionDetail> prpPcommissionDetails) {
		this.prpPcommissionDetails = prpPcommissionDetails;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemAgriRelated> getPrpPitemAgriRelateds() {
		return prpPitemAgriRelateds;
	}

	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPclause> getPrpPclauses() {
		return prpPclauses;
	}

	public void setPrpPitemAgriRelateds(
			List<PrpPitemAgriRelated> prpPitemAgriRelateds) {
		this.prpPitemAgriRelateds = prpPitemAgriRelateds;
	}

	public void setPrpPclauses(List<PrpPclause> prpPclauses) {
		this.prpPclauses = prpPclauses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPinsuredIdvListNature> getPrpPinsuredIdvListNatures() {
		return prpPinsuredIdvListNatures;
	}

	public void setPrpPinsuredIdvListNatures(
			List<PrpPinsuredIdvListNature> prpPinsuredIdvListNatures) {
		this.prpPinsuredIdvListNatures = prpPinsuredIdvListNatures;
	}
	//BUG26027 添加保单贡献对应P表 add by liangjianze 20120327 start
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPcontriution> getPrpPcontriutions() {
		return prpPcontriutions;
	}

	public void setPrpPcontriutions(List<PrpPcontriution> prpPcontriutions) {
		this.prpPcontriutions = prpPcontriutions;
	}
	//BUG26027 添加保单贡献对应P表 add by liangjianze 20120327 end
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemCreditOth> getPrpPitemCreditOths() {
		return prpPitemCreditOths;
	}

	public void setPrpPitemCreditOths(List<PrpPitemCreditOth> prpPitemCreditOths) {
		this.prpPitemCreditOths = prpPitemCreditOths;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPinsuredCreditInvest> getPrpPinsuredCreditInvests() {
		return prpPinsuredCreditInvests;
	}

	public void setPrpPinsuredCreditInvests(
			List<PrpPinsuredCreditInvest> prpPinsuredCreditInvests) {
		this.prpPinsuredCreditInvests = prpPinsuredCreditInvests;
	}

	//RZHANGT2012081301 重要客户 add by liangjianze 20120906 start
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPmainCommon> getPrpPmainCommons() {
		return prpPmainCommons;
	}

	public void setPrpPmainCommons(List<PrpPmainCommon> prpPmainCommons) {
		this.prpPmainCommons = prpPmainCommons;
	}
	//RZHANGT2012081301 重要客户 add by liangjianze 20120906 end

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPanimal> getPrpPanimals() {
		return prpPanimals;
	}

	public void setPrpPanimals(List<PrpPanimal> prpPanimals) {
		this.prpPanimals = prpPanimals;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPclauseplan> getPrpPclauseplans() {
		return prpPclauseplans;
	}

	public void setPrpPclauseplans(List<PrpPclauseplan> prpPclauseplans) {
		this.prpPclauseplans = prpPclauseplans;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemKindDetail> getPrpPitemKindDetails() {
		return prpPitemKindDetails;
	}

	public void setPrpPitemKindDetails(List<PrpPitemKindDetail> prpPitemKindDetails) {
		this.prpPitemKindDetails = prpPitemKindDetails;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPhead")
	public List<PrpPitemKindTaxFee> getPrpPitemKindTaxFees() {
		return prpPitemKindTaxFees;
	}

	public void setPrpPitemKindTaxFees(List<PrpPitemKindTaxFee> prpPitemKindTaxFees) {
		this.prpPitemKindTaxFees = prpPitemKindTaxFees;
	}
	
	
}
