package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrpPitemCarExt generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppitem_carext")
public class PrpPitemCarExt implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 标的序号 */
	private PrpPitemCarExtId id;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 上年车损险发生赔款次数 */
	private BigDecimal lastDamagedA;
	/** 上年三者险发生赔款次数 */
	private BigDecimal lastDamagedB;
	/** 上年商业保险发生赔款次数 */
	private BigDecimal lastDamagedBI;
	/** 上年强制保险发生赔款次数 */
	private BigDecimal lastDamagedCI;
	/** 上年交强险发生交通安全违法行为次数 */
	private BigDecimal lastOffenceCI;
	/** 本年车损险发生赔款次数 */
	private BigDecimal thisDamagedA;
	/** 本年三者险发生赔款次数 */
	private BigDecimal thisDamagedB;
	/** 本年商业保险发生赔款次数 */
	private BigDecimal thisDamagedBI;
	/** 本年强制保险发生赔款次数 */
	private BigDecimal thisDamagedCI;
	/** 本年交强险发生交通安全违法行为次数 */
	private BigDecimal thisOffenceCI;
	/** 商业保险连续未出险年数 */
	private BigDecimal noDamYearsBI;
	/** 强制保险连续未出险年数 */
	private BigDecimal noDamYearsCI;
	/** 交强险连续未发生交通安全违法行为年数 */
	private BigDecimal noOffYearsCI;
	/** 交强险交通事故浮动比率 */
	private BigDecimal damFloatRatioCI;
	/** 交强险交通安全违法行为浮动比率 */
	private BigDecimal offFloatRatioCI;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;
	private List<PrpPtrafficDetail> prpPtrafficDetails = new ArrayList<PrpPtrafficDetail>(
			0);

	public PrpPitemCarExt() {
	}

	/**       
	 * 标的序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "itemno", nullable = false)) })
	public PrpPitemCarExtId getId() {
		return this.id;
	}

	public void setId(PrpPitemCarExtId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 上年车损险发生赔款次数
	 */

	@Column(name = "lastdamageda")
	public BigDecimal getLastDamagedA() {
		return this.lastDamagedA;
	}

	public void setLastDamagedA(BigDecimal lastDamagedA) {
		this.lastDamagedA = lastDamagedA;
	}

	/**       
	 * 上年三者险发生赔款次数
	 */

	@Column(name = "lastdamagedb")
	public BigDecimal getLastDamagedB() {
		return this.lastDamagedB;
	}

	public void setLastDamagedB(BigDecimal lastDamagedB) {
		this.lastDamagedB = lastDamagedB;
	}

	/**       
	 * 上年商业保险发生赔款次数
	 */

	@Column(name = "lastdamagedbi")
	public BigDecimal getLastDamagedBI() {
		return this.lastDamagedBI;
	}

	public void setLastDamagedBI(BigDecimal lastDamagedBI) {
		this.lastDamagedBI = lastDamagedBI;
	}

	/**       
	 * 上年强制保险发生赔款次数
	 */

	@Column(name = "lastdamagedci")
	public BigDecimal getLastDamagedCI() {
		return this.lastDamagedCI;
	}

	public void setLastDamagedCI(BigDecimal lastDamagedCI) {
		this.lastDamagedCI = lastDamagedCI;
	}

	/**       
	 * 上年交强险发生交通安全违法行为次数
	 */

	@Column(name = "lastoffenceci")
	public BigDecimal getLastOffenceCI() {
		return this.lastOffenceCI;
	}

	public void setLastOffenceCI(BigDecimal lastOffenceCI) {
		this.lastOffenceCI = lastOffenceCI;
	}

	/**       
	 * 本年车损险发生赔款次数
	 */

	@Column(name = "thisdamageda")
	public BigDecimal getThisDamagedA() {
		return this.thisDamagedA;
	}

	public void setThisDamagedA(BigDecimal thisDamagedA) {
		this.thisDamagedA = thisDamagedA;
	}

	/**       
	 * 本年三者险发生赔款次数
	 */

	@Column(name = "thisdamagedb")
	public BigDecimal getThisDamagedB() {
		return this.thisDamagedB;
	}

	public void setThisDamagedB(BigDecimal thisDamagedB) {
		this.thisDamagedB = thisDamagedB;
	}

	/**       
	 * 本年商业保险发生赔款次数
	 */

	@Column(name = "thisdamagedbi")
	public BigDecimal getThisDamagedBI() {
		return this.thisDamagedBI;
	}

	public void setThisDamagedBI(BigDecimal thisDamagedBI) {
		this.thisDamagedBI = thisDamagedBI;
	}

	/**       
	 * 本年强制保险发生赔款次数
	 */

	@Column(name = "thisdamagedci")
	public BigDecimal getThisDamagedCI() {
		return this.thisDamagedCI;
	}

	public void setThisDamagedCI(BigDecimal thisDamagedCI) {
		this.thisDamagedCI = thisDamagedCI;
	}

	/**       
	 * 本年交强险发生交通安全违法行为次数
	 */

	@Column(name = "thisoffenceci")
	public BigDecimal getThisOffenceCI() {
		return this.thisOffenceCI;
	}

	public void setThisOffenceCI(BigDecimal thisOffenceCI) {
		this.thisOffenceCI = thisOffenceCI;
	}

	/**       
	 * 商业保险连续未出险年数
	 */

	@Column(name = "nodamyearsbi")
	public BigDecimal getNoDamYearsBI() {
		return this.noDamYearsBI;
	}

	public void setNoDamYearsBI(BigDecimal noDamYearsBI) {
		this.noDamYearsBI = noDamYearsBI;
	}

	/**       
	 * 强制保险连续未出险年数
	 */

	@Column(name = "nodamyearsci")
	public BigDecimal getNoDamYearsCI() {
		return this.noDamYearsCI;
	}

	public void setNoDamYearsCI(BigDecimal noDamYearsCI) {
		this.noDamYearsCI = noDamYearsCI;
	}

	/**       
	 * 交强险连续未发生交通安全违法行为年数
	 */

	@Column(name = "nooffyearsci")
	public BigDecimal getNoOffYearsCI() {
		return this.noOffYearsCI;
	}

	public void setNoOffYearsCI(BigDecimal noOffYearsCI) {
		this.noOffYearsCI = noOffYearsCI;
	}

	/**       
	 * 交强险交通事故浮动比率
	 */

	@Column(name = "damfloatratioci")
	public BigDecimal getDamFloatRatioCI() {
		return this.damFloatRatioCI;
	}

	public void setDamFloatRatioCI(BigDecimal damFloatRatioCI) {
		this.damFloatRatioCI = damFloatRatioCI;
	}

	/**       
	 * 交强险交通安全违法行为浮动比率
	 */

	@Column(name = "offfloatratioci")
	public BigDecimal getOffFloatRatioCI() {
		return this.offFloatRatioCI;
	}

	public void setOffFloatRatioCI(BigDecimal offFloatRatioCI) {
		this.offFloatRatioCI = offFloatRatioCI;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpPitemCarExt")
	public List<PrpPtrafficDetail> getPrpPtrafficDetails() {
		return this.prpPtrafficDetails;
	}

	public void setPrpPtrafficDetails(List<PrpPtrafficDetail> prpPtrafficDetails) {
		this.prpPtrafficDetails = prpPtrafficDetails;
	}

}
