package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrpPcommission generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppcommission")
public class PrpPcommission implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 批单申请号 */
	private String applyNo;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	/** 保单号 */
	private String policyNo;
	/** 协议号 */
	private String agreementNo;
	/** 客户群代码 */
	private String customerGroupCode;
	/** 费用类型 */
	private String costType;
	/** 险种代码 */
	private String riskCode;
	/** 总保费 */
	private BigDecimal sumPremium;
	/** 费用比例 */
	private BigDecimal costRate;
	/** 费用默认上限 */
	private BigDecimal costRateUpper;
	/** 是否允许调整 */
	private String adjustFlag;
	/** 是否可超上限 */
	private String upperFlag;
	/** 核保辅助绝对上限 */
	private BigDecimal auditRate;
	/** 超上限人工核保 */
	private String auditFlag;
	/** 共保份额 */
	private BigDecimal coinsRate;
	/** 分保扣除 */
	private String coinsDeduct;
	/** 币别 */
	private String currency;
	/** 费用金额 */
	private BigDecimal costFee;
	/** 比例变化量 */
//	private BigDecimal chgCostRate;
	/** 手续费变化量 */
	private BigDecimal chgCostFee;
	/** 费用拆分方案代码 */
	private String configCode;
	/** 是否分期 */
	private String amortizeFlag;
	/** 跟单维度 */
	private String clauseKindFlag;
	/** 备注 */
	private String remark;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpPcommission() {
	}

	/**       
	 * 批单申请号
	 */
	@Id
	@Column(name = "applyno", unique = true, nullable = false)
	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", unique = true, nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 协议号
	 */

	@Column(name = "agreementno", nullable = false)
	public String getAgreementNo() {
		return this.agreementNo;
	}

	public void setAgreementNo(String agreementNo) {
		this.agreementNo = agreementNo;
	}

	/**       
	 * 客户群代码
	 */

	@Column(name = "customergroupcode", nullable = false)
	public String getCustomerGroupCode() {
		return this.customerGroupCode;
	}

	public void setCustomerGroupCode(String customerGroupCode) {
		this.customerGroupCode = customerGroupCode;
	}

	/**       
	 * 费用类型
	 */

	@Column(name = "costtype")
	public String getCostType() {
		return this.costType;
	}

	public void setCostType(String costType) {
		this.costType = costType;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}
	/**       
	 * 总保费
	 */

	@Column(name = "SUMPREMIUM")
	public BigDecimal getSumPremium() {
		if(sumPremium==null)
		{
			sumPremium = BigDecimal.ZERO;
		}
		return this.sumPremium;
	}

	public void setSumPremium(BigDecimal sumPremium) {
		this.sumPremium = sumPremium;
	}
	
	/**       
	 * 费用比例
	 */

	@Column(name = "costrate")
	public BigDecimal getCostRate() {
		return this.costRate;
	}

	public void setCostRate(BigDecimal costRate) {
		this.costRate = costRate;
	}

	/**       
	 * 费用默认上限
	 */

	@Column(name = "costrateupper")
	public BigDecimal getCostRateUpper() {
		return this.costRateUpper;
	}

	public void setCostRateUpper(BigDecimal costRateUpper) {
		this.costRateUpper = costRateUpper;
	}

	/**       
	 * 是否允许调整
	 */

	@Column(name = "adjustflag")
	public String getAdjustFlag() {
		return this.adjustFlag;
	}

	public void setAdjustFlag(String adjustFlag) {
		this.adjustFlag = adjustFlag;
	}

	/**       
	 * 是否可超上限
	 */

	@Column(name = "upperflag")
	public String getUpperFlag() {
		return this.upperFlag;
	}

	public void setUpperFlag(String upperFlag) {
		this.upperFlag = upperFlag;
	}

	/**       
	 * 核保辅助绝对上限
	 */

	@Column(name = "auditrate")
	public BigDecimal getAuditRate() {
		return this.auditRate;
	}

	public void setAuditRate(BigDecimal auditRate) {
		this.auditRate = auditRate;
	}

	/**       
	 * 超上限人工核保
	 */

	@Column(name = "auditflag")
	public String getAuditFlag() {
		return this.auditFlag;
	}

	public void setAuditFlag(String auditFlag) {
		this.auditFlag = auditFlag;
	}

	/**       
	 * 共保份额
	 */

	@Column(name = "coinsrate")
	public BigDecimal getCoinsRate() {
		return this.coinsRate;
	}

	public void setCoinsRate(BigDecimal coinsRate) {
		this.coinsRate = coinsRate;
	}
	/**       
	 * 费用比例变化量
	 */

//	@Column(name = "chgcostrate")
//	public BigDecimal getChgCostRate() {
//		return this.chgCostRate;
//	}
//
//	public void setChgCostRate(BigDecimal chgCostRate) {
//		this.chgCostRate = chgCostRate;
//	}	

	/**       
	 * 费用金额变化量
	 */

	@Column(name = "chgcostfee")
	public BigDecimal getChgCostFee() {
		return this.chgCostFee;
	}

	public void setChgCostFee(BigDecimal chgCostFee) {
		this.chgCostFee = chgCostFee;
	}
	/**       
	 * 分保扣除
	 */

	@Column(name = "coinsdeduct")
	public String getCoinsDeduct() {
		return this.coinsDeduct;
	}

	public void setCoinsDeduct(String coinsDeduct) {
		this.coinsDeduct = coinsDeduct;
	}

	/**       
	 * 币别
	 */

	@Column(name = "currency")
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/**       
	 * 费用金额
	 */

	@Column(name = "costfee")
	public BigDecimal getCostFee() {
		return this.costFee;
	}

	public void setCostFee(BigDecimal costFee) {
		this.costFee = costFee;
	}

	/**       
	 * 费用拆分方案代码
	 */

	@Column(name = "configcode", nullable = false)
	public String getConfigCode() {
		return this.configCode;
	}

	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}
	@Column(name = "amortizeflag")
	public String getAmortizeFlag() {
		return amortizeFlag;
	}

	public void setAmortizeFlag(String amortizeFlag) {
		this.amortizeFlag = amortizeFlag;
	}
	@Column(name = "clausekindflag")
	public String getClauseKindFlag() {
		return clauseKindFlag;
	}

	public void setClauseKindFlag(String clauseKindFlag) {
		this.clauseKindFlag = clauseKindFlag;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

}
