package com.sinosoft.fccb.policy.common.model;

// Generated 2010-4-21 18:20:11 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpPitemKind generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prppitemkind")
public class PrpPitemKind implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 序号 */
	private PrpPitemKindId id;
	/** 批单申请号 */
	private PrpPhead prpPhead;
	/** 批单号 */
	private String endorseNo;
	
	/** 保单号 */
	private String policyNo;
	/** 险种代码 */
	private String riskCode;
	/** 分户序号 */
	private Integer familyNo;
	/** 车系名称 */
	private String familyName;
	/** 项目代码 */
	private String projectCode;
	/** 条款编码 */
	private String clauseCode;
	/** 条款名称 */
	private String clauseName;
	/** 险别代码 */
	private String kindCode;
	/** 险别名称 */
	private String kindName;
	/** 标的序号 */
	private Integer itemNo;
	/** 标的项目类别代码 */
	private String itemCode;
	/** 标的项目明细名称 */
	private String itemDetailName;
	/** 组别号 */
	private Integer groupNo;
	/** 投保方式代码 */
	private String modeCode;
	/** 投保方式名称 */
	private String modeName;
	/** 起运日期 */
	private Date startDate;
	/** 起保小时 */
	private Integer startHour;
	/** 生效终止日期 */
	private Date endDate;
	/** 终保小时 */
	private Integer endHour;
	/** 车型 */
	private String model;
	/** 购置日期 */
	private Date buyDate;
	/** 地址序号 */
	private Integer addressNo;
	/** 是否计算保额标志 */
	private String calculateFlag;
	/** 币别 */
	private String currency;
	/** 单位保险金额 */
	private BigDecimal unitAmount;
	/** 数量 */
	private BigDecimal quantity;
	/** 担保物计量单位 */
	private String unit;
	/** 保险价值 */
	private BigDecimal value;
	/** 总保额 */
	private BigDecimal amount;
	/** 适应费率期数 */
	private Integer ratePeriod;
	/** 费率 */
	private BigDecimal rate;
	/** 短期费率标志 */
	private String shortRateFlag;
	/** 短期费率 */
	private BigDecimal shortRate;
	/** 预收保费 */
	private BigDecimal prePremium;
	/** 计算的保费 */
	private BigDecimal calPremium;
	/** 基本保费 */
	private BigDecimal basePremium;
	/** 标准保费 */
	private BigDecimal benchMarkPremium;
	/** 折扣率 */
	private BigDecimal discount;
	/** 保费调整比率(%) */
	private BigDecimal adjustRate;
	/** 每人保费 */
	private BigDecimal unitPremium;
	/** 应收保费 */
	private BigDecimal premium;
	/** 免赔率 */
	private BigDecimal deductibleRate;
	/** 免赔额 */
	private BigDecimal deductible;
	/** 短信转存后是否删除标记 */
	private String flag;
	/** 变化数量 */
	private BigDecimal chgQuantity;
	/** 保额变化量 */
	private BigDecimal chgAmount;
	/** 保费变化量 */
	private BigDecimal chgPremium;
	/** 税额 */
	private BigDecimal taxFee;
	/** 共方税额 */
	private BigDecimal taxFee_gb;
	/** 联方税额 */
	private BigDecimal taxFee_lb;
	/** 预收税额 */
	private BigDecimal taxFee_ys;
	/** 净保费 */
	private BigDecimal netPremium;
	/** 税率 */
	private BigDecimal taxRate;
	/** 增值税标志位*/
	private String taxFlag;
	/** 税额变化量 */
	private BigDecimal chgTaxFee;
	/** 预收保费税额变化量 */
	private BigDecimal chgTaxFee_ys;
	/** 共方税额变化量 */
	private BigDecimal chgTaxFee_gb;
	/** 联方税额变化量 */
	private BigDecimal chgTaxFee_lb;
	/** 营业税保费变化量*/
    private BigDecimal chgBusTaxPremium;
    /** 净保费变化量*/
    private BigDecimal chgNetPremium;
    /** 全额税 */
	private BigDecimal allTaxFee;
    /** 全额税变化量 */
	private BigDecimal chgAllTaxFee;
	/** 全额净保费 */
	private BigDecimal allNetPremium;
	/** 全额净保费变化量 */
	private BigDecimal chgAllNetPremium;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpPitemKind() {
	}

	/**       
	 * 序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "applyNo", column = @Column(name = "applyno", nullable = false)),
			@AttributeOverride(name = "itemKindNo", column = @Column(name = "itemkindno", nullable = false)) })
	public PrpPitemKindId getId() {
		return this.id;
	}

	public void setId(PrpPitemKindId id) {
		this.id = id;
	}

	/**       
	 * 批单申请号
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applyno", nullable = false, insertable = false, updatable = false)
	public PrpPhead getPrpPhead() {
		return this.prpPhead;
	}

	public void setPrpPhead(PrpPhead prpPhead) {
		this.prpPhead = prpPhead;
	}

	/**       
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**       
	 * 保单号
	 */

	@Column(name = "policyno", nullable = false)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**       
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 分户序号
	 */

	@Column(name = "familyno")
	public Integer getFamilyNo() {
		return this.familyNo;
	}

	public void setFamilyNo(Integer familyNo) {
		this.familyNo = familyNo;
	}

	/**       
	 * 车系名称
	 */

	@Column(name = "familyname")
	public String getFamilyName() {
		return this.familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	/**       
	 * 项目代码
	 */

	@Column(name = "projectcode", nullable = false)
	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	/**       
	 * 条款编码
	 */

	@Column(name = "clausecode")
	public String getClauseCode() {
		return this.clauseCode;
	}

	public void setClauseCode(String clauseCode) {
		this.clauseCode = clauseCode;
	}

	/**       
	 * 条款名称
	 */

	@Column(name = "clausename")
	public String getClauseName() {
		return this.clauseName;
	}

	public void setClauseName(String clauseName) {
		this.clauseName = clauseName;
	}

	/**       
	 * 险别代码
	 */

	@Column(name = "kindcode", nullable = false)
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	/**       
	 * 险别名称
	 */

	@Column(name = "kindname")
	public String getKindName() {
		return this.kindName;
	}

	public void setKindName(String kindName) {
		this.kindName = kindName;
	}

	/**       
	 * 标的序号
	 */

	@Column(name = "itemno", nullable = false)
	public Integer getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(Integer itemNo) {
		this.itemNo = itemNo;
	}

	/**       
	 * 标的项目类别代码
	 */

	@Column(name = "itemcode")
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	/**       
	 * 标的项目明细名称
	 */

	@Column(name = "itemdetailname")
	public String getItemDetailName() {
		return this.itemDetailName;
	}

	public void setItemDetailName(String itemDetailName) {
		this.itemDetailName = itemDetailName;
	}
	
	
	/**       
	 * 组别号
	 */

	@Column(name = "groupno")
	public Integer getGroupNo() {
		return groupNo;
	}

	public void setGroupNo(Integer groupNo) {
		this.groupNo = groupNo;
	}
	

	/**       
	 * 投保方式代码
	 */

	@Column(name = "modecode")
	public String getModeCode() {
		return this.modeCode;
	}

	public void setModeCode(String modeCode) {
		this.modeCode = modeCode;
	}

	/**       
	 * 投保方式名称
	 */

	@Column(name = "modename")
	public String getModeName() {
		return this.modeName;
	}

	public void setModeName(String modeName) {
		this.modeName = modeName;
	}

	/**       
	 * 起运日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "startdate")
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**       
	 * 起保小时
	 */

	@Column(name = "starthour")
	public Integer getStartHour() {
		return this.startHour;
	}

	public void setStartHour(Integer startHour) {
		this.startHour = startHour;
	}

	/**       
	 * 生效终止日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "enddate")
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**       
	 * 终保小时
	 */

	@Column(name = "endhour")
	public Integer getEndHour() {
		return this.endHour;
	}

	public void setEndHour(Integer endHour) {
		this.endHour = endHour;
	}

	/**       
	 * 车型
	 */

	@Column(name = "model")
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	/**       
	 * 购置日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "buydate")
	public Date getBuyDate() {
		return this.buyDate;
	}

	public void setBuyDate(Date buyDate) {
		this.buyDate = buyDate;
	}

	/**       
	 * 地址序号
	 */

	@Column(name = "addressno")
	public Integer getAddressNo() {
		return this.addressNo;
	}

	public void setAddressNo(Integer addressNo) {
		this.addressNo = addressNo;
	}

	/**       
	 * 是否计算保额标志
	 */

	@Column(name = "calculateflag")
	public String getCalculateFlag() {
		return this.calculateFlag;
	}

	public void setCalculateFlag(String calculateFlag) {
		this.calculateFlag = calculateFlag;
	}

	/**       
	 * 币别
	 */

	@Column(name = "currency")
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/**       
	 * 单位保险金额
	 */

	@Column(name = "unitamount")
	public BigDecimal getUnitAmount() {
		return this.unitAmount;
	}

	public void setUnitAmount(BigDecimal unitAmount) {
		this.unitAmount = unitAmount;
	}

	/**       
	 * 数量
	 */

	@Column(name = "quantity")
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	/**       
	 * 担保物计量单位
	 */

	@Column(name = "unit")
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**       
	 * 保险价值
	 */

	@Column(name = "value")
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	/**       
	 * 总保额
	 */

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**       
	 * 适应费率期数
	 */

	@Column(name = "rateperiod")
	public Integer getRatePeriod() {
		return this.ratePeriod;
	}

	public void setRatePeriod(Integer ratePeriod) {
		this.ratePeriod = ratePeriod;
	}

	/**       
	 * 费率
	 */

	@Column(name = "rate")
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	/**       
	 * 短期费率标志
	 */

	@Column(name = "shortrateflag")
	public String getShortRateFlag() {
		return this.shortRateFlag;
	}

	public void setShortRateFlag(String shortRateFlag) {
		this.shortRateFlag = shortRateFlag;
	}

	/**       
	 * 短期费率
	 */

	@Column(name = "shortrate")
	public BigDecimal getShortRate() {
		return this.shortRate;
	}

	public void setShortRate(BigDecimal shortRate) {
		this.shortRate = shortRate;
	}

	/**
	 * 计算后的保费
	 */
	@Column(name = "calpremium")
	public BigDecimal getCalPremium() {
		return calPremium;
	}

	public void setCalPremium(BigDecimal calPremium) {
		this.calPremium = calPremium;
	}
	/**       
	 * 基本保费
	 */

	@Column(name = "basepremium")
	public BigDecimal getBasePremium() {
		return this.basePremium;
	}

	public void setBasePremium(BigDecimal basePremium) {
		this.basePremium = basePremium;
	}

	/**       
	 * 标准保费
	 */

	@Column(name = "benchmarkpremium")
	public BigDecimal getBenchMarkPremium() {
		return this.benchMarkPremium;
	}

	public void setBenchMarkPremium(BigDecimal benchMarkPremium) {
		this.benchMarkPremium = benchMarkPremium;
	}

	/**       
	 * 折扣率
	 */

	@Column(name = "discount")
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	/**       
	 * 保费调整比率(%)
	 */

	@Column(name = "adjustrate")
	public BigDecimal getAdjustRate() {
		return this.adjustRate;
	}

	public void setAdjustRate(BigDecimal adjustRate) {
		this.adjustRate = adjustRate;
	}

	/**       
	 * 每人保费
	 */

	@Column(name = "unitpremium")
	public BigDecimal getUnitPremium() {
		return this.unitPremium;
	}

	public void setUnitPremium(BigDecimal unitPremium) {
		this.unitPremium = unitPremium;
	}

	/**       
	 * 应收保费
	 */

	@Column(name = "premium")
	public BigDecimal getPremium() {
		return this.premium;
	}

	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	/**       
	 * 免赔率
	 */

	@Column(name = "deductiblerate")
	public BigDecimal getDeductibleRate() {
		return this.deductibleRate;
	}

	public void setDeductibleRate(BigDecimal deductibleRate) {
		this.deductibleRate = deductibleRate;
	}

	/**       
	 * 免赔额
	 */

	@Column(name = "deductible")
	public BigDecimal getDeductible() {
		return this.deductible;
	}

	public void setDeductible(BigDecimal deductible) {
		this.deductible = deductible;
	}

	/**       
	 * 短信转存后是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 变化数量
	 */

	@Column(name = "chgquantity")
	public BigDecimal getChgQuantity() {
		return this.chgQuantity;
	}

	public void setChgQuantity(BigDecimal chgQuantity) {
		this.chgQuantity = chgQuantity;
	}

	/**       
	 * 保额变化量
	 */

	@Column(name = "chgamount")
	public BigDecimal getChgAmount() {
		return this.chgAmount;
	}

	public void setChgAmount(BigDecimal chgAmount) {
		this.chgAmount = chgAmount;
	}

	/**       
	 * 保费变化量
	 */

	@Column(name = "chgpremium")
	public BigDecimal getChgPremium() {
		return this.chgPremium;
	}

	public void setChgPremium(BigDecimal chgPremium) {
		this.chgPremium = chgPremium;
	}

	/**       
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**       
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
	
	/**       
	 * 预收保费
	 */

	@Column(name = "prepremium")
	public BigDecimal getPrePremium() {
		return prePremium;
	}

	public void setPrePremium(BigDecimal prePremium) {
		this.prePremium = prePremium;
	}
	
	/**       
	 * 税额
	 */
	
	@Column(name = "taxFee")
	public BigDecimal getTaxFee() {
		return taxFee;
	}

	public void setTaxFee(BigDecimal taxFee) {
		this.taxFee = taxFee;
	}

	/**       
	 * 净保费
	 */
	@Column(name = "netPremium")
	public BigDecimal getNetPremium() {
		return netPremium;
	}

	public void setNetPremium(BigDecimal netPremium) {
		this.netPremium = netPremium;
	}

	/**       
	 * 税率
	 */
	@Column(name = "taxRate")
	public BigDecimal getTaxRate() {
		return taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	/**       
	 * 增值税标志位
	 */
	@Column(name = "taxFlag")
	public String getTaxFlag() {
		return taxFlag;
	}

	public void setTaxFlag(String taxFlag) {
		this.taxFlag = taxFlag;
	}
	
	/**       
	 * 税额变化量
	 */
	@Column(name = "chgTaxFee")
	public BigDecimal getChgTaxFee() {
		return chgTaxFee;
	}

	public void setChgTaxFee(BigDecimal chgTaxFee) {
		this.chgTaxFee = chgTaxFee;
	}
	@Column(name = "chgbustaxpremium")
	public BigDecimal getChgBusTaxPremium() {
		return chgBusTaxPremium;
	}

	public void setChgBusTaxPremium(BigDecimal chgBusTaxPremium) {
		this.chgBusTaxPremium = chgBusTaxPremium;
	}
	@Column(name = "chgnetpremium")
	public BigDecimal getChgNetPremium() {
		return chgNetPremium;
	}

	public void setChgNetPremium(BigDecimal chgNetPremium) {
		this.chgNetPremium = chgNetPremium;
	}
	
	@Column(name = "taxFee_gb")
	public BigDecimal getTaxFee_gb() {
		return taxFee_gb;
	}

	public void setTaxFee_gb(BigDecimal taxFee_gb) {
		this.taxFee_gb = taxFee_gb;
	}
	
	@Column(name = "chgTaxFee_gb")
	public BigDecimal getChgTaxFee_gb() {
		return chgTaxFee_gb;
	}

	public void setChgTaxFee_gb(BigDecimal chgTaxFee_gb) {
		this.chgTaxFee_gb = chgTaxFee_gb;
	}
	@Column(name = "taxFee_lb")
	public BigDecimal getTaxFee_lb() {
		return taxFee_lb;
	}

	public void setTaxFee_lb(BigDecimal taxFee_lb) {
		this.taxFee_lb = taxFee_lb;
	}
	@Column(name = "chgTaxFee_lb")
	public BigDecimal getChgTaxFee_lb() {
		return chgTaxFee_lb;
	}

	public void setChgTaxFee_lb(BigDecimal chgTaxFee_lb) {
		this.chgTaxFee_lb = chgTaxFee_lb;
	}

	@Column(name = "chgTaxFee_ys")
	public BigDecimal getChgTaxFee_ys() {
		return chgTaxFee_ys;
	}

	public void setChgTaxFee_ys(BigDecimal chgTaxFee_ys) {
		this.chgTaxFee_ys = chgTaxFee_ys;
	}
	@Column(name = "taxFee_ys")
	public BigDecimal getTaxFee_ys() {
		return taxFee_ys;
	}

	public void setTaxFee_ys(BigDecimal taxFee_ys) {
		this.taxFee_ys = taxFee_ys;
	}
    /** 
     * 全单税 
     */
	@Column(name = "alltaxfee")
	public BigDecimal getAllTaxFee() {
		return allTaxFee;
	}

	public void setAllTaxFee(BigDecimal allTaxFee) {
		this.allTaxFee = allTaxFee;
	}
	/** 
	 * 全单税变化量
	 */
	@Column(name = "chgalltaxfee")
	public BigDecimal getChgAllTaxFee() {
		return chgAllTaxFee;
	}

	public void setChgAllTaxFee(BigDecimal chgAllTaxFee) {
		this.chgAllTaxFee = chgAllTaxFee;
	}

	/** 
	 * 全单净保费 
	 */
	@Column(name = "allnetpremium")
	public BigDecimal getAllNetPremium() {
		return allNetPremium;
	}

	public void setAllNetPremium(BigDecimal allNetPremium) {
		this.allNetPremium = allNetPremium;
	}

	/** 
	 * 全单净保费变化量 
	 */
	@Column(name = "chgallnetpremium")
	public BigDecimal getChgAllNetPremium() {
		return chgAllNetPremium;
	}

	public void setChgAllNetPremium(BigDecimal chgAllNetPremium) {
		this.chgAllNetPremium = chgAllNetPremium;
	}
	
}
