server:
  port: 1111
spring:
  application:
    name: service-unwrt
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: 123456

  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
feign:
  hystrix:
    enabled: false
    command:
      default:
        execution:
          timeout:
            enabled: false
          #isolation:
            #thread:
              #timeoutInMilliseconds: 20000
