package com.sinosoft.fccb.policy.premiumcal.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtiEndorsParamConfigId generated by Tools.Don't edit.
 */
@Embeddable
public class UtiEndorsParamConfigId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String riskCode;
	private String comCode;
	private String clauseCode;
	private String kindCode;

	public UtiEndorsParamConfigId() {
	}

	@Column(name = "riskcode")
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "comcode")
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "clausecode")
	public String getClauseCode() {
		return this.clauseCode;
	}

	public void setClauseCode(String clauseCode) {
		this.clauseCode = clauseCode;
	}

	@Column(name = "kindcode")
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtiEndorsParamConfigId))
			return false;
		UtiEndorsParamConfigId castOther = (UtiEndorsParamConfigId) other;

		return ((this.getRiskCode() == castOther.getRiskCode()) || (this
				.getRiskCode() != null
				&& castOther.getRiskCode() != null && this.getRiskCode()
				.equals(castOther.getRiskCode())))
				&& ((this.getComCode() == castOther.getComCode()) || (this
						.getComCode() != null
						&& castOther.getComCode() != null && this.getComCode()
						.equals(castOther.getComCode())))
				&& ((this.getClauseCode() == castOther.getClauseCode()) || (this
						.getClauseCode() != null
						&& castOther.getClauseCode() != null && this
						.getClauseCode().equals(castOther.getClauseCode())))
				&& ((this.getKindCode() == castOther.getKindCode()) || (this
						.getKindCode() != null
						&& castOther.getKindCode() != null && this
						.getKindCode().equals(castOther.getKindCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRiskCode() == null ? 0 : this.getRiskCode().hashCode());
		result = 37 * result
				+ (getComCode() == null ? 0 : this.getComCode().hashCode());
		result = 37
				* result
				+ (getClauseCode() == null ? 0 : this.getClauseCode()
						.hashCode());
		result = 37 * result
				+ (getKindCode() == null ? 0 : this.getKindCode().hashCode());
		return result;
	}

}
