package com.sinosoft.fccb.policy.premiumcal.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtiFormulaId generated by Tools.Don't edit.
 */
@Embeddable
public class UtiFormulaId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String riskCode;
	private String clauseCode;
	private String kindCode;
	private String comCode;
	private String calFormulaType;
	private String formulaType;
	private String factorCode;

	public UtiFormulaId() {
	}

	@Column(name = "riskcode")
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "clausecode")
	public String getClauseCode() {
		return this.clauseCode;
	}

	public void setClauseCode(String clauseCode) {
		this.clauseCode = clauseCode;
	}

	@Column(name = "kindcode")
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	@Column(name = "comcode")
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "calformulatype")
	public String getCalFormulaType() {
		return this.calFormulaType;
	}

	public void setCalFormulaType(String calFormulaType) {
		this.calFormulaType = calFormulaType;
	}

	@Column(name = "formulatype")
	public String getFormulaType() {
		return this.formulaType;
	}

	public void setFormulaType(String formulaType) {
		this.formulaType = formulaType;
	}

	@Column(name = "factorcode")
	public String getFactorCode() {
		return this.factorCode;
	}

	public void setFactorCode(String factorCode) {
		this.factorCode = factorCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtiFormulaId))
			return false;
		UtiFormulaId castOther = (UtiFormulaId) other;

		return ((this.getRiskCode() == castOther.getRiskCode()) || (this
				.getRiskCode() != null
				&& castOther.getRiskCode() != null && this.getRiskCode()
				.equals(castOther.getRiskCode())))
				&& ((this.getClauseCode() == castOther.getClauseCode()) || (this
						.getClauseCode() != null
						&& castOther.getClauseCode() != null && this
						.getClauseCode().equals(castOther.getClauseCode())))
				&& ((this.getKindCode() == castOther.getKindCode()) || (this
						.getKindCode() != null
						&& castOther.getKindCode() != null && this
						.getKindCode().equals(castOther.getKindCode())))
				&& ((this.getComCode() == castOther.getComCode()) || (this
						.getComCode() != null
						&& castOther.getComCode() != null && this.getComCode()
						.equals(castOther.getComCode())))
				&& ((this.getCalFormulaType() == castOther.getCalFormulaType()) || (this
						.getCalFormulaType() != null
						&& castOther.getCalFormulaType() != null && this
						.getCalFormulaType().equals(
								castOther.getCalFormulaType())))
				&& ((this.getFormulaType() == castOther.getFormulaType()) || (this
						.getFormulaType() != null
						&& castOther.getFormulaType() != null && this
						.getFormulaType().equals(castOther.getFormulaType())))
				&& ((this.getFactorCode() == castOther.getFactorCode()) || (this
						.getFactorCode() != null
						&& castOther.getFactorCode() != null && this
						.getFactorCode().equals(castOther.getFactorCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRiskCode() == null ? 0 : this.getRiskCode().hashCode());
		result = 37
				* result
				+ (getClauseCode() == null ? 0 : this.getClauseCode()
						.hashCode());
		result = 37 * result
				+ (getKindCode() == null ? 0 : this.getKindCode().hashCode());
		result = 37 * result
				+ (getComCode() == null ? 0 : this.getComCode().hashCode());
		result = 37
				* result
				+ (getCalFormulaType() == null ? 0 : this.getCalFormulaType()
						.hashCode());
		result = 37
				* result
				+ (getFormulaType() == null ? 0 : this.getFormulaType()
						.hashCode());
		result = 37
				* result
				+ (getFactorCode() == null ? 0 : this.getFactorCode()
						.hashCode());
		return result;
	}

}
