package com.sinosoft.fccb.policy.premiumcal.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UtiFactor generated by Tools.Don't edit.
 */
@Entity
@Table(name = "utifactor")
public class UtiFactor implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    /** 因子代码 */
    private UtiFactorId id;
    /** 条款代码 */
    private String clauseCode;
    /** 责任代码 */
    private String kindCode;
    /** 机构代码 */
    private String comCode;
    /** 因子名称 */
    private String factorName;
    /** 影响范围 */
    private String scope;
    /** 因子类型 */
    private String factorType;
    /** 控制标志字段 */
    private String controlType;
    /** 因子是否参与短期计算 */
    private String shortRateCalcFlag;
    /** 路径对象 */
    private String fromTable;
    /** 路径属性 */
    private String fromColumn;
    /** 代码类型 */
    private String codeType;
    /** 提示语 */
    private String message;
    /** 因子来源类型 */
    private String factorSourceType;
    /** 创建人 */
    private String creatorCode;
    /** 最后修改人 */
    private String updaterCode;
    /** 有效标志 */
    private String validStatus;
    /** 生效日期 */
    private Date validDate;
    /** 失效日期 */
    private Date invalidDate;
    /** 备注 */
    private String remark;
    /** 标志字段 */
    private String flag;
    /** 插入时间 */
    private Date insertTimeForHis;
    /** 更新时间 */
    private Date operateTimeForHis;

    public UtiFactor() {
    }

    /**
     * 因子代码
     */
    @EmbeddedId
    @AttributeOverrides( {
            @AttributeOverride(name = "riskCode", column = @Column(name = "riskcode")),
            @AttributeOverride(name = "factorCode", column = @Column(name = "factorcode")) })
    public UtiFactorId getId() {
        return this.id;
    }

    public void setId(UtiFactorId id) {
        this.id = id;
    }

    /**
     * 条款代码
     */

    @Column(name = "clausecode")
    public String getClauseCode() {
        return this.clauseCode;
    }

    public void setClauseCode(String clauseCode) {
        this.clauseCode = clauseCode;
    }

    /**
     * 责任代码
     */

    @Column(name = "kindcode")
    public String getKindCode() {
        return this.kindCode;
    }

    public void setKindCode(String kindCode) {
        this.kindCode = kindCode;
    }

    /**
     * 机构代码
     */

    @Column(name = "comcode")
    public String getComCode() {
        return this.comCode;
    }

    public void setComCode(String comCode) {
        this.comCode = comCode;
    }

    /**
     * 因子名称
     */

    @Column(name = "factorname")
    public String getFactorName() {
        return this.factorName;
    }

    public void setFactorName(String factorName) {
        this.factorName = factorName;
    }

    /**
     * 影响范围
     */

    @Column(name = "scope")
    public String getScope() {
        return this.scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * 因子类型
     */

    @Column(name = "factortype")
    public String getFactorType() {
        return this.factorType;
    }

    public void setFactorType(String factorType) {
        this.factorType = factorType;
    }

    /**
     * 控制标志字段
     */

    @Column(name = "controltype")
    public String getControlType() {
        return this.controlType;
    }

    public void setControlType(String controlType) {
        this.controlType = controlType;
    }

    /**
     * 因子是否参与短期计算
     */

    @Column(name = "shortratecalcflag")
    public String getShortRateCalcFlag() {
        return this.shortRateCalcFlag;
    }

    public void setShortRateCalcFlag(String shortRateCalcFlag) {
        this.shortRateCalcFlag = shortRateCalcFlag;
    }

    /**
     * 路径对象
     */

    @Column(name = "fromtable")
    public String getFromTable() {
        return this.fromTable;
    }

    public void setFromTable(String fromTable) {
        this.fromTable = fromTable;
    }

    /**
     * 路径属性
     */

    @Column(name = "fromcolumn")
    public String getFromColumn() {
        return this.fromColumn;
    }

    public void setFromColumn(String fromColumn) {
        this.fromColumn = fromColumn;
    }

    /**
     * 代码类型
     */

    @Column(name = "codetype")
    public String getCodeType() {
        return this.codeType;
    }

    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }

    /**
     * 提示语
     */

    @Column(name = "message")
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * 因子来源类型
     */

    @Column(name = "factorsourcetype")
    public String getFactorSourceType() {
        return this.factorSourceType;
    }

    public void setFactorSourceType(String factorSourceType) {
        this.factorSourceType = factorSourceType;
    }

    /**
     * 创建人
     */

    @Column(name = "creatorcode")
    public String getCreatorCode() {
        return this.creatorCode;
    }

    public void setCreatorCode(String creatorCode) {
        this.creatorCode = creatorCode;
    }

    /**
     * 最后修改人
     */

    @Column(name = "updatercode")
    public String getUpdaterCode() {
        return this.updaterCode;
    }

    public void setUpdaterCode(String updaterCode) {
        this.updaterCode = updaterCode;
    }

    /**
     * 有效标志
     */

    @Column(name = "validstatus")
    public String getValidStatus() {
        return this.validStatus;
    }

    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus;
    }

    /**
     * 生效日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "validdate")
    public Date getValidDate() {
        return this.validDate;
    }

    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * 失效日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "invaliddate")
    public Date getInvalidDate() {
        return this.invalidDate;
    }

    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * 备注
     */

    @Column(name = "remark")
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * 标志字段
     */

    @Column(name = "flag")
    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * 插入时间
     */

    @Column(name = "inserttimeforhis", insertable = false, updatable = false)
    public Date getInsertTimeForHis() {
        return this.insertTimeForHis;
    }

    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * 更新时间
     */

    @Column(name = "operatetimeforhis", insertable = false)
    public Date getOperateTimeForHis() {
        return this.operateTimeForHis;
    }

    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }

}
