package com.sinosoft.fccb.policy.premiumcal.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UtiFactorRelaShip generated by Tools.Don't edit.
 */
@Entity
@Table(name = "utifactorrelaship", uniqueConstraints = @UniqueConstraint(columnNames = {
        "factorcode", "riskcode", "clausecode", "comcode", "kindcode" }))
public class UtiFactorRelaShip implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 机构代码
     */
    private UtiFactorRelaShipId id;
    /**
     * 因子代码对照关系
     */
    private String relatedFactorCodes;
    /**
     * 创建人
     */
    private String creatorCode;
    /**
     * 最后修改人
     */
    private String updaterCode;
    /**
     * 有效标志
     */
    private String validStatus;
    /**
     * 生效日期
     */
    private Date validDate;
    /**
     * 失效日期
     */
    private Date invalidDate;
    /**
     * 备注
     */
    private String remark;
    /**
     * 标志字段
     */
    private String flag;
    /**
     * 插入时间
     */
    private Date insertTimeForHis;
    /**
     * 更新时间
     */
    private Date operateTimeForHis;

    public UtiFactorRelaShip() {
    }

    /**
     * 机构代码
     */
    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "riskCode", column = @Column(name = "riskcode")),
            @AttributeOverride(name = "factorCode", column = @Column(name = "factorcode")),
            @AttributeOverride(name = "clauseCode", column = @Column(name = "clausecode")),
            @AttributeOverride(name = "kindCode", column = @Column(name = "kindcode")),
            @AttributeOverride(name = "comCode", column = @Column(name = "comcode"))})
    public UtiFactorRelaShipId getId() {
        return this.id;
    }

    public void setId(UtiFactorRelaShipId id) {
        this.id = id;
    }

    /**
     * 因子代码对照关系
     */

    @Column(name = "relatedfactorcodes")
    public String getRelatedFactorCodes() {
        return this.relatedFactorCodes;
    }

    public void setRelatedFactorCodes(String relatedFactorCodes) {
        this.relatedFactorCodes = relatedFactorCodes;
    }

    /**
     * 创建人
     */

    @Column(name = "creatorcode")
    public String getCreatorCode() {
        return this.creatorCode;
    }

    public void setCreatorCode(String creatorCode) {
        this.creatorCode = creatorCode;
    }

    /**
     * 最后修改人
     */

    @Column(name = "updatercode")
    public String getUpdaterCode() {
        return this.updaterCode;
    }

    public void setUpdaterCode(String updaterCode) {
        this.updaterCode = updaterCode;
    }

    /**
     * 有效标志
     */

    @Column(name = "validstatus")
    public String getValidStatus() {
        return this.validStatus;
    }

    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus;
    }

    /**
     * 生效日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "validdate")
    public Date getValidDate() {
        return this.validDate;
    }

    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * 失效日期
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "invaliddate")
    public Date getInvalidDate() {
        return this.invalidDate;
    }

    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * 备注
     */

    @Column(name = "remark")
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * 标志字段
     */

    @Column(name = "flag")
    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * 插入时间
     */

    @Column(name = "inserttimeforhis", insertable = false, updatable = false)
    public Date getInsertTimeForHis() {
        return this.insertTimeForHis;
    }

    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * 更新时间
     */

    @Column(name = "operatetimeforhis", insertable = false)
    public Date getOperateTimeForHis() {
        return this.operateTimeForHis;
    }

    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }


}