server:
  port: 8761

eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka/
  instance.:
    prefer-ip-address: true
    hostname: localhost